import type {
  BackendJobStatus,
  BackendPreviewSection,
} from "@/shared/api/backend-contract";
import type { Locale } from "@/shared/i18n/locales";

type StatusMessage = {
  title: string;
  text: string;
  tone: "progress" | "warning" | "error" | "success";
  pending: boolean;
};

export type RealPreviewCopy = {
  status: Record<BackendJobStatus, StatusMessage>;
  workspaceEyebrow: string;
  pdfTitle: string;
  pptxTitle: string;
  sectionsTitle: string;
  previewLabel: string;
  inspectorTitle: string;
  globalWarningsTitle: string;
  noWarnings: string;
  noPreviewYet: string;
  up: string;
  down: string;
  restore: string;
  remove: string;
  split: string;
  merge: string;
  renderFinal: string;
  openDownload: string;
  cancel: string;
  retryFromConverter: string;
  revision: (value: number) => string;
  dimensions: (section: BackendPreviewSection) => string;
  fidelity: Record<BackendPreviewSection["fidelity"], string>;
  warnings: Record<string, string>;
  downloadEyebrow: string;
  downloadTitle: string;
  downloadPending: string;
  downloadFile: string;
  returnToPreview: string;
};

const realPreviewCopy: Record<
  Locale,
  RealPreviewCopy
> = {
  en: {
    status: {
      accepted: {
        title: "Request accepted",
        text: "The temporary conversion has been created.",
        tone: "progress",
        pending: true,
      },
      queued: {
        title: "Queued",
        text: "Waiting for an isolated browser worker.",
        tone: "progress",
        pending: true,
      },
      loading: {
        title: "Loading public page",
        text: "The destination is revalidated while resources load within fixed limits.",
        tone: "progress",
        pending: true,
      },
      analyzing: {
        title: "Analyzing sections",
        text: "Layout, safe links and editable elements are being mapped.",
        tone: "progress",
        pending: true,
      },
      preview_rendering: {
        title: "Rendering preview",
        text: "Temporary page or slide thumbnails are being created.",
        tone: "progress",
        pending: true,
      },
      preview_ready: {
        title: "Preview ready",
        text: "Review sections and visible fallbacks before final rendering.",
        tone: "success",
        pending: false,
      },
      final_queued: {
        title: "Final render queued",
        text: "The accepted preview revision is waiting for a worker.",
        tone: "progress",
        pending: true,
      },
      final_rendering: {
        title: "Rendering final file",
        text: "The final document uses the same preview revision shown here.",
        tone: "progress",
        pending: true,
      },
      download_ready: {
        title: "Download ready",
        text: "The temporary encrypted artifact is ready to download.",
        tone: "success",
        pending: false,
      },
      downloaded: {
        title: "Download completed",
        text: "The temporary artifact is entering its short deletion grace period.",
        tone: "success",
        pending: false,
      },
      failed_recoverable: {
        title: "Conversion interrupted",
        text: "The operation failed safely. Start a new preview to retry.",
        tone: "error",
        pending: false,
      },
      failed_terminal: {
        title: "Conversion stopped",
        text: "The source could not be processed within the safety limits.",
        tone: "error",
        pending: false,
      },
      cancelled: {
        title: "Conversion cancelled",
        text: "Queued work was stopped and temporary data will be removed.",
        tone: "warning",
        pending: false,
      },
      expired: {
        title: "Preview expired",
        text: "Temporary jobs are not retained as conversion history.",
        tone: "error",
        pending: false,
      },
    },
    workspaceEyebrow: "Secure temporary workspace",
    pdfTitle: "PDF pages",
    pptxTitle: "PowerPoint slides",
    sectionsTitle: "Sections",
    previewLabel: "Document preview",
    inspectorTitle: "Inspector",
    globalWarningsTitle: "Conversion warnings",
    noWarnings: "No conversion warnings for this section.",
    noPreviewYet: "The preview will appear when analysis is complete.",
    up: "Up",
    down: "Down",
    restore: "Restore",
    remove: "Remove",
    split: "Split",
    merge: "Merge",
    renderFinal: "Render final file",
    openDownload: "Open download",
    cancel: "Cancel conversion",
    retryFromConverter: "Start a new conversion",
    revision: (value: number): string => `Revision ${value}`,
    dimensions: (section: BackendPreviewSection): string =>
      `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: {
      native: "editable",
      mixed: "mixed fidelity",
      visual: "visual",
    },
    warnings: {
      RASTER_FALLBACK: "A complex element was rasterized.",
      FONT_SUBSTITUTED: "A web font was replaced with a safe document font.",
      RESOURCE_OMITTED: "A resource outside the safe budget was omitted.",
      STABILIZATION_INCOMPLETE:
        "The page did not become fully idle before capture.",
      LINK_REMOVED: "An unsafe or unsupported link was removed.",
      CRAWL_PAGE_SKIPPED: "A crawl target was skipped by scope or robots rules.",
    },
    downloadEyebrow: "Temporary encrypted artifact",
    downloadTitle: "Your file is ready",
    downloadPending: "The final document is still being prepared.",
    downloadFile: "Download file",
    returnToPreview: "Return to preview",
  },
  ru: {
    status: {
      accepted: {
        title: "Запрос принят",
        text: "Временная задача конвертации создана.",
        tone: "progress",
        pending: true,
      },
      queued: {
        title: "В очереди",
        text: "Ожидаем изолированный браузерный обработчик.",
        tone: "progress",
        pending: true,
      },
      loading: {
        title: "Загрузка общедоступной страницы",
        text: "Адрес повторно проверяется, а ресурсы загружаются в заданных лимитах.",
        tone: "progress",
        pending: true,
      },
      analyzing: {
        title: "Анализ секций",
        text: "Определяются макет, безопасные ссылки и редактируемые элементы.",
        tone: "progress",
        pending: true,
      },
      preview_rendering: {
        title: "Создание предпросмотра",
        text: "Формируются временные миниатюры страниц или слайдов.",
        tone: "progress",
        pending: true,
      },
      preview_ready: {
        title: "Предпросмотр готов",
        text: "Проверьте секции и видимые замены перед финальным созданием файла.",
        tone: "success",
        pending: false,
      },
      final_queued: {
        title: "Финальный файл в очереди",
        text: "Принятая ревизия предпросмотра ожидает обработчик.",
        tone: "progress",
        pending: true,
      },
      final_rendering: {
        title: "Создание итогового файла",
        text: "Документ создаётся из той же ревизии, которая показана здесь.",
        tone: "progress",
        pending: true,
      },
      download_ready: {
        title: "Файл готов",
        text: "Временный зашифрованный файл готов к скачиванию.",
        tone: "success",
        pending: false,
      },
      downloaded: {
        title: "Скачивание завершено",
        text: "Начался короткий период перед удалением временного файла.",
        tone: "success",
        pending: false,
      },
      failed_recoverable: {
        title: "Конвертация прервана",
        text: "Операция завершилась безопасно. Создайте новый предпросмотр для повтора.",
        tone: "error",
        pending: false,
      },
      failed_terminal: {
        title: "Конвертация остановлена",
        text: "Источник нельзя обработать в пределах безопасных ограничений.",
        tone: "error",
        pending: false,
      },
      cancelled: {
        title: "Конвертация отменена",
        text: "Работа остановлена, временные данные будут удалены.",
        tone: "warning",
        pending: false,
      },
      expired: {
        title: "Срок предпросмотра истёк",
        text: "Временные задачи не сохраняются как история конвертаций.",
        tone: "error",
        pending: false,
      },
    },
    workspaceEyebrow: "Безопасная временная рабочая область",
    pdfTitle: "Страницы PDF",
    pptxTitle: "Слайды PowerPoint",
    sectionsTitle: "Секции",
    previewLabel: "Предпросмотр документа",
    inspectorTitle: "Инспектор",
    globalWarningsTitle: "Предупреждения конвертации",
    noWarnings: "Для этой секции нет предупреждений.",
    noPreviewYet: "Предпросмотр появится после завершения анализа.",
    up: "Вверх",
    down: "Вниз",
    restore: "Вернуть",
    remove: "Удалить",
    split: "Разделить",
    merge: "Объединить",
    renderFinal: "Создать итоговый файл",
    openDownload: "Открыть скачивание",
    cancel: "Отменить конвертацию",
    retryFromConverter: "Начать новую конвертацию",
    revision: (value: number): string => `Ревизия ${value}`,
    dimensions: (section: BackendPreviewSection): string =>
      `${Math.round(section.width)} × ${Math.round(section.height)} пкс`,
    fidelity: {
      native: "редактируемый",
      mixed: "смешанная точность",
      visual: "визуальный",
    },
    warnings: {
      RASTER_FALLBACK: "Сложный элемент преобразован в изображение.",
      FONT_SUBSTITUTED: "Веб-шрифт заменён безопасным шрифтом документа.",
      RESOURCE_OMITTED: "Ресурс за пределами безопасного лимита пропущен.",
      STABILIZATION_INCOMPLETE:
        "Страница не перешла в полностью стабильное состояние.",
      LINK_REMOVED: "Небезопасная или неподдерживаемая ссылка удалена.",
      CRAWL_PAGE_SKIPPED:
        "Страница пропущена из-за области обхода или правил robots.",
    },
    downloadEyebrow: "Временный зашифрованный файл",
    downloadTitle: "Ваш файл готов",
    downloadPending: "Итоговый документ ещё создаётся.",
    downloadFile: "Скачать файл",
    returnToPreview: "Вернуться к предпросмотру",
  },
  de: {
    status: {
      accepted: {
        title: "Anfrage angenommen",
        text: "Die temporäre Konvertierung wurde erstellt.",
        tone: "progress",
        pending: true,
      },
      queued: {
        title: "In Warteschlange",
        text: "Warten auf einen isolierten Browser-Worker.",
        tone: "progress",
        pending: true,
      },
      loading: {
        title: "Öffentliche Seite wird geladen",
        text: "Das Ziel wird erneut geprüft, während Ressourcen innerhalb fester Grenzen geladen werden.",
        tone: "progress",
        pending: true,
      },
      analyzing: {
        title: "Abschnitte werden analysiert",
        text: "Layout, sichere Links und bearbeitbare Elemente werden erfasst.",
        tone: "progress",
        pending: true,
      },
      preview_rendering: {
        title: "Vorschau wird erstellt",
        text: "Temporäre Miniaturen der Seiten oder Folien werden erstellt.",
        tone: "progress",
        pending: true,
      },
      preview_ready: {
        title: "Vorschau bereit",
        text: "Prüfen Sie Abschnitte und sichtbare Ersetzungen vor der finalen Ausgabe.",
        tone: "success",
        pending: false,
      },
      final_queued: {
        title: "Finale Ausgabe in Warteschlange",
        text: "Die bestätigte Vorschauversion wartet auf einen Worker.",
        tone: "progress",
        pending: true,
      },
      final_rendering: {
        title: "Finale Datei wird erstellt",
        text: "Das endgültige Dokument verwendet dieselbe hier gezeigte Vorschauversion.",
        tone: "progress",
        pending: true,
      },
      download_ready: {
        title: "Download bereit",
        text: "Die temporäre verschlüsselte Datei kann heruntergeladen werden.",
        tone: "success",
        pending: false,
      },
      downloaded: {
        title: "Download abgeschlossen",
        text: "Für die temporäre Datei beginnt die kurze Frist bis zur Löschung.",
        tone: "success",
        pending: false,
      },
      failed_recoverable: {
        title: "Konvertierung unterbrochen",
        text: "Der Vorgang wurde sicher beendet. Starten Sie für einen neuen Versuch eine neue Vorschau.",
        tone: "error",
        pending: false,
      },
      failed_terminal: {
        title: "Konvertierung beendet",
        text: "Die Quelle konnte innerhalb der Sicherheitsgrenzen nicht verarbeitet werden.",
        tone: "error",
        pending: false,
      },
      cancelled: {
        title: "Konvertierung abgebrochen",
        text: "Die ausstehende Arbeit wurde beendet und temporäre Daten werden entfernt.",
        tone: "warning",
        pending: false,
      },
      expired: {
        title: "Vorschau abgelaufen",
        text: "Temporäre Aufgaben werden nicht als Konvertierungsverlauf gespeichert.",
        tone: "error",
        pending: false,
      },
    },
    workspaceEyebrow: "Sicherer temporärer Arbeitsbereich",
    pdfTitle: "PDF-Seiten",
    pptxTitle: "PowerPoint-Folien",
    sectionsTitle: "Abschnitte",
    previewLabel: "Dokumentvorschau",
    inspectorTitle: "Details",
    globalWarningsTitle: "Konvertierungswarnungen",
    noWarnings: "Für diesen Abschnitt liegen keine Konvertierungswarnungen vor.",
    noPreviewYet: "Die Vorschau erscheint nach Abschluss der Analyse.",
    up: "Nach oben",
    down: "Nach unten",
    restore: "Wiederherstellen",
    remove: "Entfernen",
    split: "Teilen",
    merge: "Verbinden",
    renderFinal: "Finale Datei erstellen",
    openDownload: "Download öffnen",
    cancel: "Konvertierung abbrechen",
    retryFromConverter: "Neue Konvertierung starten",
    revision: (value: number): string => `Version ${value}`,
    dimensions: (section: BackendPreviewSection): string =>
      `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: {
      native: "bearbeitbar",
      mixed: "gemischte Wiedergabetreue",
      visual: "Seitenaufnahme",
    },
    warnings: {
      RASTER_FALLBACK: "Ein komplexes Element wurde gerastert.",
      FONT_SUBSTITUTED: "Eine Webschrift wurde durch eine sichere Dokumentschrift ersetzt.",
      RESOURCE_OMITTED: "Eine Ressource außerhalb des sicheren Limits wurde ausgelassen.",
      STABILIZATION_INCOMPLETE:
        "Die Seite erreichte vor der Erfassung keinen vollständig stabilen Zustand.",
      LINK_REMOVED: "Ein unsicherer oder nicht unterstützter Link wurde entfernt.",
      CRAWL_PAGE_SKIPPED:
        "Ein Ziel wurde aufgrund des Umfangs oder der robots-Regeln übersprungen.",
    },
    downloadEyebrow: "Temporäre verschlüsselte Datei",
    downloadTitle: "Ihre Datei ist bereit",
    downloadPending: "Das endgültige Dokument wird noch erstellt.",
    downloadFile: "Datei herunterladen",
    returnToPreview: "Zurück zur Vorschau",
  },
  fr: {
    status: {
      accepted: {
        title: "Demande acceptée",
        text: "La conversion temporaire a été créée.",
        tone: "progress",
        pending: true,
      },
      queued: {
        title: "En attente",
        text: "En attente d’un processus de navigateur isolé.",
        tone: "progress",
        pending: true,
      },
      loading: {
        title: "Chargement de la page publique",
        text: "La destination est vérifiée à nouveau pendant le chargement des ressources dans les limites définies.",
        tone: "progress",
        pending: true,
      },
      analyzing: {
        title: "Analyse des sections",
        text: "La mise en page, les liens sûrs et les éléments modifiables sont en cours d’identification.",
        tone: "progress",
        pending: true,
      },
      preview_rendering: {
        title: "Création de l’aperçu",
        text: "Les miniatures temporaires des pages ou diapositives sont en cours de création.",
        tone: "progress",
        pending: true,
      },
      preview_ready: {
        title: "Aperçu prêt",
        text: "Vérifiez les sections et les remplacements visibles avant le rendu final.",
        tone: "success",
        pending: false,
      },
      final_queued: {
        title: "Rendu final en attente",
        text: "La version approuvée de l’aperçu attend un processus de traitement.",
        tone: "progress",
        pending: true,
      },
      final_rendering: {
        title: "Création du fichier final",
        text: "Le document final utilise la même version de l’aperçu que celle affichée ici.",
        tone: "progress",
        pending: true,
      },
      download_ready: {
        title: "Téléchargement prêt",
        text: "Le fichier temporaire chiffré est prêt à être téléchargé.",
        tone: "success",
        pending: false,
      },
      downloaded: {
        title: "Téléchargement terminé",
        text: "Le court délai précédant la suppression du fichier temporaire commence.",
        tone: "success",
        pending: false,
      },
      failed_recoverable: {
        title: "Conversion interrompue",
        text: "L’opération s’est arrêtée en toute sécurité. Créez un nouvel aperçu pour réessayer.",
        tone: "error",
        pending: false,
      },
      failed_terminal: {
        title: "Conversion arrêtée",
        text: "La source n’a pas pu être traitée dans les limites de sécurité.",
        tone: "error",
        pending: false,
      },
      cancelled: {
        title: "Conversion annulée",
        text: "Le travail en attente a été arrêté et les données temporaires seront supprimées.",
        tone: "warning",
        pending: false,
      },
      expired: {
        title: "Aperçu expiré",
        text: "Les tâches temporaires ne sont pas conservées dans un historique de conversions.",
        tone: "error",
        pending: false,
      },
    },
    workspaceEyebrow: "Espace de travail temporaire sécurisé",
    pdfTitle: "Pages PDF",
    pptxTitle: "Diapositives PowerPoint",
    sectionsTitle: "Sections",
    previewLabel: "Aperçu du document",
    inspectorTitle: "Détails",
    globalWarningsTitle: "Avertissements de conversion",
    noWarnings: "Aucun avertissement de conversion pour cette section.",
    noPreviewYet: "L’aperçu apparaîtra lorsque l’analyse sera terminée.",
    up: "Monter",
    down: "Descendre",
    restore: "Restaurer",
    remove: "Supprimer",
    split: "Scinder",
    merge: "Fusionner",
    renderFinal: "Créer le fichier final",
    openDownload: "Ouvrir le téléchargement",
    cancel: "Annuler la conversion",
    retryFromConverter: "Démarrer une nouvelle conversion",
    revision: (value: number): string => `Version ${value}`,
    dimensions: (section: BackendPreviewSection): string =>
      `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: {
      native: "modifiable",
      mixed: "fidélité mixte",
      visual: "capture de page",
    },
    warnings: {
      RASTER_FALLBACK: "Un élément complexe a été pixellisé.",
      FONT_SUBSTITUTED: "Une police web a été remplacée par une police de document sûre.",
      RESOURCE_OMITTED: "Une ressource dépassant la limite de sécurité a été omise.",
      STABILIZATION_INCOMPLETE:
        "La page n’était pas totalement stable avant la capture.",
      LINK_REMOVED: "Un lien non sûr ou non pris en charge a été supprimé.",
      CRAWL_PAGE_SKIPPED:
        "Une cible a été ignorée en raison du périmètre ou des règles robots.",
    },
    downloadEyebrow: "Fichier temporaire chiffré",
    downloadTitle: "Votre fichier est prêt",
    downloadPending: "Le document final est encore en cours de préparation.",
    downloadFile: "Télécharger le fichier",
    returnToPreview: "Retour à l’aperçu",
  },
  es: {
    status: {
      accepted: {
        title: "Solicitud aceptada",
        text: "Se ha creado la conversión temporal.",
        tone: "progress",
        pending: true,
      },
      queued: {
        title: "En cola",
        text: "Esperando un proceso de navegador aislado.",
        tone: "progress",
        pending: true,
      },
      loading: {
        title: "Cargando la página pública",
        text:
          "El destino se vuelve a validar mientras los recursos se cargan dentro de límites fijos.",
        tone: "progress",
        pending: true,
      },
      analyzing: {
        title: "Analizando secciones",
        text:
          "Se están identificando el diseño, los enlaces seguros y los elementos editables.",
        tone: "progress",
        pending: true,
      },
      preview_rendering: {
        title: "Creando la vista previa",
        text:
          "Se están creando miniaturas temporales de páginas o diapositivas.",
        tone: "progress",
        pending: true,
      },
      preview_ready: {
        title: "Vista previa lista",
        text:
          "Revise las secciones y las sustituciones visibles antes del renderizado final.",
        tone: "success",
        pending: false,
      },
      final_queued: {
        title: "Renderizado final en cola",
        text:
          "La revisión aceptada de la vista previa está esperando un proceso.",
        tone: "progress",
        pending: true,
      },
      final_rendering: {
        title: "Creando el archivo final",
        text:
          "El documento final usa la misma revisión de la vista previa que se muestra aquí.",
        tone: "progress",
        pending: true,
      },
      download_ready: {
        title: "Descarga lista",
        text:
          "El archivo temporal cifrado está listo para descargar.",
        tone: "success",
        pending: false,
      },
      downloaded: {
        title: "Descarga completada",
        text:
          "Ha comenzado el breve periodo previo a la eliminación del archivo temporal.",
        tone: "success",
        pending: false,
      },
      failed_recoverable: {
        title: "Conversión interrumpida",
        text:
          "La operación falló de forma segura. Inicie una nueva vista previa para volver a intentarlo.",
        tone: "error",
        pending: false,
      },
      failed_terminal: {
        title: "Conversión detenida",
        text:
          "La fuente no se pudo procesar dentro de los límites de seguridad.",
        tone: "error",
        pending: false,
      },
      cancelled: {
        title: "Conversión cancelada",
        text:
          "El trabajo pendiente se detuvo y los datos temporales se eliminarán.",
        tone: "warning",
        pending: false,
      },
      expired: {
        title: "Vista previa caducada",
        text:
          "Las tareas temporales no se conservan como historial de conversiones.",
        tone: "error",
        pending: false,
      },
    },
    workspaceEyebrow: "Espacio de trabajo temporal seguro",
    pdfTitle: "Páginas PDF",
    pptxTitle: "Diapositivas de PowerPoint",
    sectionsTitle: "Secciones",
    previewLabel: "Vista previa del documento",
    inspectorTitle: "Detalles",
    globalWarningsTitle: "Advertencias de conversión",
    noWarnings: "No hay advertencias de conversión para esta sección.",
    noPreviewYet: "La vista previa aparecerá cuando termine el análisis.",
    up: "Subir",
    down: "Bajar",
    restore: "Restaurar",
    remove: "Eliminar",
    split: "Dividir",
    merge: "Combinar",
    renderFinal: "Crear archivo final",
    openDownload: "Abrir descarga",
    cancel: "Cancelar conversión",
    retryFromConverter: "Iniciar una nueva conversión",
    revision: (value: number): string => `Revisión ${value}`,
    dimensions: (section: BackendPreviewSection): string =>
      `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: {
      native: "editable",
      mixed: "fidelidad mixta",
      visual: "captura de página",
    },
    warnings: {
      RASTER_FALLBACK: "Un elemento complejo se convirtió en imagen.",
      FONT_SUBSTITUTED:
        "Una fuente web se sustituyó por una fuente segura para documentos.",
      RESOURCE_OMITTED:
        "Se omitió un recurso que superaba el límite seguro.",
      STABILIZATION_INCOMPLETE:
        "La página no alcanzó un estado completamente estable antes de la captura.",
      LINK_REMOVED:
        "Se eliminó un enlace no seguro o no compatible.",
      CRAWL_PAGE_SKIPPED:
        "Se omitió un destino por el alcance o las reglas robots.",
    },
    downloadEyebrow: "Archivo temporal cifrado",
    downloadTitle: "Su archivo está listo",
    downloadPending: "El documento final todavía se está preparando.",
    downloadFile: "Descargar archivo",
    returnToPreview: "Volver a la vista previa",
  },
  nl: {
    status: {
      accepted: {
        title: "Aanvraag geaccepteerd",
        text: "De tijdelijke conversie is aangemaakt.",
        tone: "progress",
        pending: true,
      },
      queued: {
        title: "In wachtrij",
        text: "Wachten op een geïsoleerde browserworker.",
        tone: "progress",
        pending: true,
      },
      loading: {
        title: "Openbare pagina laden",
        text:
          "De bestemming wordt opnieuw gevalideerd terwijl bronnen binnen vaste grenzen worden geladen.",
        tone: "progress",
        pending: true,
      },
      analyzing: {
        title: "Secties analyseren",
        text:
          "Lay-out, veilige links en bewerkbare elementen worden in kaart gebracht.",
        tone: "progress",
        pending: true,
      },
      preview_rendering: {
        title: "Voorbeeld maken",
        text:
          "Tijdelijke miniaturen van pagina's of dia's worden gemaakt.",
        tone: "progress",
        pending: true,
      },
      preview_ready: {
        title: "Voorbeeld gereed",
        text:
          "Controleer secties en zichtbare vervangingen vóór de definitieve weergave.",
        tone: "success",
        pending: false,
      },
      final_queued: {
        title: "Definitieve weergave in wachtrij",
        text:
          "De geaccepteerde voorbeeldrevisie wacht op een worker.",
        tone: "progress",
        pending: true,
      },
      final_rendering: {
        title: "Definitief bestand maken",
        text:
          "Het definitieve document gebruikt dezelfde voorbeeldrevisie die hier wordt getoond.",
        tone: "progress",
        pending: true,
      },
      download_ready: {
        title: "Download gereed",
        text:
          "Het tijdelijke versleutelde bestand kan worden gedownload.",
        tone: "success",
        pending: false,
      },
      downloaded: {
        title: "Download voltooid",
        text:
          "De korte respijtperiode vóór verwijdering van het tijdelijke bestand is gestart.",
        tone: "success",
        pending: false,
      },
      failed_recoverable: {
        title: "Conversie onderbroken",
        text:
          "De bewerking is veilig mislukt. Start een nieuw voorbeeld om het opnieuw te proberen.",
        tone: "error",
        pending: false,
      },
      failed_terminal: {
        title: "Conversie gestopt",
        text:
          "De bron kon niet binnen de veiligheidsgrenzen worden verwerkt.",
        tone: "error",
        pending: false,
      },
      cancelled: {
        title: "Conversie geannuleerd",
        text:
          "Werk in de wachtrij is gestopt en tijdelijke gegevens worden verwijderd.",
        tone: "warning",
        pending: false,
      },
      expired: {
        title: "Voorbeeld verlopen",
        text:
          "Tijdelijke taken worden niet als conversiegeschiedenis bewaard.",
        tone: "error",
        pending: false,
      },
    },
    workspaceEyebrow: "Veilige tijdelijke werkruimte",
    pdfTitle: "PDF-pagina's",
    pptxTitle: "PowerPoint-dia's",
    sectionsTitle: "Secties",
    previewLabel: "Documentvoorbeeld",
    inspectorTitle: "Details",
    globalWarningsTitle: "Conversiewaarschuwingen",
    noWarnings: "Geen conversiewaarschuwingen voor deze sectie.",
    noPreviewYet: "Het voorbeeld verschijnt wanneer de analyse is voltooid.",
    up: "Omhoog",
    down: "Omlaag",
    restore: "Herstellen",
    remove: "Verwijderen",
    split: "Splitsen",
    merge: "Samenvoegen",
    renderFinal: "Definitief bestand maken",
    openDownload: "Download openen",
    cancel: "Conversie annuleren",
    retryFromConverter: "Nieuwe conversie starten",
    revision: (value: number): string => `Revisie ${value}`,
    dimensions: (section: BackendPreviewSection): string =>
      `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: {
      native: "bewerkbaar",
      mixed: "gemengde nauwkeurigheid",
      visual: "pagina-opname",
    },
    warnings: {
      RASTER_FALLBACK:
        "Een complex element is omgezet naar een rasterafbeelding.",
      FONT_SUBSTITUTED:
        "Een weblettertype is vervangen door een veilig documentlettertype.",
      RESOURCE_OMITTED:
        "Een bron buiten de veilige limiet is weggelaten.",
      STABILIZATION_INCOMPLETE:
        "De pagina werd vóór de vastlegging niet volledig stabiel.",
      LINK_REMOVED:
        "Een onveilige of niet-ondersteunde link is verwijderd.",
      CRAWL_PAGE_SKIPPED:
        "Een doel is overgeslagen vanwege het bereik of de robots-regels.",
    },
    downloadEyebrow: "Tijdelijk versleuteld bestand",
    downloadTitle: "Uw bestand is gereed",
    downloadPending: "Het definitieve document wordt nog voorbereid.",
    downloadFile: "Bestand downloaden",
    returnToPreview: "Terug naar voorbeeld",
  },
  pt: {
    status: {
      accepted: {
        title: "Pedido aceite",
        text: "A conversão temporária foi criada.",
        tone: "progress",
        pending: true,
      },
      queued: {
        title: "Em fila",
        text: "A aguardar um processo de navegador isolado.",
        tone: "progress",
        pending: true,
      },
      loading: {
        title: "A carregar a página pública",
        text:
          "O destino é novamente validado enquanto os recursos são carregados dentro de limites fixos.",
        tone: "progress",
        pending: true,
      },
      analyzing: {
        title: "A analisar secções",
        text:
          "O layout, as ligações seguras e os elementos editáveis estão a ser identificados.",
        tone: "progress",
        pending: true,
      },
      preview_rendering: {
        title: "A criar a pré-visualização",
        text:
          "Estão a ser criadas miniaturas temporárias de páginas ou diapositivos.",
        tone: "progress",
        pending: true,
      },
      preview_ready: {
        title: "Pré-visualização pronta",
        text:
          "Reveja as secções e as substituições visíveis antes da renderização final.",
        tone: "success",
        pending: false,
      },
      final_queued: {
        title: "Renderização final em fila",
        text:
          "A revisão aceite da pré-visualização está a aguardar um processo.",
        tone: "progress",
        pending: true,
      },
      final_rendering: {
        title: "A criar o ficheiro final",
        text:
          "O documento final utiliza a mesma revisão da pré-visualização apresentada aqui.",
        tone: "progress",
        pending: true,
      },
      download_ready: {
        title: "Transferência pronta",
        text:
          "O ficheiro temporário encriptado está pronto para transferência.",
        tone: "success",
        pending: false,
      },
      downloaded: {
        title: "Transferência concluída",
        text:
          "Começou o curto período antes da eliminação do ficheiro temporário.",
        tone: "success",
        pending: false,
      },
      failed_recoverable: {
        title: "Conversão interrompida",
        text:
          "A operação falhou de forma segura. Inicie uma nova pré-visualização para tentar novamente.",
        tone: "error",
        pending: false,
      },
      failed_terminal: {
        title: "Conversão parada",
        text:
          "Não foi possível processar a origem dentro dos limites de segurança.",
        tone: "error",
        pending: false,
      },
      cancelled: {
        title: "Conversão cancelada",
        text:
          "O trabalho em fila foi interrompido e os dados temporários serão eliminados.",
        tone: "warning",
        pending: false,
      },
      expired: {
        title: "Pré-visualização expirada",
        text:
          "As tarefas temporárias não são guardadas como histórico de conversões.",
        tone: "error",
        pending: false,
      },
    },
    workspaceEyebrow: "Área de trabalho temporária segura",
    pdfTitle: "Páginas PDF",
    pptxTitle: "Diapositivos PowerPoint",
    sectionsTitle: "Secções",
    previewLabel: "Pré-visualização do documento",
    inspectorTitle: "Detalhes",
    globalWarningsTitle: "Avisos de conversão",
    noWarnings: "Não existem avisos de conversão para esta secção.",
    noPreviewYet: "A pré-visualização aparecerá quando a análise terminar.",
    up: "Subir",
    down: "Descer",
    restore: "Restaurar",
    remove: "Remover",
    split: "Dividir",
    merge: "Combinar",
    renderFinal: "Criar ficheiro final",
    openDownload: "Abrir transferência",
    cancel: "Cancelar conversão",
    retryFromConverter: "Iniciar nova conversão",
    revision: (value: number): string => `Revisão ${value}`,
    dimensions: (section: BackendPreviewSection): string =>
      `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: {
      native: "editável",
      mixed: "fidelidade mista",
      visual: "captura de página",
    },
    warnings: {
      RASTER_FALLBACK:
        "Um elemento complexo foi convertido numa imagem rasterizada.",
      FONT_SUBSTITUTED:
        "Um tipo de letra web foi substituído por um tipo de letra seguro para documentos.",
      RESOURCE_OMITTED:
        "Foi omitido um recurso que excedia o limite seguro.",
      STABILIZATION_INCOMPLETE:
        "A página não atingiu um estado totalmente estável antes da captura.",
      LINK_REMOVED:
        "Foi removida uma ligação insegura ou não suportada.",
      CRAWL_PAGE_SKIPPED:
        "Um destino foi ignorado devido ao âmbito ou às regras robots.",
    },
    downloadEyebrow: "Ficheiro temporário encriptado",
    downloadTitle: "O seu ficheiro está pronto",
    downloadPending: "O documento final ainda está a ser preparado.",
    downloadFile: "Transferir ficheiro",
    returnToPreview: "Voltar à pré-visualização",
  },
  it: {
    status: {
      accepted: {
        title: "Richiesta accettata",
        text: "La conversione temporanea è stata creata.",
        tone: "progress",
        pending: true,
      },
      queued: {
        title: "In coda",
        text: "In attesa di un processo browser isolato.",
        tone: "progress",
        pending: true,
      },
      loading: {
        title: "Caricamento della pagina pubblica",
        text:
          "La destinazione viene convalidata di nuovo mentre le risorse vengono caricate entro limiti fissi.",
        tone: "progress",
        pending: true,
      },
      analyzing: {
        title: "Analisi delle sezioni",
        text:
          "Il layout, i link sicuri e gli elementi modificabili vengono identificati.",
        tone: "progress",
        pending: true,
      },
      preview_rendering: {
        title: "Creazione dell’anteprima",
        text:
          "Sono in fase di creazione miniature temporanee delle pagine o delle diapositive.",
        tone: "progress",
        pending: true,
      },
      preview_ready: {
        title: "Anteprima pronta",
        text:
          "Verifica le sezioni e le sostituzioni visibili prima del rendering finale.",
        tone: "success",
        pending: false,
      },
      final_queued: {
        title: "Rendering finale in coda",
        text:
          "La revisione accettata dell’anteprima è in attesa di un processo.",
        tone: "progress",
        pending: true,
      },
      final_rendering: {
        title: "Creazione del file finale",
        text:
          "Il documento finale usa la stessa revisione dell’anteprima mostrata qui.",
        tone: "progress",
        pending: true,
      },
      download_ready: {
        title: "Download pronto",
        text:
          "Il file temporaneo crittografato è pronto per il download.",
        tone: "success",
        pending: false,
      },
      downloaded: {
        title: "Download completato",
        text:
          "È iniziato il breve periodo prima dell’eliminazione del file temporaneo.",
        tone: "success",
        pending: false,
      },
      failed_recoverable: {
        title: "Conversione interrotta",
        text:
          "L’operazione non è riuscita in modo sicuro. Avvia una nuova anteprima per riprovare.",
        tone: "error",
        pending: false,
      },
      failed_terminal: {
        title: "Conversione arrestata",
        text:
          "Non è stato possibile elaborare la fonte entro i limiti di sicurezza.",
        tone: "error",
        pending: false,
      },
      cancelled: {
        title: "Conversione annullata",
        text:
          "Il lavoro in coda è stato interrotto e i dati temporanei saranno eliminati.",
        tone: "warning",
        pending: false,
      },
      expired: {
        title: "Anteprima scaduta",
        text:
          "Le attività temporanee non vengono conservate come cronologia delle conversioni.",
        tone: "error",
        pending: false,
      },
    },
    workspaceEyebrow: "Area di lavoro temporanea sicura",
    pdfTitle: "Pagine PDF",
    pptxTitle: "Diapositive PowerPoint",
    sectionsTitle: "Sezioni",
    previewLabel: "Anteprima del documento",
    inspectorTitle: "Dettagli",
    globalWarningsTitle: "Avvisi di conversione",
    noWarnings: "Nessun avviso di conversione per questa sezione.",
    noPreviewYet: "L’anteprima apparirà al termine dell’analisi.",
    up: "Sposta su",
    down: "Sposta giù",
    restore: "Ripristina",
    remove: "Rimuovi",
    split: "Dividi",
    merge: "Unisci",
    renderFinal: "Crea file finale",
    openDownload: "Apri download",
    cancel: "Annulla conversione",
    retryFromConverter: "Avvia nuova conversione",
    revision: (value: number): string => `Revisione ${value}`,
    dimensions: (section: BackendPreviewSection): string =>
      `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: {
      native: "modificabile",
      mixed: "fedeltà mista",
      visual: "acquisizione della pagina",
    },
    warnings: {
      RASTER_FALLBACK:
        "Un elemento complesso è stato convertito in un’immagine raster.",
      FONT_SUBSTITUTED:
        "Un font web è stato sostituito con un font sicuro per documenti.",
      RESOURCE_OMITTED:
        "È stata omessa una risorsa che superava il limite di sicurezza.",
      STABILIZATION_INCOMPLETE:
        "La pagina non ha raggiunto uno stato completamente stabile prima dell’acquisizione.",
      LINK_REMOVED:
        "È stato rimosso un link non sicuro o non supportato.",
      CRAWL_PAGE_SKIPPED:
        "Una destinazione è stata ignorata per l’ambito o le regole robots.",
    },
    downloadEyebrow: "File temporaneo crittografato",
    downloadTitle: "Il file è pronto",
    downloadPending: "Il documento finale è ancora in preparazione.",
    downloadFile: "Scarica file",
    returnToPreview: "Torna all’anteprima",
  },
  pl: {
    status: {
      accepted: { title: "Żądanie przyjęte", text: "Utworzono tymczasową konwersję.", tone: "progress", pending: true },
      queued: { title: "W kolejce", text: "Oczekiwanie na odizolowany proces przeglądarki.", tone: "progress", pending: true },
      loading: { title: "Wczytywanie publicznej strony", text: "Miejsce docelowe jest ponownie weryfikowane podczas wczytywania zasobów w ustalonych limitach.", tone: "progress", pending: true },
      analyzing: { title: "Analizowanie sekcji", text: "Mapowane są układ, bezpieczne łącza i elementy edytowalne.", tone: "progress", pending: true },
      preview_rendering: { title: "Tworzenie podglądu", text: "Tworzone są tymczasowe miniatury stron lub slajdów.", tone: "progress", pending: true },
      preview_ready: { title: "Podgląd gotowy", text: "Sprawdź sekcje i widoczne zastąpienia przed końcowym renderowaniem.", tone: "success", pending: false },
      final_queued: { title: "Końcowe renderowanie w kolejce", text: "Zaakceptowana wersja podglądu oczekuje na proces.", tone: "progress", pending: true },
      final_rendering: { title: "Tworzenie pliku końcowego", text: "Dokument końcowy korzysta z tej samej wersji podglądu, którą tu widzisz.", tone: "progress", pending: true },
      download_ready: { title: "Plik gotowy do pobrania", text: "Tymczasowy zaszyfrowany plik jest gotowy do pobrania.", tone: "success", pending: false },
      downloaded: { title: "Pobieranie zakończone", text: "Rozpoczął się krótki okres przed usunięciem tymczasowego pliku.", tone: "success", pending: false },
      failed_recoverable: { title: "Konwersja przerwana", text: "Operacja zakończyła się bezpiecznie niepowodzeniem. Utwórz nowy podgląd, aby spróbować ponownie.", tone: "error", pending: false },
      failed_terminal: { title: "Konwersja zatrzymana", text: "Nie udało się przetworzyć źródła w granicach bezpieczeństwa.", tone: "error", pending: false },
      cancelled: { title: "Konwersja anulowana", text: "Praca w kolejce została zatrzymana, a dane tymczasowe zostaną usunięte.", tone: "warning", pending: false },
      expired: { title: "Podgląd wygasł", text: "Tymczasowe zadania nie są przechowywane jako historia konwersji.", tone: "error", pending: false },
    },
    workspaceEyebrow: "Bezpieczny tymczasowy obszar roboczy",
    pdfTitle: "Strony PDF",
    pptxTitle: "Slajdy PowerPoint",
    sectionsTitle: "Sekcje",
    previewLabel: "Podgląd dokumentu",
    inspectorTitle: "Szczegóły",
    globalWarningsTitle: "Ostrzeżenia konwersji",
    noWarnings: "Brak ostrzeżeń konwersji dla tej sekcji.",
    noPreviewYet: "Podgląd pojawi się po zakończeniu analizy.",
    up: "W górę",
    down: "W dół",
    restore: "Przywróć",
    remove: "Usuń",
    split: "Podziel",
    merge: "Połącz",
    renderFinal: "Utwórz plik końcowy",
    openDownload: "Otwórz pobieranie",
    cancel: "Anuluj konwersję",
    retryFromConverter: "Rozpocznij nową konwersję",
    revision: (value: number): string => `Wersja ${value}`,
    dimensions: (section: BackendPreviewSection): string => `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: { native: "edytowalny", mixed: "mieszana wierność", visual: "zrzut strony" },
    warnings: {
      RASTER_FALLBACK: "Złożony element został zamieniony na obraz rastrowy.",
      FONT_SUBSTITUTED: "Czcionkę internetową zastąpiono bezpieczną czcionką dokumentu.",
      RESOURCE_OMITTED: "Pominięto zasób przekraczający bezpieczny limit.",
      STABILIZATION_INCOMPLETE: "Strona nie osiągnęła pełnej stabilności przed przechwyceniem.",
      LINK_REMOVED: "Usunięto niebezpieczne lub nieobsługiwane łącze.",
      CRAWL_PAGE_SKIPPED: "Pominięto cel ze względu na zakres lub reguły robots.",
    },
    downloadEyebrow: "Tymczasowy zaszyfrowany plik",
    downloadTitle: "Twój plik jest gotowy",
    downloadPending: "Dokument końcowy jest nadal przygotowywany.",
    downloadFile: "Pobierz plik",
    returnToPreview: "Wróć do podglądu",
  },
  cs: {
    status: {
      accepted: { title: "Požadavek přijat", text: "Dočasná konverze byla vytvořena.", tone: "progress", pending: true },
      queued: { title: "Ve frontě", text: "Čeká se na izolovaný proces prohlížeče.", tone: "progress", pending: true },
      loading: { title: "Načítání veřejné stránky", text: "Cíl se znovu ověřuje, zatímco se prostředky načítají v pevných limitech.", tone: "progress", pending: true },
      analyzing: { title: "Analýza částí", text: "Mapuje se rozvržení, bezpečné odkazy a upravitelné prvky.", tone: "progress", pending: true },
      preview_rendering: { title: "Vytváření náhledu", text: "Vytvářejí se dočasné miniatury stránek nebo snímků.", tone: "progress", pending: true },
      preview_ready: { title: "Náhled je připraven", text: "Před konečným vykreslením zkontrolujte části a viditelné náhrady.", tone: "success", pending: false },
      final_queued: { title: "Konečné vykreslení ve frontě", text: "Přijatá revize náhledu čeká na proces.", tone: "progress", pending: true },
      final_rendering: { title: "Vytváření konečného souboru", text: "Konečný dokument používá stejnou revizi náhledu, která je zde zobrazena.", tone: "progress", pending: true },
      download_ready: { title: "Stažení je připraveno", text: "Dočasný šifrovaný soubor je připraven ke stažení.", tone: "success", pending: false },
      downloaded: { title: "Stažení dokončeno", text: "Začala krátká lhůta před odstraněním dočasného souboru.", tone: "success", pending: false },
      failed_recoverable: { title: "Konverze přerušena", text: "Operace bezpečně selhala. Spusťte nový náhled a zkuste to znovu.", tone: "error", pending: false },
      failed_terminal: { title: "Konverze zastavena", text: "Zdroj nebylo možné zpracovat v bezpečnostních limitech.", tone: "error", pending: false },
      cancelled: { title: "Konverze zrušena", text: "Práce ve frontě byla zastavena a dočasná data budou odstraněna.", tone: "warning", pending: false },
      expired: { title: "Náhled vypršel", text: "Dočasné úlohy se neuchovávají jako historie konverzí.", tone: "error", pending: false },
    },
    workspaceEyebrow: "Bezpečný dočasný pracovní prostor",
    pdfTitle: "Stránky PDF",
    pptxTitle: "Snímky PowerPointu",
    sectionsTitle: "Části",
    previewLabel: "Náhled dokumentu",
    inspectorTitle: "Podrobnosti",
    globalWarningsTitle: "Upozornění konverze",
    noWarnings: "Pro tuto část nejsou žádná upozornění.",
    noPreviewYet: "Náhled se zobrazí po dokončení analýzy.",
    up: "Nahoru",
    down: "Dolů",
    restore: "Obnovit",
    remove: "Odstranit",
    split: "Rozdělit",
    merge: "Sloučit",
    renderFinal: "Vytvořit konečný soubor",
    openDownload: "Otevřít stažení",
    cancel: "Zrušit konverzi",
    retryFromConverter: "Spustit novou konverzi",
    revision: (value: number): string => `Revize ${value}`,
    dimensions: (section: BackendPreviewSection): string => `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: { native: "upravitelný", mixed: "smíšená věrnost", visual: "snímek stránky" },
    warnings: {
      RASTER_FALLBACK: "Složitý prvek byl převeden na rastrový obrázek.",
      FONT_SUBSTITUTED: "Webové písmo bylo nahrazeno bezpečným písmem dokumentu.",
      RESOURCE_OMITTED: "Prostředek překračující bezpečný limit byl vynechán.",
      STABILIZATION_INCOMPLETE: "Stránka před zachycením nedosáhla zcela stabilního stavu.",
      LINK_REMOVED: "Nebezpečný nebo nepodporovaný odkaz byl odstraněn.",
      CRAWL_PAGE_SKIPPED: "Cíl byl vynechán kvůli rozsahu nebo pravidlům robots.",
    },
    downloadEyebrow: "Dočasný šifrovaný soubor",
    downloadTitle: "Váš soubor je připraven",
    downloadPending: "Konečný dokument se stále připravuje.",
    downloadFile: "Stáhnout soubor",
    returnToPreview: "Zpět k náhledu",
  },
  sv: {
    status: {
      accepted: { title: "Begäran godkänd", text: "Den tillfälliga konverteringen har skapats.", tone: "progress", pending: true },
      queued: { title: "I kö", text: "Väntar på en isolerad webbläsarprocess.", tone: "progress", pending: true },
      loading: { title: "Läser in offentlig sida", text: "Målet valideras på nytt medan resurser läses in inom fasta gränser.", tone: "progress", pending: true },
      analyzing: { title: "Analyserar avsnitt", text: "Layout, säkra länkar och redigerbara element kartläggs.", tone: "progress", pending: true },
      preview_rendering: { title: "Skapar förhandsgranskning", text: "Tillfälliga miniatyrer av sidor eller bilder skapas.", tone: "progress", pending: true },
      preview_ready: { title: "Förhandsgranskningen är klar", text: "Granska avsnitt och synliga ersättningar före slutlig rendering.", tone: "success", pending: false },
      final_queued: { title: "Slutlig rendering i kö", text: "Den godkända versionen av förhandsgranskningen väntar på en process.", tone: "progress", pending: true },
      final_rendering: { title: "Skapar slutlig fil", text: "Det slutliga dokumentet använder samma version som visas i förhandsgranskningen.", tone: "progress", pending: true },
      download_ready: { title: "Filen är klar att hämta", text: "Den tillfälliga krypterade filen är klar att hämtas.", tone: "success", pending: false },
      downloaded: { title: "Hämtningen är klar", text: "Den korta perioden före radering av den tillfälliga filen har börjat.", tone: "success", pending: false },
      failed_recoverable: { title: "Konverteringen avbröts", text: "Åtgärden misslyckades på ett säkert sätt. Starta en ny förhandsgranskning och försök igen.", tone: "error", pending: false },
      failed_terminal: { title: "Konverteringen stoppades", text: "Källan kunde inte bearbetas inom säkerhetsgränserna.", tone: "error", pending: false },
      cancelled: { title: "Konverteringen avbruten", text: "Köat arbete stoppades och tillfälliga data kommer att raderas.", tone: "warning", pending: false },
      expired: { title: "Förhandsgranskningen har upphört", text: "Tillfälliga jobb sparas inte som konverteringshistorik.", tone: "error", pending: false },
    },
    workspaceEyebrow: "Säker tillfällig arbetsyta",
    pdfTitle: "PDF-sidor",
    pptxTitle: "PowerPoint-bilder",
    sectionsTitle: "Avsnitt",
    previewLabel: "Dokumentförhandsgranskning",
    inspectorTitle: "Detaljer",
    globalWarningsTitle: "Konverteringsvarningar",
    noWarnings: "Inga konverteringsvarningar för detta avsnitt.",
    noPreviewYet: "Förhandsgranskningen visas när analysen är klar.",
    up: "Upp",
    down: "Ned",
    restore: "Återställ",
    remove: "Ta bort",
    split: "Dela",
    merge: "Slå samman",
    renderFinal: "Skapa slutlig fil",
    openDownload: "Öppna hämtning",
    cancel: "Avbryt konvertering",
    retryFromConverter: "Starta en ny konvertering",
    revision: (value: number): string => `Version ${value}`,
    dimensions: (section: BackendPreviewSection): string => `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: { native: "redigerbar", mixed: "blandad trohet", visual: "sidbild" },
    warnings: {
      RASTER_FALLBACK: "Ett komplext element omvandlades till en rasterbild.",
      FONT_SUBSTITUTED: "Ett webbtypsnitt ersattes med ett säkert dokumenttypsnitt.",
      RESOURCE_OMITTED: "En resurs över den säkra gränsen utelämnades.",
      STABILIZATION_INCOMPLETE: "Sidan blev inte helt stabil före fångsten.",
      LINK_REMOVED: "En osäker eller ej stödd länk togs bort.",
      CRAWL_PAGE_SKIPPED: "Ett mål hoppades över på grund av omfattning eller robots-regler.",
    },
    downloadEyebrow: "Tillfällig krypterad fil",
    downloadTitle: "Din fil är klar",
    downloadPending: "Det slutliga dokumentet förbereds fortfarande.",
    downloadFile: "Hämta fil",
    returnToPreview: "Tillbaka till förhandsgranskningen",
  },
  no: {
    status: {
      accepted: { title: "Forespørsel godkjent", text: "Den midlertidige konverteringen er opprettet.", tone: "progress", pending: true },
      queued: { title: "I kø", text: "Venter på en isolert nettleserprosess.", tone: "progress", pending: true },
      loading: { title: "Laster offentlig side", text: "Målet valideres på nytt mens ressurser lastes innenfor faste grenser.", tone: "progress", pending: true },
      analyzing: { title: "Analyserer deler", text: "Layout, sikre lenker og redigerbare elementer kartlegges.", tone: "progress", pending: true },
      preview_rendering: { title: "Oppretter forhåndsvisning", text: "Midlertidige miniatyrbilder av sider eller lysbilder opprettes.", tone: "progress", pending: true },
      preview_ready: { title: "Forhåndsvisningen er klar", text: "Kontroller deler og synlige erstatninger før endelig gjengivelse.", tone: "success", pending: false },
      final_queued: { title: "Endelig gjengivelse i kø", text: "Den godkjente versjonen av forhåndsvisningen venter på en prosess.", tone: "progress", pending: true },
      final_rendering: { title: "Oppretter endelig fil", text: "Det endelige dokumentet bruker samme versjon som vises i forhåndsvisningen.", tone: "progress", pending: true },
      download_ready: { title: "Filen er klar til nedlasting", text: "Den midlertidige krypterte filen er klar til nedlasting.", tone: "success", pending: false },
      downloaded: { title: "Nedlasting fullført", text: "Den korte perioden før den midlertidige filen slettes, har startet.", tone: "success", pending: false },
      failed_recoverable: { title: "Konverteringen ble avbrutt", text: "Handlingen mislyktes på en sikker måte. Start en ny forhåndsvisning og prøv igjen.", tone: "error", pending: false },
      failed_terminal: { title: "Konverteringen ble stoppet", text: "Kilden kunne ikke behandles innenfor sikkerhetsgrensene.", tone: "error", pending: false },
      cancelled: { title: "Konverteringen er avbrutt", text: "Arbeid i kø ble stoppet, og midlertidige data blir slettet.", tone: "warning", pending: false },
      expired: { title: "Forhåndsvisningen er utløpt", text: "Midlertidige jobber lagres ikke som konverteringshistorikk.", tone: "error", pending: false },
    },
    workspaceEyebrow: "Sikkert midlertidig arbeidsområde",
    pdfTitle: "PDF-sider",
    pptxTitle: "PowerPoint-lysbilder",
    sectionsTitle: "Deler",
    previewLabel: "Dokumentforhåndsvisning",
    inspectorTitle: "Detaljer",
    globalWarningsTitle: "Konverteringsvarsler",
    noWarnings: "Ingen konverteringsvarsler for denne delen.",
    noPreviewYet: "Forhåndsvisningen vises når analysen er ferdig.",
    up: "Opp",
    down: "Ned",
    restore: "Gjenopprett",
    remove: "Fjern",
    split: "Del",
    merge: "Slå sammen",
    renderFinal: "Opprett endelig fil",
    openDownload: "Åpne nedlasting",
    cancel: "Avbryt konvertering",
    retryFromConverter: "Start en ny konvertering",
    revision: (value: number): string => `Versjon ${value}`,
    dimensions: (section: BackendPreviewSection): string => `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: { native: "redigerbar", mixed: "blandet trohet", visual: "sidebilde" },
    warnings: {
      RASTER_FALLBACK: "Et komplekst element ble konvertert til et rasterbilde.",
      FONT_SUBSTITUTED: "En nettskrift ble erstattet med en sikker dokumentskrift.",
      RESOURCE_OMITTED: "En ressurs over den sikre grensen ble utelatt.",
      STABILIZATION_INCOMPLETE: "Siden ble ikke helt stabil før fangsten.",
      LINK_REMOVED: "En usikker eller ikke støttet lenke ble fjernet.",
      CRAWL_PAGE_SKIPPED: "Et mål ble hoppet over på grunn av omfang eller robots-regler.",
    },
    downloadEyebrow: "Midlertidig kryptert fil",
    downloadTitle: "Filen din er klar",
    downloadPending: "Det endelige dokumentet forberedes fortsatt.",
    downloadFile: "Last ned fil",
    returnToPreview: "Tilbake til forhåndsvisningen",
  },
  da: {
    status: {
      accepted: { title: "Anmodning accepteret", text: "Den midlertidige konvertering er oprettet.", tone: "progress", pending: true },
      queued: { title: "I kø", text: "Venter på en isoleret browserproces.", tone: "progress", pending: true },
      loading: { title: "Indlæser offentlig side", text: "Målet valideres igen, mens ressourcer indlæses inden for faste grænser.", tone: "progress", pending: true },
      analyzing: { title: "Analyserer afsnit", text: "Layout, sikre links og redigerbare elementer kortlægges.", tone: "progress", pending: true },
      preview_rendering: { title: "Opretter forhåndsvisning", text: "Der oprettes midlertidige miniaturebilleder af sider eller dias.", tone: "progress", pending: true },
      preview_ready: { title: "Forhåndsvisningen er klar", text: "Kontrollér afsnit og synlige erstatninger før den endelige gengivelse.", tone: "success", pending: false },
      final_queued: { title: "Endelig gengivelse i kø", text: "Den godkendte version af forhåndsvisningen venter på en proces.", tone: "progress", pending: true },
      final_rendering: { title: "Opretter endelig fil", text: "Det endelige dokument bruger den samme version, som vises i forhåndsvisningen.", tone: "progress", pending: true },
      download_ready: { title: "Filen er klar til download", text: "Den midlertidige krypterede fil er klar til download.", tone: "success", pending: false },
      downloaded: { title: "Download fuldført", text: "Den korte periode, før den midlertidige fil slettes, er startet.", tone: "success", pending: false },
      failed_recoverable: { title: "Konverteringen blev afbrudt", text: "Handlingen mislykkedes på en sikker måde. Start en ny forhåndsvisning, og prøv igen.", tone: "error", pending: false },
      failed_terminal: { title: "Konverteringen blev stoppet", text: "Kilden kunne ikke behandles inden for sikkerhedsgrænserne.", tone: "error", pending: false },
      cancelled: { title: "Konverteringen er annulleret", text: "Arbejde i kø blev stoppet, og midlertidige data slettes.", tone: "warning", pending: false },
      expired: { title: "Forhåndsvisningen er udløbet", text: "Midlertidige opgaver gemmes ikke som konverteringshistorik.", tone: "error", pending: false },
    },
    workspaceEyebrow: "Sikkert midlertidigt arbejdsområde",
    pdfTitle: "PDF-sider",
    pptxTitle: "PowerPoint-dias",
    sectionsTitle: "Afsnit",
    previewLabel: "Dokumentforhåndsvisning",
    inspectorTitle: "Detaljer",
    globalWarningsTitle: "Konverteringsadvarsler",
    noWarnings: "Ingen konverteringsadvarsler for dette afsnit.",
    noPreviewYet: "Forhåndsvisningen vises, når analysen er færdig.",
    up: "Op",
    down: "Ned",
    restore: "Gendan",
    remove: "Fjern",
    split: "Opdel",
    merge: "Flet",
    renderFinal: "Opret endelig fil",
    openDownload: "Åbn download",
    cancel: "Annullér konvertering",
    retryFromConverter: "Start en ny konvertering",
    revision: (value: number): string => `Version ${value}`,
    dimensions: (section: BackendPreviewSection): string => `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: { native: "redigerbar", mixed: "blandet nøjagtighed", visual: "sidebillede" },
    warnings: {
      RASTER_FALLBACK: "Et komplekst element blev konverteret til et rasterbillede.",
      FONT_SUBSTITUTED: "En webskrifttype blev erstattet med en sikker dokumentskrifttype.",
      RESOURCE_OMITTED: "En ressource over den sikre grænse blev udeladt.",
      STABILIZATION_INCOMPLETE: "Siden blev ikke helt stabil før optagelsen.",
      LINK_REMOVED: "Et usikkert eller ikke-understøttet link blev fjernet.",
      CRAWL_PAGE_SKIPPED: "Et mål blev sprunget over på grund af omfang eller robots-regler.",
    },
    downloadEyebrow: "Midlertidig krypteret fil",
    downloadTitle: "Din fil er klar",
    downloadPending: "Det endelige dokument er stadig ved at blive forberedt.",
    downloadFile: "Download fil",
    returnToPreview: "Tilbage til forhåndsvisningen",
  },
  fi: {
    status: {
      accepted: { title: "Pyyntö hyväksytty", text: "Väliaikainen muunnos on luotu.", tone: "progress", pending: true },
      queued: { title: "Jonossa", text: "Odotetaan eristettyä selainprosessia.", tone: "progress", pending: true },
      loading: { title: "Ladataan julkista sivua", text: "Kohde vahvistetaan uudelleen, kun resurssit ladataan kiinteiden rajojen sisällä.", tone: "progress", pending: true },
      analyzing: { title: "Analysoidaan osioita", text: "Asettelu, turvalliset linkit ja muokattavat elementit kartoitetaan.", tone: "progress", pending: true },
      preview_rendering: { title: "Luodaan esikatselua", text: "Sivuista tai dioista luodaan väliaikaiset pienoiskuvat.", tone: "progress", pending: true },
      preview_ready: { title: "Esikatselu on valmis", text: "Tarkista osiot ja näkyvät korvaukset ennen lopullista renderöintiä.", tone: "success", pending: false },
      final_queued: { title: "Lopullinen renderöinti jonossa", text: "Hyväksytty esikatseluversio odottaa prosessia.", tone: "progress", pending: true },
      final_rendering: { title: "Luodaan lopullista tiedostoa", text: "Lopullinen asiakirja käyttää samaa versiota kuin esikatselu.", tone: "progress", pending: true },
      download_ready: { title: "Tiedosto on valmis ladattavaksi", text: "Väliaikainen salattu tiedosto on valmis ladattavaksi.", tone: "success", pending: false },
      downloaded: { title: "Lataus valmis", text: "Lyhyt aika ennen väliaikaisen tiedoston poistamista on alkanut.", tone: "success", pending: false },
      failed_recoverable: { title: "Muunnos keskeytyi", text: "Toiminto epäonnistui turvallisesti. Aloita uusi esikatselu ja yritä uudelleen.", tone: "error", pending: false },
      failed_terminal: { title: "Muunnos pysäytettiin", text: "Lähdettä ei voitu käsitellä turvallisuusrajojen puitteissa.", tone: "error", pending: false },
      cancelled: { title: "Muunnos peruutettu", text: "Jonossa ollut työ pysäytettiin ja väliaikaisia tietoja poistetaan.", tone: "warning", pending: false },
      expired: { title: "Esikatselu on vanhentunut", text: "Väliaikaisia tehtäviä ei tallenneta muunnoshistoriaksi.", tone: "error", pending: false },
    },
    workspaceEyebrow: "Turvallinen väliaikainen työtila",
    pdfTitle: "PDF-sivut",
    pptxTitle: "PowerPoint-diat",
    sectionsTitle: "Osiot",
    previewLabel: "Asiakirjan esikatselu",
    inspectorTitle: "Tiedot",
    globalWarningsTitle: "Muunnosvaroitukset",
    noWarnings: "Tälle osiolle ei ole muunnosvaroituksia.",
    noPreviewYet: "Esikatselu tulee näkyviin, kun analyysi on valmis.",
    up: "Ylös",
    down: "Alas",
    restore: "Palauta",
    remove: "Poista",
    split: "Jaa",
    merge: "Yhdistä",
    renderFinal: "Luo lopullinen tiedosto",
    openDownload: "Avaa lataus",
    cancel: "Peruuta muunnos",
    retryFromConverter: "Aloita uusi muunnos",
    revision: (value: number): string => `Versio ${value}`,
    dimensions: (section: BackendPreviewSection): string => `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: { native: "muokattava", mixed: "yhdistetty tarkkuus", visual: "sivukaappaus" },
    warnings: {
      RASTER_FALLBACK: "Monimutkainen elementti muunnettiin rasterikuvaksi.",
      FONT_SUBSTITUTED: "Verkkofontti korvattiin turvallisella asiakirjafontilla.",
      RESOURCE_OMITTED: "Turvallisen rajan ylittävä resurssi jätettiin pois.",
      STABILIZATION_INCOMPLETE: "Sivu ei vakiintunut täysin ennen kaappausta.",
      LINK_REMOVED: "Vaarallinen tai tukematon linkki poistettiin.",
      CRAWL_PAGE_SKIPPED: "Kohde ohitettiin laajuuden tai robots-sääntöjen vuoksi.",
    },
    downloadEyebrow: "Väliaikainen salattu tiedosto",
    downloadTitle: "Tiedostosi on valmis",
    downloadPending: "Lopullista asiakirjaa valmistellaan edelleen.",
    downloadFile: "Lataa tiedosto",
    returnToPreview: "Takaisin esikatseluun",
  },
  ro: {
    status: {
      accepted: { title: "Solicitare acceptată", text: "Conversia temporară a fost creată.", tone: "progress", pending: true },
      queued: { title: "În așteptare", text: "Se așteaptă un proces de browser izolat.", tone: "progress", pending: true },
      loading: { title: "Se încarcă pagina publică", text: "Ținta este revalidată în timp ce resursele se încarcă în limite fixe.", tone: "progress", pending: true },
      analyzing: { title: "Se analizează secțiunile", text: "Sunt cartografiate aspectul, linkurile sigure și elementele editabile.", tone: "progress", pending: true },
      preview_rendering: { title: "Se creează previzualizarea", text: "Se creează miniaturi temporare ale paginilor sau diapozitivelor.", tone: "progress", pending: true },
      preview_ready: { title: "Previzualizarea este gata", text: "Verificați secțiunile și înlocuirile vizibile înainte de randarea finală.", tone: "success", pending: false },
      final_queued: { title: "Randarea finală este în așteptare", text: "Versiunea aprobată a previzualizării așteaptă un proces.", tone: "progress", pending: true },
      final_rendering: { title: "Se creează fișierul final", text: "Documentul final folosește aceeași versiune afișată în previzualizare.", tone: "progress", pending: true },
      download_ready: { title: "Fișierul este gata de descărcat", text: "Fișierul temporar criptat este gata de descărcat.", tone: "success", pending: false },
      downloaded: { title: "Descărcare finalizată", text: "A început perioada scurtă înainte de ștergerea fișierului temporar.", tone: "success", pending: false },
      failed_recoverable: { title: "Conversia a fost întreruptă", text: "Acțiunea a eșuat în siguranță. Porniți o nouă previzualizare și încercați din nou.", tone: "error", pending: false },
      failed_terminal: { title: "Conversia a fost oprită", text: "Sursa nu a putut fi procesată în limitele de securitate.", tone: "error", pending: false },
      cancelled: { title: "Conversie anulată", text: "Lucrările în așteptare au fost oprite, iar datele temporare sunt șterse.", tone: "warning", pending: false },
      expired: { title: "Previzualizarea a expirat", text: "Sarcinile temporare nu sunt păstrate ca istoric al conversiilor.", tone: "error", pending: false },
    },
    workspaceEyebrow: "Spațiu de lucru temporar sigur",
    pdfTitle: "Pagini PDF",
    pptxTitle: "Diapozitive PowerPoint",
    sectionsTitle: "Secțiuni",
    previewLabel: "Previzualizarea documentului",
    inspectorTitle: "Detalii",
    globalWarningsTitle: "Avertismente de conversie",
    noWarnings: "Nu există avertismente de conversie pentru această secțiune.",
    noPreviewYet: "Previzualizarea va apărea după finalizarea analizei.",
    up: "Sus",
    down: "Jos",
    restore: "Restaurează",
    remove: "Elimină",
    split: "Divizează",
    merge: "Îmbină",
    renderFinal: "Creează fișierul final",
    openDownload: "Deschide descărcarea",
    cancel: "Anulează conversia",
    retryFromConverter: "Pornește o nouă conversie",
    revision: (value: number): string => `Versiunea ${value}`,
    dimensions: (section: BackendPreviewSection): string => `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: { native: "editabil", mixed: "fidelitate mixtă", visual: "instantaneu de pagină" },
    warnings: {
      RASTER_FALLBACK: "Un element complex a fost transformat într-o imagine raster.",
      FONT_SUBSTITUTED: "Un font web a fost înlocuit cu un font sigur pentru documente.",
      RESOURCE_OMITTED: "O resursă peste limita sigură a fost omisă.",
      STABILIZATION_INCOMPLETE: "Pagina nu s-a stabilizat complet înainte de captură.",
      LINK_REMOVED: "Un link nesigur sau neacceptat a fost eliminat.",
      CRAWL_PAGE_SKIPPED: "O țintă a fost omisă din cauza domeniului sau regulilor robots.",
    },
    downloadEyebrow: "Fișier temporar criptat",
    downloadTitle: "Fișierul este gata",
    downloadPending: "Documentul final este încă în curs de pregătire.",
    downloadFile: "Descarcă fișierul",
    returnToPreview: "Înapoi la previzualizare",
  },
  hu: {
    status: {
      accepted: { title: "Kérés elfogadva", text: "Az ideiglenes konvertálás létrejött.", tone: "progress", pending: true },
      queued: { title: "Sorban áll", text: "Várakozás egy elszigetelt böngészőfolyamatra.", tone: "progress", pending: true },
      loading: { title: "Nyilvános oldal betöltése", text: "A cél újraellenőrzése zajlik, miközben az erőforrások rögzített korlátok között töltődnek.", tone: "progress", pending: true },
      analyzing: { title: "Szakaszok elemzése", text: "Az elrendezés, a biztonságos hivatkozások és a szerkeszthető elemek feltérképezése zajlik.", tone: "progress", pending: true },
      preview_rendering: { title: "Előnézet létrehozása", text: "Ideiglenes oldal- vagy diabélyegképek készülnek.", tone: "progress", pending: true },
      preview_ready: { title: "Az előnézet elkészült", text: "A végleges renderelés előtt ellenőrizze a szakaszokat és a látható helyettesítéseket.", tone: "success", pending: false },
      final_queued: { title: "Végleges renderelés sorban", text: "A jóváhagyott előnézeti verzió egy folyamatra vár.", tone: "progress", pending: true },
      final_rendering: { title: "Végleges fájl létrehozása", text: "A végleges dokumentum ugyanazt a verziót használja, amely az előnézetben látható.", tone: "progress", pending: true },
      download_ready: { title: "A fájl letölthető", text: "Az ideiglenes titkosított fájl készen áll a letöltésre.", tone: "success", pending: false },
      downloaded: { title: "Letöltés kész", text: "Elindult a rövid időszak az ideiglenes fájl törlése előtt.", tone: "success", pending: false },
      failed_recoverable: { title: "A konvertálás megszakadt", text: "A művelet biztonságosan meghiúsult. Indítson új előnézetet, és próbálja újra.", tone: "error", pending: false },
      failed_terminal: { title: "A konvertálás leállt", text: "A forrás nem volt feldolgozható a biztonsági korlátokon belül.", tone: "error", pending: false },
      cancelled: { title: "Konvertálás megszakítva", text: "A sorban álló munka leállt, az ideiglenes adatok törlése folyamatban van.", tone: "warning", pending: false },
      expired: { title: "Az előnézet lejárt", text: "Az ideiglenes feladatok nem kerülnek konvertálási előzményként tárolásra.", tone: "error", pending: false },
    },
    workspaceEyebrow: "Biztonságos ideiglenes munkaterület",
    pdfTitle: "PDF-oldalak",
    pptxTitle: "PowerPoint-diák",
    sectionsTitle: "Szakaszok",
    previewLabel: "Dokumentum-előnézet",
    inspectorTitle: "Részletek",
    globalWarningsTitle: "Konvertálási figyelmeztetések",
    noWarnings: "Ehhez a szakaszhoz nincs konvertálási figyelmeztetés.",
    noPreviewYet: "Az előnézet az elemzés befejezése után jelenik meg.",
    up: "Fel",
    down: "Le",
    restore: "Visszaállítás",
    remove: "Eltávolítás",
    split: "Felosztás",
    merge: "Egyesítés",
    renderFinal: "Végleges fájl létrehozása",
    openDownload: "Letöltés megnyitása",
    cancel: "Konvertálás megszakítása",
    retryFromConverter: "Új konvertálás indítása",
    revision: (value: number): string => `${value}. verzió`,
    dimensions: (section: BackendPreviewSection): string => `${Math.round(section.width)} × ${Math.round(section.height)} px`,
    fidelity: { native: "szerkeszthető", mixed: "vegyes hűség", visual: "oldal-pillanatkép" },
    warnings: {
      RASTER_FALLBACK: "Egy összetett elem raszterképpé alakult.",
      FONT_SUBSTITUTED: "Egy webes betűtípus biztonságos dokumentumbetűtípusra cserélődött.",
      RESOURCE_OMITTED: "A biztonságos korlátot meghaladó erőforrás kimaradt.",
      STABILIZATION_INCOMPLETE: "Az oldal a rögzítés előtt nem stabilizálódott teljesen.",
      LINK_REMOVED: "Egy nem biztonságos vagy nem támogatott hivatkozás eltávolításra került.",
      CRAWL_PAGE_SKIPPED: "Egy cél kimaradt a hatókör vagy a robots-szabályok miatt.",
    },
    downloadEyebrow: "Ideiglenes titkosított fájl",
    downloadTitle: "A fájl elkészült",
    downloadPending: "A végleges dokumentum előkészítése még folyamatban van.",
    downloadFile: "Fájl letöltése",
    returnToPreview: "Vissza az előnézethez",
  },
};

export const getRealPreviewCopy = (locale: Locale): RealPreviewCopy =>
  realPreviewCopy[locale];
