FROM node:24-bookworm-slim AS dependencies

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:24-bookworm-slim AS build

WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_ENABLE_INDEXING=false
ARG NEXT_PUBLIC_LEGAL_REVIEWED=false
ARG NEXT_PUBLIC_ENABLE_CONVERSION=false
ARG NEXT_PUBLIC_CHROME_EXTENSION_URL
ARG NEXT_PUBLIC_PAGE2PDF_GPT_URL
ARG NEXT_PUBLIC_WEB2PDF_GPT_URL
ARG NEXT_PUBLIC_HTML2PDF_GPT_URL
ARG NEXT_PUBLIC_ONE_PAGE2POWERPOINT_GPT_URL
ARG NEXT_PUBLIC_WEB2POWERPOINT_GPT_URL

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID \
    NEXT_PUBLIC_ENABLE_INDEXING=$NEXT_PUBLIC_ENABLE_INDEXING \
    NEXT_PUBLIC_LEGAL_REVIEWED=$NEXT_PUBLIC_LEGAL_REVIEWED \
    NEXT_PUBLIC_ENABLE_CONVERSION=$NEXT_PUBLIC_ENABLE_CONVERSION \
    NEXT_PUBLIC_CHROME_EXTENSION_URL=$NEXT_PUBLIC_CHROME_EXTENSION_URL \
    NEXT_PUBLIC_PAGE2PDF_GPT_URL=$NEXT_PUBLIC_PAGE2PDF_GPT_URL \
    NEXT_PUBLIC_WEB2PDF_GPT_URL=$NEXT_PUBLIC_WEB2PDF_GPT_URL \
    NEXT_PUBLIC_HTML2PDF_GPT_URL=$NEXT_PUBLIC_HTML2PDF_GPT_URL \
    NEXT_PUBLIC_ONE_PAGE2POWERPOINT_GPT_URL=$NEXT_PUBLIC_ONE_PAGE2POWERPOINT_GPT_URL \
    NEXT_PUBLIC_WEB2POWERPOINT_GPT_URL=$NEXT_PUBLIC_WEB2POWERPOINT_GPT_URL

RUN npm run build:next

FROM node:24-bookworm-slim AS runtime

WORKDIR /app
ENV NODE_ENV=production \
    HOSTNAME=0.0.0.0 \
    PORT=3000

RUN groupadd --system --gid 1001 nodejs \
  && useradd --system --uid 1001 --gid nodejs nextjs

COPY --from=build --chown=nextjs:nodejs /app/public ./public
COPY --from=build --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=build --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
