import type { HomeCopy } from "./home-copy";

export const homeCopyHu: HomeCopy = {
  title: "Exportáljon bármilyen weboldalt PDF/PPTX-fájlba",
  lead: "Illessze be egy nyilvános oldal hivatkozását. A Page 2 File pontosan PDF-oldalakra vagy PowerPoint-diákra bontja, letöltés előtti előnézettel.",
  form: {
    formatLabel: "Formátum",
    meta: "Nincs regisztráció · Előnézet · Ideiglenes fájlok",
    pdfModeLabel: "PDF-mód",
    pdfModes: [{ label: "Oldal-pillanatképek", value: "visual" }, { label: "Szerkeszthető PDF", value: "editable" }],
    powerpointModeLabel: "PowerPoint-mód",
    powerpointModes: [{ label: "Diaképek", value: "visual" }, { label: "Szerkeszthető prezentáció", value: "editable" }],
    submitPdf: "PDF létrehozása",
    submitPowerpoint: "PowerPoint létrehozása",
    urlHelper: "Csak nyilvános HTTPS-oldalak. Bejelentkezett lapokhoz használja a bővítményt.",
    urlLabel: "Weboldal hivatkozása",
    urlPlaceholder: "https://example.com/cikk",
  },
  converterFlow: {
    backAction: "Vissza a beállításokhoz",
    processingBody: "Elemezzük az oldalt és előkészítjük a kiválasztott fájlformátumot.",
    processingTitle: "Előkészítjük a fájlt",
    readyBody: "Kattintson a fájl letöltéséhez",
    readyTitle: "A fájl elkészült",
  },
  closingNote: "A szolgáltatás cikkekkel, dokumentációval, céloldalakkal és nyilvános jelentésekkel működik. Privát oldalak vagy AI-csevegések esetén a bővítmény az aktív böngészőlapot használja, és ideiglenes előnézetet hoz létre.",
  preview: {
    accessibleLabel: "Példa a konvertálás eredményére",
    divider: "AZ OLDALTÖRÉS EGYBEN TARTJA A KÉPET",
    imageNote: "A kép teljes marad",
    pdfMeta: "12 oldal · kész",
    powerpointMeta: "12 dia · kész",
    sourceTitle: "Hosszú cikk egy képpel",
    title: "Oldal → pontos fájl",
  },
  promo: {
    body: "A bővítmény kétféleképpen működik: URL-lel vagy az aktív lappal. Az exportált oldal adatai az előnézet bezárása után törlődnek a szerverről.",
    eyebrow: "CHROME-BŐVÍTMÉNY",
    title: "Exportálja az aktuális lapot akkor is, ha bejelentkezés szükséges.",
  },
  features: {
    eyebrow: "FUNKCIÓK",
    title: "Rugalmas lehetőségek az exportált tartalomhoz",
    body: "Exportáljon weboldalakat a megfelelő formátumban: oldal-pillanatképként vagy a média, hivatkozások és szerkezet megőrzésével.",
    items: [
      { title: "AI- és üzenetküldő csevegések exportálása", body: "Exportáljon hosszú beszélgetéseket a ChatGPT, Claude, Gemini, Grok, DeepSeek és más szolgáltatásokból áttekinthető PDF-be." },
      { title: "A 2 legpraktikusabb formátum", list: { items: ["Mentse az oldal-pillanatképeket PDF/PPTX-fájlba.", "Hozzon létre szerkeszthető PDF/PPTX-fájlokat a média, hivatkozások és szerkezet megőrzésével."], style: "unordered" } },
      { title: "A fájl tartalmának szabályozása", body: "Kombinálja a megőrzött médiát, hivatkozásokat és formázást. Az előnézetben a felesleges oldalelemeket is eltávolíthatja." },
      { title: "2 munkamód", body: "Exportálja az aktuális lapot bármely webhelyről, vagy adja meg egy nyilvános oldal URL-jét." },
      { title: "Más szolgáltatások problémái megoldva", body: "Kapjon PDF- vagy PPTX-fájlt teljes képekkel és szükségtelenül nagy üres helyek nélkül." },
      { title: "Biztonságos és regisztráció nélküli", body: "Nincs szükség fiókra. Telepítse a bővítményt, és mentse a kiválasztott oldalt." },
    ],
  },
  howItWorks: {
    action: "Teljes útmutató megnyitása",
    body: "A leggyorsabb módszer a bővítmény: az aktuális lapot használja, így nem kell hivatkozást másolnia.",
    eyebrow: "ÍGY KEZDHETI EL",
    extensionAction: "Bővítmény telepítése",
    installTime: "30 másodperc alatt",
    items: [
      { title: "Telepítse a bővítményt", body: "Adja hozzá a Page 2 File-t a Chrome-hoz. Nincs szükség Page 2 File-fiókra." },
      { title: "Nyissa meg az oldalt", list: { items: ["Lépjen a kívánt lapra.", "Nyissa meg a Page 2 File-t.", "Kattintson a Preview gombra."], style: "ordered" } },
      { title: "Ellenőrizze és töltse le", body: "Ellenőrizze az eredményt, szükség esetén távolítson el szakaszokat, majd töltse le a kész fájlt." },
    ],
    note: "Példák nyilvános hivatkozásra, privát lapra és AI-csevegésre",
    stepLabels: ["1. lépés", "2. lépés", "3. lépés"],
    title: "Három lépés a kész fájlig",
  },
  blog: {
    action: "Cikk olvasása",
    allAction: "Minden cikk",
    body: "Gyakorlati útmutatók a megjelenéshűségről, szerkeszthetőségről, hivatkozásokról, oldaltörésekről és AI-csevegések biztonságos kezeléséről.",
    eyebrow: "BLOG",
    items: [{ slug: "why-print-to-pdf-breaks" }, { slug: "visual-vs-editable" }, { slug: "preserve-clickable-links" }, { slug: "long-webpage-page-breaks" }],
    title: "Útmutatók különböző webhelytípusok exportálásához",
  },
  faq: {
    body: "Egyértelmű válaszok oldalrögzítésről, kimeneti módokról, privát lapokról, ideiglenes előnézetekről és csevegések exportálásáról.",
    eyebrow: "GYAKORI KÉRDÉSEK",
    items: [
      { title: "Hogyan konvertálhatok weboldalt PDF-be vagy PowerPointba?", body: "Nyilvános oldalnál illessze be a HTTPS URL-t, válassza a PDF-et vagy PowerPointot és az oldal-pillanatképeket vagy szerkeszthető módot, majd ellenőrizze a szakaszokat. Bejelentkezett oldalnál használja a Page 2 File bővítményt az aktív lapon." },
      { title: "Megőrizheti a Page 2 File az oldal megjelenését?", body: "Az oldal-pillanatképek a renderelt megjelenés, így az elrendezés, színek, képek és látható diagramok megőrzésére készültek. Az animációk, videók és interaktív vezérlők statikusan jelennek meg." },
      { title: "A szöveg és a hivatkozások szerkeszthetők maradnak?", body: "A szerkeszthető mód megőrzi a támogatott szöveget és a biztonságos hivatkozáscélokat. Az összetett modulok, a böngésző által közvetlenül rajzolt grafika és nem támogatott elemek képként jelenhetnek meg. Az oldal-pillanatképek a megjelenést részesítik előnyben." },
      { title: "A hosszú és dinamikus oldalak teljesen rögzíthetők?", body: "A bővítmény a renderelt aktív lapot használja. Először nyissa ki a tartalmat, és görgessen a végére. A rejtett vagy be nem töltött tartalom nem exportálható." },
      { title: "Konvertálhatok oldalakat bejelentkezés után?", body: "Igen, a Chrome-bővítménnyel, miután az oldalt a szokásos módon megnyitotta. A bővítmény az aktív lapot használja, és nem kéri jelszavát a nyilvános URL űrlapon. Nem kerüli meg a hozzáférés-vezérlést." },
      {
        title: "Egy oldalt vagy teljes webhelyet konvertálhatok?",
        body: [
          { kind: "text", text: "A weboldal-konverterek, valamint a " },
          { kind: "link", label: "Webpage to PDF Converter — Web2File", route: "page2pdf-gpt" },
          { kind: "text", text: " és a " },
          { kind: "link", label: "One Page 2 PowerPoint", route: "one-page2powerpoint-gpt" },
          { kind: "text", text: " egy URL-t dolgoznak fel. Több elérhető nyilvános oldalhoz használja a " },
          { kind: "link", label: "Web 2 PDF", route: "web2pdf-gpt" },
          { kind: "text", text: " vagy a " },
          { kind: "link", label: "Web 2 PowerPoint", route: "web2powerpoint-gpt" },
          { kind: "text", text: " alkalmazást: minden kiválasztott oldalhoz külön PDF- vagy PPTX-fájlt kap, nem egyetlen egyesített fájlt." },
        ],
      },
      { title: "Mi a különbség az oldal-pillanatképek és a szerkeszthető módok között?", body: "Az oldal-pillanatképek a renderelt oldalhoz való hűséget részesítik előnyben. A szerkeszthető mód a kijelölhető szöveget, támogatott képeket, biztonságos hivatkozásokat és újrafelhasználható szerkezetet. Ellenőrizze az összetett grafikát és elrendezést." },
      { title: "Mi történik az előnézeti adatokkal a lap bezárása után?", body: "Az adatok ideiglenesek, és a lap bezárásakor törlődnek. A Page 2 File nem rendelkezik felhasználói konvertálási előzményeket tároló adatbázissal vagy korábbi előnézetek archívumával." },
      { title: "Szükségem van fiókra?", body: "Nyilvános URL-ekhez vagy a bővítmény előnézetéhez nincs szükség Page 2 File-fiókra. Privát oldal rögzítéséhez be kell jelentkeznie a forráswebhelyre." },
      { title: "Exportálhatok AI- és üzenetküldő csevegéseket?", body: "A bővítmény a Chrome-lapon renderelt beszélgetést exportálja, beleértve a támogatott AI-csevegéseket és webes üzenetküldőket. Először töltse be a kívánt üzenettartományt. A böngészőn kívüli alkalmazások, például a Signal Desktop, nem rögzíthetők." },
    ],
    title: "Hasznos tudnivalók",
  },
  finalCta: {
    body: "Illesszen be ide egy nyilvános hivatkozást, vagy telepítse a bővítményt az aktuális laphoz.",
    eyebrow: "KIPRÓBÁLNÁ A SAJÁT OLDALÁVAL?",
    title: "Szerezzen PDF-et vagy PowerPointot a szerkesztő megnyitása előtt",
  },
};
