import type { HomeCopy } from "./home-copy";

export const homeCopyRo: HomeCopy = {
  title: "Exportați orice pagină web în PDF/PPTX",
  lead: "Lipiți linkul către o pagină publică. Page 2 File o împarte exact în pagini PDF sau diapozitive PowerPoint, cu previzualizare înainte de descărcare.",
  form: {
    formatLabel: "Format",
    meta: "Fără înregistrare · Previzualizare · Fișiere temporare",
    pdfModeLabel: "Mod PDF",
    pdfModes: [{ label: "Instantanee ale paginii", value: "visual" }, { label: "PDF editabil", value: "editable" }],
    powerpointModeLabel: "Mod PowerPoint",
    powerpointModes: [{ label: "Imagini ale diapozitivelor", value: "visual" }, { label: "Prezentare editabilă", value: "editable" }],
    submitPdf: "Creează PDF",
    submitPowerpoint: "Creează PowerPoint",
    urlHelper: "Numai pagini HTTPS publice. Folosiți extensia pentru filele autentificate.",
    urlLabel: "Link către pagina web",
    urlPlaceholder: "https://example.com/articol",
  },
  converterFlow: {
    backAction: "Înapoi la configurare",
    processingBody: "Analizăm pagina și pregătim formatul de fișier selectat.",
    processingTitle: "Vă pregătim fișierul",
    readyBody: "Faceți clic pentru a descărca fișierul",
    readyTitle: "Fișierul este gata",
  },
  closingNote: "Serviciul funcționează cu articole, documentație, pagini de destinație și rapoarte publice. Pentru pagini private sau conversații AI, extensia folosește fila activă a browserului și creează o previzualizare temporară.",
  preview: {
    accessibleLabel: "Exemplu de rezultat al conversiei",
    divider: "ÎNTRERUPEREA DE PAGINĂ PĂSTREAZĂ IMAGINEA ÎNTREAGĂ",
    imageNote: "Imaginea rămâne întreagă",
    pdfMeta: "12 pagini · gata",
    powerpointMeta: "12 diapozitive · gata",
    sourceTitle: "Un articol lung cu o imagine",
    title: "Pagină → fișier precis",
  },
  promo: {
    body: "Extensia funcționează în două moduri: prin URL sau cu fila activă. Datele paginii exportate sunt șterse de pe server după închiderea previzualizării.",
    eyebrow: "EXTENSIE CHROME",
    title: "Exportați fila curentă, inclusiv atunci când este necesară autentificarea.",
  },
  features: {
    eyebrow: "FUNCȚIONALITĂȚI",
    title: "Opțiuni flexibile pentru conținutul exportat",
    body: "Exportați paginile web în formatul potrivit: ca instantanee ale paginii sau cu elemente media, linkuri și structură păstrate.",
    items: [
      { title: "Exportați conversații AI și de mesagerie", body: "Exportați conversații lungi din ChatGPT, Claude, Gemini, Grok, DeepSeek și alte servicii într-un PDF clar." },
      { title: "Cele mai practice 2 formate", list: { items: ["Salvați instantaneele paginii în PDF/PPTX.", "Creați fișiere PDF/PPTX editabile care păstrează elementele media, linkurile și structura."], style: "unordered" } },
      { title: "Controlați conținutul fișierului", body: "Combinați elementele media, linkurile și formatarea păstrate. De asemenea, puteți elimina elemente inutile ale paginii în previzualizare." },
      { title: "2 moduri de lucru", body: "Exportați fila curentă de pe orice site sau introduceți URL-ul unei pagini publice." },
      { title: "Probleme din alte servicii rezolvate", body: "Obțineți un PDF sau PPTX cu imagini întregi și fără spații inutil de mari în conținut." },
      { title: "Sigur și fără înregistrare", body: "Nu aveți nevoie de cont. Instalați extensia și salvați pagina selectată." },
    ],
  },
  howItWorks: {
    action: "Deschide ghidul complet",
    body: "Cea mai rapidă metodă este extensia: folosește fila curentă, fără să fie nevoie să copiați un link.",
    eyebrow: "CUM ÎNCEPEȚI",
    extensionAction: "Instalați extensia",
    installTime: "În 30 de secunde",
    items: [
      { title: "Instalați extensia", body: "Adăugați Page 2 File în Chrome. Nu aveți nevoie de un cont Page 2 File." },
      { title: "Deschideți pagina", list: { items: ["Accesați fila dorită.", "Deschideți Page 2 File.", "Faceți clic pe Preview."], style: "ordered" } },
      { title: "Verificați și descărcați", body: "Verificați rezultatul, eliminați secțiuni dacă este necesar și descărcați fișierul final." },
    ],
    note: "Cu exemple pentru un link public, o filă privată și o conversație AI",
    stepLabels: ["Pasul 1", "Pasul 2", "Pasul 3"],
    title: "Trei pași până la fișierul final",
  },
  blog: {
    action: "Citiți articolul",
    allAction: "Toate articolele",
    body: "Ghiduri practice despre fidelitate, editare, linkuri, întreruperi de pagină și gestionarea sigură a conversațiilor AI.",
    eyebrow: "BLOG",
    items: [{ slug: "why-print-to-pdf-breaks" }, { slug: "visual-vs-editable" }, { slug: "preserve-clickable-links" }, { slug: "long-webpage-page-breaks" }],
    title: "Ghiduri pentru exportarea diferitelor tipuri de site-uri",
  },
  faq: {
    body: "Răspunsuri clare despre capturarea paginilor, modurile de ieșire, filele private, previzualizările temporare și exportul conversațiilor.",
    eyebrow: "ÎNTREBĂRI FRECVENTE",
    items: [
      { title: "Cum convertesc o pagină web în PDF sau PowerPoint?", body: "Pentru o pagină publică, lipiți URL-ul HTTPS, alegeți PDF sau PowerPoint și instantanee ale paginii sau modul editabil, apoi verificați secțiunile. Pentru o pagină autentificată, folosiți extensia Page 2 File în fila activă." },
      { title: "Poate Page 2 File păstra designul paginii?", body: "Instantaneele paginii sunt concepute pentru a păstra aspectul randat, inclusiv dispunerea, culorile, imaginile și graficele vizibile. Animațiile, videoclipurile și controalele interactive sunt randate static." },
      { title: "Textul și linkurile rămân editabile?", body: "Modul editabil păstrează textul acceptat și destinațiile sigure ale linkurilor. Modulele complexe, canvas și elementele neacceptate pot fi randate ca imagini. Instantaneele paginii prioritizează aspectul." },
      { title: "Pot fi capturate integral paginile lungi și dinamice?", body: "Extensia folosește fila activă randată. Extindeți mai întâi conținutul și derulați până la sfârșit. Conținutul ascuns sau neîncărcat nu poate fi exportat." },
      { title: "Pot converti pagini după autentificare?", body: "Da, cu extensia Chrome după ce pagina a fost deschisă în mod normal. Extensia folosește fila activă și nu vă cere parola în formularul pentru URL-uri publice. Nu ocolește controalele de acces." },
      {
        title: "Pot converti o singură pagină sau un site întreg?",
        body: [
          { kind: "text", text: "Convertoarele de pagini web și " },
          { kind: "link", label: "One Page 2 PDF", route: "page2pdf-gpt" },
          { kind: "text", text: " și " },
          { kind: "link", label: "One Page 2 PowerPoint", route: "one-page2powerpoint-gpt" },
          { kind: "text", text: " procesează un singur URL. Pentru mai multe pagini publice accesibile, folosiți " },
          { kind: "link", label: "Web 2 PDF", route: "web2pdf-gpt" },
          { kind: "text", text: " sau " },
          { kind: "link", label: "Web 2 PowerPoint", route: "web2powerpoint-gpt" },
          { kind: "text", text: ": primiți un PDF sau PPTX separat pentru fiecare pagină selectată, nu un singur fișier combinat." },
        ],
      },
      { title: "Care este diferența dintre instantaneele paginii și modurile editabile?", body: "Instantaneele paginii prioritizează fidelitatea față de pagina randată. Modul editabil prioritizează textul selectabil, imaginile acceptate, linkurile sigure și structura reutilizabilă. Verificați grafica și aspectele complexe." },
      { title: "Ce se întâmplă cu datele de previzualizare după închiderea filei?", body: "Datele sunt temporare și sunt șterse când fila se închide. Page 2 File nu are o bază de date cu istoricul conversiilor și nici o arhivă a previzualizărilor anterioare." },
      { title: "Am nevoie de cont?", body: "Nu aveți nevoie de un cont Page 2 File pentru URL-uri publice sau pentru previzualizarea extensiei. Pentru o pagină privată poate fi necesar să vă autentificați pe site-ul sursă." },
      { title: "Pot exporta conversații AI și de mesagerie?", body: "Extensia exportă o conversație randată într-o filă Chrome, inclusiv conversații AI și mesagerie web acceptate. Încărcați mai întâi intervalul dorit de mesaje. Aplicațiile din afara browserului, precum Signal Desktop, nu sunt capturate." },
    ],
    title: "Bine de știut",
  },
  finalCta: {
    body: "Lipiți aici un link public sau instalați extensia pentru fila curentă.",
    eyebrow: "DORIȚI SĂ ÎNCERCAȚI CU PAGINA DVS.?",
    title: "Obțineți un PDF sau PowerPoint înainte de a deschide un editor",
  },
};
