import type { HomeCopy } from "./home-copy";

export const homeCopyDa: HomeCopy = {
  title: "Eksportér enhver webside til PDF/PPTX",
  lead: "Indsæt linket til en offentlig side. Page 2 File opdeler den præcist i PDF-sider eller PowerPoint-dias med forhåndsvisning før download.",
  form: {
    formatLabel: "Format",
    meta: "Ingen registrering · Forhåndsvisning · Midlertidige filer",
    pdfModeLabel: "PDF-tilstand",
    pdfModes: [{ label: "Sidebilleder", value: "visual" }, { label: "Redigerbar PDF", value: "editable" }],
    powerpointModeLabel: "PowerPoint-tilstand",
    powerpointModes: [{ label: "Diasbilleder", value: "visual" }, { label: "Redigerbar præsentation", value: "editable" }],
    submitPdf: "Opret PDF",
    submitPowerpoint: "Opret PowerPoint",
    urlHelper: "Kun offentlige HTTPS-sider. Brug udvidelsen til faner med login.",
    urlLabel: "Link til websiden",
    urlPlaceholder: "https://example.com/artikel",
  },
  converterFlow: {
    backAction: "Tilbage til opsætningen",
    processingBody: "Vi analyserer siden og forbereder det valgte filformat.",
    processingTitle: "Vi forbereder din fil",
    readyBody: "Klik for at downloade filen",
    readyTitle: "Din fil er klar",
  },
  closingNote: "Tjenesten fungerer med artikler, dokumentation, landingssider og offentlige rapporter. Til private sider eller AI-chats bruger udvidelsen den aktive browserfane og opretter en midlertidig forhåndsvisning.",
  preview: {
    accessibleLabel: "Eksempel på konverteringsresultat",
    divider: "SIDESKIFTET HOLDER BILLEDET SAMLET",
    imageNote: "Billedet forbliver helt",
    pdfMeta: "12 sider · klar",
    powerpointMeta: "12 dias · klar",
    sourceTitle: "En lang artikel med et billede",
    title: "Side → nøjagtig fil",
  },
  promo: {
    body: "Udvidelsen fungerer på to måder: via URL eller med den aktive fane. Data fra den eksporterede side slettes fra serveren, når forhåndsvisningen lukkes.",
    eyebrow: "CHROME-UDVIDELSE",
    title: "Eksportér den aktuelle fane, også når login er påkrævet.",
  },
  features: {
    eyebrow: "FUNKTIONER",
    title: "Fleksible muligheder for eksporteret indhold",
    body: "Eksportér websider i det rette format: som sidebilleder eller med bevarede medier, links og struktur.",
    items: [
      { title: "Eksportér AI- og beskedchats", body: "Eksportér lange samtaler fra ChatGPT, Claude, Gemini, Grok, DeepSeek og andre tjenester til en overskuelig PDF." },
      { title: "De 2 mest praktiske formater", list: { items: ["Gem sidebilleder som PDF/PPTX.", "Opret redigerbare PDF/PPTX-filer, der bevarer medier, links og struktur."], style: "unordered" } },
      { title: "Kontrollér filens indhold", body: "Kombinér bevarede medier, links og formatering. I forhåndsvisningen kan du også fjerne unødvendige sideelementer." },
      { title: "2 arbejdsmåder", body: "Eksportér den aktuelle fane fra et hvilket som helst websted, eller indtast URL'en til en offentlig side." },
      { title: "Problemer i andre tjenester løst", body: "Få en PDF eller PPTX med hele billeder og uden unødvendigt store mellemrum i indholdet." },
      { title: "Sikkert og uden registrering", body: "Du behøver ingen konto. Installer udvidelsen, og gem den valgte side." },
    ],
  },
  howItWorks: {
    action: "Åbn hele vejledningen",
    body: "Den hurtigste metode er udvidelsen: den bruger den aktuelle fane, så du ikke behøver at kopiere et link.",
    eyebrow: "SÅDAN KOMMER DU I GANG",
    extensionAction: "Installer udvidelsen",
    installTime: "På 30 sekunder",
    items: [
      { title: "Installer udvidelsen", body: "Føj Page 2 File til Chrome. Du behøver ikke en Page 2 File-konto." },
      { title: "Åbn siden", list: { items: ["Gå til den ønskede fane.", "Åbn Page 2 File.", "Klik på Preview."], style: "ordered" } },
      { title: "Kontrollér og download", body: "Kontrollér resultatet, fjern om nødvendigt afsnit, og download den færdige fil." },
    ],
    note: "Med eksempler på et offentligt link, en privat fane og en AI-chat",
    stepLabels: ["Trin 1", "Trin 2", "Trin 3"],
    title: "Tre trin til en færdig fil",
  },
  blog: {
    action: "Læs artiklen",
    allAction: "Alle artikler",
    body: "Praktiske vejledninger om gengivelse, redigering, links, sideskift og sikker håndtering af AI-chats.",
    eyebrow: "BLOG",
    items: [{ slug: "why-print-to-pdf-breaks" }, { slug: "visual-vs-editable" }, { slug: "preserve-clickable-links" }, { slug: "long-webpage-page-breaks" }],
    title: "Vejledninger til eksport af forskellige typer websteder",
  },
  faq: {
    body: "Tydelige svar om sideoptagelse, outputtilstande, private faner, midlertidige forhåndsvisninger og chateksport.",
    eyebrow: "OFTE STILLEDE SPØRGSMÅL",
    items: [
      { title: "Hvordan konverterer jeg en webside til PDF eller PowerPoint?", body: "Indsæt HTTPS-URL'en til en offentlig side, vælg PDF eller PowerPoint og sidebilleder eller redigerbar tilstand, og kontrollér afsnittene. Brug Page 2 File-udvidelsen i den aktive fane til en side med login." },
      { title: "Kan Page 2 File bevare sidens design?", body: "Sidebilleder er beregnet til at bevare det gengivne udseende, herunder layout, farver, billeder og synlige diagrammer. Animationer, video og interaktive kontroller gengives statisk." },
      { title: "Forbliver tekst og links redigerbare?", body: "Redigerbar tilstand bevarer understøttet tekst og sikre linkmål. Komplekse moduler, grafik som browseren tegner direkte og elementer, der ikke understøttes, kan gengives som billeder. Sidebilleder prioriterer udseendet." },
      { title: "Kan lange og dynamiske sider optages helt?", body: "Udvidelsen bruger den gengivne aktive fane. Udvid først indholdet, og rul til slutningen. Skjult eller ikke-indlæst indhold kan ikke eksporteres." },
      { title: "Kan jeg konvertere sider efter login?", body: "Ja, med Chrome-udvidelsen, efter at siden er åbnet på normal vis. Udvidelsen bruger den aktive fane og beder ikke om din adgangskode i formularen til offentlige URL'er. Den omgår ikke adgangskontrol." },
      {
        title: "Kan jeg konvertere én side eller et helt websted?",
        body: [
          { kind: "text", text: "Websidekonverterne og " },
          { kind: "link", label: "Webpage to PDF Converter — Web2File", route: "page2pdf-gpt" },
          { kind: "text", text: " og " },
          { kind: "link", label: "One Page 2 PowerPoint", route: "one-page2powerpoint-gpt" },
          { kind: "text", text: " behandler én URL. Brug " },
          { kind: "link", label: "Web 2 PDF", route: "web2pdf-gpt" },
          { kind: "text", text: " eller " },
          { kind: "link", label: "Web 2 PowerPoint", route: "web2powerpoint-gpt" },
          { kind: "text", text: " til flere tilgængelige offentlige sider: du får en separat PDF eller PPTX for hver valgt side, ikke én samlet fil." },
        ],
      },
      { title: "Hvad er forskellen på sidebilleder og redigerbare tilstande?", body: "Sidebilleder prioriterer nøjagtighed i forhold til den gengivne side. Redigerbar tilstand prioriterer markerbar tekst, understøttede billeder, sikre links og genanvendelig struktur. Kontrollér kompleks grafik og layout." },
      { title: "Hvad sker der med forhåndsvisningsdata, når fanen lukkes?", body: "Dataene er midlertidige og slettes, når fanen lukkes. Page 2 File har ingen database med konverteringshistorik og intet arkiv over tidligere forhåndsvisninger." },
      { title: "Skal jeg have en konto?", body: "Du behøver ingen Page 2 File-konto til offentlige URL'er eller forhåndsvisning i udvidelsen. For en privat side kan det være nødvendigt at være logget ind på kildewebstedet." },
      { title: "Kan jeg eksportere AI- og beskedchats?", body: "Udvidelsen eksporterer en samtale, der er gengivet i en Chrome-fane, herunder understøttede AI-chats og webbeskeder. Indlæs først det ønskede beskedområde. Apps uden for browseren, f.eks. Signal Desktop, optages ikke." },
    ],
    title: "Godt at vide",
  },
  finalCta: {
    body: "Indsæt et offentligt link her, eller installer udvidelsen til den aktuelle fane.",
    eyebrow: "VIL DU PRØVE MED DIN SIDE?",
    title: "Få en PDF eller PowerPoint, før du åbner et redigeringsprogram",
  },
};
