import type { HomeCopy } from "./home-copy";

export const homeCopySv: HomeCopy = {
  title: "Exportera valfri webbsida till PDF/PPTX",
  lead: "Klistra in länken till en offentlig sida. Page 2 File delar noggrant upp den i PDF-sidor eller PowerPoint-bilder, med förhandsgranskning före hämtning.",
  form: {
    formatLabel: "Format",
    meta: "Ingen registrering · Förhandsgranskning · Tillfälliga filer",
    pdfModeLabel: "PDF-läge",
    pdfModes: [{ label: "Sidbilder", value: "visual" }, { label: "Redigerbar PDF", value: "editable" }],
    powerpointModeLabel: "PowerPoint-läge",
    powerpointModes: [{ label: "Bilder av presentationen", value: "visual" }, { label: "Redigerbar presentation", value: "editable" }],
    submitPdf: "Skapa PDF",
    submitPowerpoint: "Skapa PowerPoint",
    urlHelper: "Endast offentliga HTTPS-sidor. Använd tillägget för inloggade flikar.",
    urlLabel: "Länk till webbsidan",
    urlPlaceholder: "https://example.com/artikel",
  },
  converterFlow: {
    backAction: "Tillbaka till inställningarna",
    processingBody: "Vi analyserar sidan och förbereder det valda filformatet.",
    processingTitle: "Vi förbereder din fil",
    readyBody: "Klicka för att hämta filen",
    readyTitle: "Din fil är klar",
  },
  closingNote: "Tjänsten fungerar med artiklar, dokumentation, landningssidor och offentliga rapporter. För privata sidor eller AI-chattar använder tillägget den aktiva webbläsarfliken och skapar en tillfällig förhandsgranskning.",
  preview: {
    accessibleLabel: "Exempel på konverteringsresultat",
    divider: "SIDBRYTNINGEN HÅLLER BILDEN SAMMAN",
    imageNote: "Bilden förblir hel",
    pdfMeta: "12 sidor · klar",
    powerpointMeta: "12 bilder · klar",
    sourceTitle: "En lång artikel med en bild",
    title: "Sida → korrekt fil",
  },
  promo: {
    body: "Tillägget fungerar på två sätt: via URL eller med den aktiva fliken. Data från den exporterade sidan raderas från servern när förhandsgranskningen stängs.",
    eyebrow: "CHROME-TILLÄGG",
    title: "Exportera den aktuella fliken, även när inloggning krävs.",
  },
  features: {
    eyebrow: "FUNKTIONER",
    title: "Flexibla alternativ för exporterat innehåll",
    body: "Exportera webbsidor i rätt format: som sidbilder eller med bevarade medier, länkar och struktur.",
    items: [
      { title: "Exportera AI- och meddelandechattar", body: "Exportera långa konversationer från ChatGPT, Claude, Gemini, Grok, DeepSeek och andra tjänster till en tydlig PDF." },
      { title: "De 2 mest praktiska formaten", list: { items: ["Spara sidbilder som PDF/PPTX.", "Skapa redigerbara PDF/PPTX-filer som bevarar medier, länkar och struktur."], style: "unordered" } },
      { title: "Styr filens innehåll", body: "Kombinera bevarade medier, länkar och format. I förhandsgranskningen kan du även ta bort onödiga sidelement." },
      { title: "2 arbetssätt", body: "Exportera den aktuella fliken från valfri webbplats eller ange URL:en till en offentlig sida." },
      { title: "Problem hos andra tjänster lösta", body: "Få en PDF eller PPTX med hela bilder och utan onödigt stora mellanrum i innehållet." },
      { title: "Säkert och utan registrering", body: "Du behöver inget konto. Installera tillägget och spara den valda sidan." },
    ],
  },
  howItWorks: {
    action: "Öppna hela guiden",
    body: "Det snabbaste sättet är tillägget: det arbetar med den aktuella fliken och kräver inte att du kopierar en länk.",
    eyebrow: "SÅ KOMMER DU IGÅNG",
    extensionAction: "Installera tillägget",
    installTime: "På 30 sekunder",
    items: [
      { title: "Installera tillägget", body: "Lägg till Page 2 File i Chrome. Du behöver inget Page 2 File-konto." },
      { title: "Öppna sidan", list: { items: ["Gå till önskad flik.", "Öppna Page 2 File.", "Klicka på Preview."], style: "ordered" } },
      { title: "Granska och hämta", body: "Granska resultatet, ta bort avsnitt vid behov och hämta den färdiga filen." },
    ],
    note: "Med exempel på en offentlig länk, en privat flik och en AI-chatt",
    stepLabels: ["Steg 1", "Steg 2", "Steg 3"],
    title: "Tre steg till en färdig fil",
  },
  blog: {
    action: "Läs artikeln",
    allAction: "Alla artiklar",
    body: "Praktiska guider om trohet, redigering, länkar, sidbrytningar och säker hantering av AI-chattar.",
    eyebrow: "BLOGG",
    items: [{ slug: "why-print-to-pdf-breaks" }, { slug: "visual-vs-editable" }, { slug: "preserve-clickable-links" }, { slug: "long-webpage-page-breaks" }],
    title: "Guider för export av olika typer av webbplatser",
  },
  faq: {
    body: "Tydliga svar om sidfångst, utdatalägen, privata flikar, tillfälliga förhandsgranskningar och chattexport.",
    eyebrow: "VANLIGA FRÅGOR",
    items: [
      { title: "Hur konverterar jag en webbsida till PDF eller PowerPoint?", body: "För en offentlig sida klistrar du in dess HTTPS-URL, väljer PDF eller PowerPoint och sidbilder eller redigerbart läge och granskar avsnitten. För en inloggad sida använder du Page 2 File-tillägget i den aktiva fliken." },
      { title: "Kan Page 2 File bevara sidans utformning?", body: "Sidbilder är avsedda att bevara det renderade utseendet, inklusive layout, färger, bilder och synliga diagram. Animationer, video och interaktiva kontroller återges statiskt." },
      { title: "Förblir text och länkar redigerbara?", body: "Redigerbart läge bevarar text som stöds och säkra länkmål. Komplexa widgetar, grafik som webbläsaren ritar direkt och element som inte stöds kan återges som bilder. Sidbilder prioriterar utseendet." },
      { title: "Kan långa och dynamiska sidor fångas helt?", body: "Tillägget arbetar med den renderade aktiva fliken. Fäll först ut innehåll och rulla till slutet. Dolt eller inte inläst innehåll kan inte exporteras." },
      { title: "Kan jag konvertera sidor efter inloggning?", body: "Ja, med Chrome-tillägget efter att sidan öppnats normalt. Tillägget använder den aktiva fliken och begär inte ditt lösenord i formuläret för offentliga URL:er. Det kringgår inte åtkomstkontroller." },
      {
        title: "Kan jag konvertera en sida eller en hel webbplats?",
        body: [
          { kind: "text", text: "Webbsideskonverterarna samt " },
          { kind: "link", label: "Webpage to PDF Converter — Web2File", route: "page2pdf-gpt" },
          { kind: "text", text: " och " },
          { kind: "link", label: "One Page 2 PowerPoint", route: "one-page2powerpoint-gpt" },
          { kind: "text", text: " bearbetar en URL. För flera tillgängliga offentliga sidor använder du " },
          { kind: "link", label: "Web 2 PDF", route: "web2pdf-gpt" },
          { kind: "text", text: " eller " },
          { kind: "link", label: "Web 2 PowerPoint", route: "web2powerpoint-gpt" },
          { kind: "text", text: ": du får en separat PDF eller PPTX för varje vald sida, inte en sammanslagen fil." },
        ],
      },
      { title: "Vad skiljer sidbilder från redigerbara lägen?", body: "Sidbilder prioriterar trohet mot den renderade sidan. Redigerbart läge prioriterar markerbar text, bilder som stöds, säkra länkar och återanvändbara strukturer. Granska komplex grafik och layout." },
      { title: "Vad händer med förhandsgranskningsdata när fliken stängs?", body: "Data är tillfälliga och raderas när fliken stängs. Page 2 File har ingen databas med konverteringshistorik och inget arkiv över tidigare förhandsgranskningar." },
      { title: "Behöver jag ett konto?", body: "Du behöver inget Page 2 File-konto för offentliga URL:er eller tilläggets förhandsgranskning. För en privat sida kan du behöva vara inloggad på källwebbplatsen." },
      { title: "Kan jag exportera AI- och meddelandechattar?", body: "Tillägget exporterar en konversation som renderats i en Chrome-flik, inklusive AI-chattar och webbmeddelanden som stöds. Läs först in rätt meddelandeintervall. Appar utanför webbläsaren, som Signal Desktop, fångas inte." },
    ],
    title: "Bra att veta",
  },
  finalCta: {
    body: "Klistra in en offentlig länk här eller installera tillägget för den aktuella fliken.",
    eyebrow: "VILL DU PROVA MED DIN SIDA?",
    title: "Få en PDF eller PowerPoint innan du öppnar en redigerare",
  },
};
