import type { HomeCopy } from "./home-copy";

export const homeCopyFi: HomeCopy = {
  title: "Vie mikä tahansa verkkosivu PDF/PPTX-tiedostoksi",
  lead: "Liitä julkisen sivun linkki. Page 2 File jakaa sen tarkasti PDF-sivuiksi tai PowerPoint-dioiksi ja näyttää esikatselun ennen lataamista.",
  form: {
    formatLabel: "Muoto",
    meta: "Ei rekisteröitymistä · Esikatselu · Väliaikaiset tiedostot",
    pdfModeLabel: "PDF-tila",
    pdfModes: [{ label: "Sivukaappaukset", value: "visual" }, { label: "Muokattava PDF", value: "editable" }],
    powerpointModeLabel: "PowerPoint-tila",
    powerpointModes: [{ label: "Diakuvat", value: "visual" }, { label: "Muokattava esitys", value: "editable" }],
    submitPdf: "Luo PDF",
    submitPowerpoint: "Luo PowerPoint",
    urlHelper: "Vain julkiset HTTPS-sivut. Käytä laajennusta kirjautuneisiin välilehtiin.",
    urlLabel: "Verkkosivun linkki",
    urlPlaceholder: "https://example.com/artikkeli",
  },
  converterFlow: {
    backAction: "Takaisin asetuksiin",
    processingBody: "Analysoimme sivua ja valmistelemme valittua tiedostomuotoa.",
    processingTitle: "Valmistelemme tiedostoasi",
    readyBody: "Lataa tiedosto napsauttamalla",
    readyTitle: "Tiedostosi on valmis",
  },
  closingNote: "Palvelu toimii artikkeleiden, dokumentaation, laskeutumissivujen ja julkisten raporttien kanssa. Yksityisillä sivuilla ja AI-keskusteluissa laajennus käyttää aktiivista selainvälilehteä ja luo väliaikaisen esikatselun.",
  preview: {
    accessibleLabel: "Esimerkki muunnoksen tuloksesta",
    divider: "SIVUNVAIHTO PITÄÄ KUVAN YHDESSÄ",
    imageNote: "Kuva säilyy kokonaisena",
    pdfMeta: "12 sivua · valmis",
    powerpointMeta: "12 diaa · valmis",
    sourceTitle: "Pitkä artikkeli, jossa on kuva",
    title: "Sivu → tarkka tiedosto",
  },
  promo: {
    body: "Laajennus toimii kahdella tavalla: URL-osoitteella tai aktiivisella välilehdellä. Viedyn sivun tiedot poistetaan palvelimelta, kun esikatselu suljetaan.",
    eyebrow: "CHROME-LAAJENNUS",
    title: "Vie nykyinen välilehti myös silloin, kun kirjautuminen vaaditaan.",
  },
  features: {
    eyebrow: "OMINAISUUDET",
    title: "Joustavat vaihtoehdot vietävälle sisällölle",
    body: "Vie verkkosivut sopivassa muodossa: sivukaappauksina tai media, linkit ja rakenne säilyttäen.",
    items: [
      { title: "Vie AI- ja viestikeskustelut", body: "Vie pitkät keskustelut ChatGPT:stä, Claudesta, Geministä, Grokista, DeepSeekistä ja muista palveluista selkeäksi PDF-tiedostoksi." },
      { title: "2 käytännöllisintä muotoa", list: { items: ["Tallenna sivukaappaukset PDF/PPTX-tiedostoksi.", "Luo muokattavia PDF/PPTX-tiedostoja, joissa media, linkit ja rakenne säilyvät."], style: "unordered" } },
      { title: "Hallitse tiedoston sisältöä", body: "Yhdistä säilytetty media, linkit ja muotoilu. Voit myös poistaa tarpeettomia sivuelementtejä esikatselussa." },
      { title: "2 käyttötapaa", body: "Vie nykyinen välilehti miltä tahansa sivustolta tai anna julkisen sivun URL." },
      { title: "Muiden palvelujen ongelmat ratkaistu", body: "Saat PDF- tai PPTX-tiedoston, jossa kuvat ovat kokonaisia eikä sisällössä ole tarpeettoman suuria tyhjiä välejä." },
      { title: "Turvallinen ilman rekisteröitymistä", body: "Et tarvitse tiliä. Asenna laajennus ja tallenna valitsemasi sivu." },
    ],
  },
  howItWorks: {
    action: "Avaa koko opas",
    body: "Nopein tapa on laajennus: se käyttää nykyistä välilehteä, joten linkkiä ei tarvitse kopioida.",
    eyebrow: "NÄIN PÄÄSET ALKUUN",
    extensionAction: "Asenna laajennus",
    installTime: "30 sekunnissa",
    items: [
      { title: "Asenna laajennus", body: "Lisää Page 2 File Chromeen. Et tarvitse Page 2 File -tiliä." },
      { title: "Avaa sivu", list: { items: ["Siirry haluamallesi välilehdelle.", "Avaa Page 2 File.", "Napsauta Preview."], style: "ordered" } },
      { title: "Tarkista ja lataa", body: "Tarkista tulos, poista tarvittaessa osioita ja lataa valmis tiedosto." },
    ],
    note: "Esimerkit julkisesta linkistä, yksityisestä välilehdestä ja AI-keskustelusta",
    stepLabels: ["Vaihe 1", "Vaihe 2", "Vaihe 3"],
    title: "Kolme vaihetta valmiiseen tiedostoon",
  },
  blog: {
    action: "Lue artikkeli",
    allAction: "Kaikki artikkelit",
    body: "Käytännön oppaita tarkkuudesta, muokattavuudesta, linkeistä, sivunvaihdoista ja AI-keskustelujen turvallisesta käsittelystä.",
    eyebrow: "BLOGI",
    items: [{ slug: "why-print-to-pdf-breaks" }, { slug: "visual-vs-editable" }, { slug: "preserve-clickable-links" }, { slug: "long-webpage-page-breaks" }],
    title: "Oppaat erilaisten verkkosivustojen vientiin",
  },
  faq: {
    body: "Selkeät vastaukset sivun kaappaamisesta, tulostiloista, yksityisistä välilehdistä, väliaikaisista esikatseluista ja keskustelujen viennistä.",
    eyebrow: "USEIN KYSYTYT KYSYMYKSET",
    items: [
      { title: "Miten muunnan verkkosivun PDF- tai PowerPoint-tiedostoksi?", body: "Liitä julkisen sivun HTTPS-URL, valitse PDF tai PowerPoint sekä sivukaappaukset tai muokattava tila ja tarkista osiot. Käytä kirjautuneella sivulla aktiivisen välilehden Page 2 File -laajennusta." },
      { title: "Voiko Page 2 File säilyttää sivun ulkoasun?", body: "Sivukaappaukset on suunniteltu säilyttämään renderöity ulkoasu, kuten asettelu, värit, kuvat ja näkyvät kaaviot. Animaatiot, videot ja vuorovaikutteiset ohjaimet renderöidään staattisina." },
      { title: "Säilyvätkö teksti ja linkit muokattavina?", body: "Muokattava tila säilyttää tuetun tekstin ja turvalliset linkkikohteet. Monimutkaiset moduulit, selaimen suoraan piirtämä grafiikka ja tukemattomat elementit voidaan renderöidä kuvina. Sivukaappaukset painottavat ulkoasua." },
      { title: "Voiko pitkät ja dynaamiset sivut kaapata kokonaan?", body: "Laajennus käyttää renderöityä aktiivista välilehteä. Avaa ensin sisältö ja selaa loppuun. Piilotettua tai lataamatonta sisältöä ei voi viedä." },
      { title: "Voinko muuntaa sivuja kirjautumisen jälkeen?", body: "Kyllä, Chrome-laajennuksella sen jälkeen, kun sivu on avattu normaalisti. Laajennus käyttää aktiivista välilehteä eikä kysy salasanaasi julkisen URL:n lomakkeessa. Se ei ohita käyttöoikeuksia." },
      {
        title: "Voinko muuntaa yhden sivun tai koko verkkosivuston?",
        body: [
          { kind: "text", text: "Verkkosivumuuntimet sekä " },
          { kind: "link", label: "Webpage to PDF Converter — Web2File", route: "page2pdf-gpt" },
          { kind: "text", text: " ja " },
          { kind: "link", label: "One Page 2 PowerPoint", route: "one-page2powerpoint-gpt" },
          { kind: "text", text: " käsittelevät yhden URL-osoitteen. Käytä useille saavutettaville julkisille sivuille " },
          { kind: "link", label: "Web 2 PDF", route: "web2pdf-gpt" },
          { kind: "text", text: " - tai " },
          { kind: "link", label: "Web 2 PowerPoint", route: "web2powerpoint-gpt" },
          { kind: "text", text: " -sovellusta: saat erillisen PDF- tai PPTX-tiedoston kustakin valitusta sivusta, et yhtä yhdistettyä tiedostoa." },
        ],
      },
      { title: "Mitä eroa on sivukaappauksilla ja muokattavilla tiloilla?", body: "Sivukaappaukset painottavat renderöidyn sivun tarkkuutta. Muokattava tila painottaa valittavaa tekstiä, tuettuja kuvia, turvallisia linkkejä ja uudelleenkäytettävää rakennetta. Tarkista monimutkainen grafiikka ja asettelu." },
      { title: "Mitä esikatselutiedoille tapahtuu, kun välilehti suljetaan?", body: "Tiedot ovat väliaikaisia ja poistetaan, kun välilehti suljetaan. Page 2 File ei ylläpidä käyttäjien muunnoshistorian tietokantaa eikä aiempien esikatselujen arkistoa." },
      { title: "Tarvitsenko tilin?", body: "Et tarvitse Page 2 File -tiliä julkisiin URL-osoitteisiin tai laajennuksen esikatseluun. Yksityisellä sivulla saatat joutua kirjautumaan lähdesivustolle." },
      { title: "Voinko viedä AI- ja viestikeskusteluja?", body: "Laajennus vie Chrome-välilehdellä renderöidyn keskustelun, mukaan lukien tuetut AI-keskustelut ja verkkoviestit. Lataa ensin haluttu viestialue. Selaimen ulkopuolisia sovelluksia, kuten Signal Desktopia, ei kaapata." },
    ],
    title: "Hyvä tietää",
  },
  finalCta: {
    body: "Liitä julkinen linkki tähän tai asenna laajennus nykyistä välilehteä varten.",
    eyebrow: "HALUATKO KOKEILLA OMALLA SIVULLASI?",
    title: "Hanki PDF tai PowerPoint ennen muokkausohjelman avaamista",
  },
};
