import type { HomeCopy } from "./home-copy";

export const homeCopyCs: HomeCopy = {
  title: "Exportujte libovolnou webovou stránku do PDF/PPTX",
  lead: "Vložte odkaz na veřejnou stránku. Page 2 File ji pečlivě rozdělí na stránky PDF nebo snímky PowerPointu a před stažením nabídne náhled.",
  form: {
    formatLabel: "Formát",
    meta: "Bez registrace · Náhled · Dočasné soubory",
    pdfModeLabel: "Režim PDF",
    pdfModes: [{ label: "Snímky stránky", value: "visual" }, { label: "Upravitelné PDF", value: "editable" }],
    powerpointModeLabel: "Režim PowerPointu",
    powerpointModes: [{ label: "Snímky prezentace", value: "visual" }, { label: "Upravitelná prezentace", value: "editable" }],
    submitPdf: "Vytvořit PDF",
    submitPowerpoint: "Vytvořit PowerPoint",
    urlHelper: "Pouze veřejné stránky HTTPS. Pro přihlášené karty použijte rozšíření.",
    urlLabel: "Odkaz na webovou stránku",
    urlPlaceholder: "https://example.com/clanek",
  },
  converterFlow: {
    backAction: "Zpět k nastavení",
    processingBody: "Analyzujeme stránku a připravujeme zvolený formát souboru.",
    processingTitle: "Připravujeme váš soubor",
    readyBody: "Kliknutím stáhnete soubor",
    readyTitle: "Váš soubor je připraven",
  },
  closingNote: "Služba funguje s články, dokumentací, vstupními stránkami a veřejnými zprávami. Pro soukromé stránky nebo AI chaty používá rozšíření aktivní kartu prohlížeče a vytváří dočasný náhled.",
  preview: {
    accessibleLabel: "Ukázkový výsledek konverze",
    divider: "ZALOMENÍ STRÁNKY UDRŽÍ OBRÁZEK POHROMADĚ",
    imageNote: "Obrázek zůstane celý",
    pdfMeta: "12 stránek · připraveno",
    powerpointMeta: "12 snímků · připraveno",
    sourceTitle: "Dlouhý článek s obrázkem",
    title: "Stránka → přesný soubor",
  },
  promo: {
    body: "Rozšíření funguje dvěma způsoby: přes URL nebo s aktivní kartou. Data exportované stránky se po zavření náhledu odstraní ze serveru.",
    eyebrow: "ROZŠÍŘENÍ CHROME",
    title: "Exportujte aktuální kartu, i když je nutné přihlášení.",
  },
  features: {
    eyebrow: "FUNKCE",
    title: "Flexibilní možnosti exportovaného obsahu",
    body: "Exportujte stránky ve vhodném formátu: jako snímky stránky nebo se zachováním médií, odkazů a struktury.",
    items: [
      { title: "Exportujte AI chaty a komunikátory", body: "Exportujte dlouhé konverzace z ChatGPT, Claude, Gemini, Grok, DeepSeek a dalších služeb do přehledného PDF." },
      { title: "2 nejpraktičtější formáty", list: { items: ["Ukládejte snímky stránky jako PDF/PPTX.", "Vytvářejte upravitelné soubory PDF/PPTX se zachováním médií, odkazů a struktury."], style: "unordered" } },
      { title: "Ovládejte obsah souboru", body: "Kombinujte zachovaná média, odkazy a styly. V náhledu můžete odstranit nepotřebné prvky stránky." },
      { title: "2 způsoby práce", body: "Exportujte aktuální kartu libovolného webu nebo zadejte URL veřejné stránky." },
      { title: "Vyřešené problémy jiných služeb", body: "Získejte PDF nebo PPTX s celými obrázky a bez nadměrných mezer mezi obsahem." },
      { title: "Bezpečně a bez registrace", body: "Nemusíte vytvářet účet. Nainstalujte rozšíření a uložte vybranou stránku." },
    ],
  },
  howItWorks: {
    action: "Otevřít celý návod",
    body: "Nejrychlejší je rozšíření: pracuje s aktuální kartou a nevyžaduje kopírování odkazu.",
    eyebrow: "JAK ZAČÍT",
    extensionAction: "Nainstalovat rozšíření",
    installTime: "Za 30 sekund",
    items: [
      { title: "Nainstalujte rozšíření", body: "Přidejte Page 2 File do Chromu. Účet Page 2 File není potřeba." },
      { title: "Otevřete stránku", list: { items: ["Přejděte na požadovanou kartu.", "Otevřete Page 2 File.", "Klikněte na Preview."], style: "ordered" } },
      { title: "Zkontrolujte a stáhněte", body: "Zkontrolujte výsledek, případně odstraňte části a stáhněte hotový soubor." },
    ],
    note: "S příklady veřejného odkazu, soukromé karty a AI chatu",
    stepLabels: ["Krok 1", "Krok 2", "Krok 3"],
    title: "Tři kroky k hotovému souboru",
  },
  blog: {
    action: "Číst článek",
    allAction: "Všechny články",
    body: "Praktické návody o věrnosti, úpravách, odkazech, zalomení stránek a bezpečném zpracování AI chatů.",
    eyebrow: "BLOG",
    items: [{ slug: "why-print-to-pdf-breaks" }, { slug: "visual-vs-editable" }, { slug: "preserve-clickable-links" }, { slug: "long-webpage-page-breaks" }],
    title: "Návody k exportu různých typů webů",
  },
  faq: {
    body: "Jasné odpovědi o zachycení stránek, režimech výstupu, soukromých kartách, dočasných náhledech a exportu chatů.",
    eyebrow: "ČASTÉ DOTAZY",
    items: [
      { title: "Jak převedu webovou stránku do PDF nebo PowerPointu?", body: "U veřejné stránky vložte URL s HTTPS, zvolte PDF nebo PowerPoint a snímky stránky či upravitelný režim a před vytvořením souboru zkontrolujte části. U přihlášené stránky použijte rozšíření Page 2 File v aktivní kartě." },
      { title: "Dokáže Page 2 File zachovat vzhled stránky?", body: "Snímky stránky zachovávají vykreslený vzhled včetně rozvržení, barev, obrázků a viditelných grafů. Animace, video a interaktivní ovládací prvky se zobrazují staticky." },
      { title: "Zůstanou text a odkazy upravitelné?", body: "Upravitelný režim zachová podporovaný text a bezpečné cíle odkazů. Složité widgety, canvas a nepodporované prvky mohou být převedeny na obrázky. Snímky stránky upřednostňují vzhled." },
      { title: "Lze zachytit dlouhé a dynamické stránky?", body: "Rozšíření pracuje s vykreslenou aktivní kartou. Nejprve rozbalte obsah a posuňte stránku až dolů. Skrytý nebo nenačtený obsah nelze exportovat." },
      { title: "Mohu převádět stránky po přihlášení?", body: "Ano, pomocí rozšíření Chrome po běžném otevření stránky. Rozšíření používá aktivní kartu a nevyžaduje heslo ve formuláři veřejné URL. Neobchází řízení přístupu." },
      {
        title: "Mohu převést jednu stránku nebo celý web?",
        body: [
          { kind: "text", text: "Konvertory stránek a také " },
          { kind: "link", label: "One Page 2 PDF", route: "page2pdf-gpt" },
          { kind: "text", text: " a " },
          { kind: "link", label: "One Page 2 PowerPoint", route: "one-page2powerpoint-gpt" },
          { kind: "text", text: " zpracují jednu URL. Pro více dostupných veřejných stránek použijte " },
          { kind: "link", label: "Web 2 PDF", route: "web2pdf-gpt" },
          { kind: "text", text: " nebo " },
          { kind: "link", label: "Web 2 PowerPoint", route: "web2powerpoint-gpt" },
          { kind: "text", text: ": obdržíte samostatné PDF nebo PPTX pro každou vybranou stránku, nikoli jeden sloučený soubor." },
        ],
      },
      { title: "Jaký je rozdíl mezi snímky stránky a upravitelnými režimy?", body: "Snímky stránky upřednostňují věrnost vykreslené stránce. Upravitelný režim upřednostňuje označitelný text, podporované obrázky, bezpečné odkazy a opakovaně použitelné struktury. Zkontrolujte složitou grafiku a rozvržení." },
      { title: "Co se stane s daty náhledu po zavření karty?", body: "Data náhledu jsou dočasná a po zavření karty se odstraní. Page 2 File nevede databázi historie konverzí ani archiv předchozích náhledů." },
      { title: "Potřebuji účet?", body: "Účet Page 2 File není potřeba pro veřejnou URL ani pro náhled rozšíření. U soukromé stránky může být nutné zůstat přihlášený na zdrojovém webu." },
      { title: "Mohu exportovat AI chaty a komunikátory?", body: "Rozšíření exportuje konverzaci vykreslenou v kartě Chrome, včetně podporovaných AI chatů a webových komunikátorů. Nejprve načtěte potřebný rozsah zpráv. Aplikace mimo prohlížeč, například Signal Desktop, se nezachytí." },
    ],
    title: "Co je dobré vědět",
  },
  finalCta: {
    body: "Vložte sem veřejný odkaz nebo nainstalujte rozšíření pro aktuální kartu.",
    eyebrow: "CHCETE TO VYZKOUŠET NA SVÉ STRÁNCE?",
    title: "Získejte PDF nebo PowerPoint ještě před otevřením editoru",
  },
};
