import type { HomeCopy } from "./home-copy";

export const homeCopyNo: HomeCopy = {
  title: "Eksporter en hvilken som helst nettside til PDF/PPTX",
  lead: "Lim inn lenken til en offentlig side. Page 2 File deler den nøyaktig inn i PDF-sider eller PowerPoint-lysbilder, med forhåndsvisning før nedlasting.",
  form: {
    formatLabel: "Format",
    meta: "Ingen registrering · Forhåndsvisning · Midlertidige filer",
    pdfModeLabel: "PDF-modus",
    pdfModes: [{ label: "Sidebilder", value: "visual" }, { label: "Redigerbar PDF", value: "editable" }],
    powerpointModeLabel: "PowerPoint-modus",
    powerpointModes: [{ label: "Bilder av lysbilder", value: "visual" }, { label: "Redigerbar presentasjon", value: "editable" }],
    submitPdf: "Opprett PDF",
    submitPowerpoint: "Opprett PowerPoint",
    urlHelper: "Bare offentlige HTTPS-sider. Bruk utvidelsen for påloggede faner.",
    urlLabel: "Lenke til nettsiden",
    urlPlaceholder: "https://example.com/artikkel",
  },
  converterFlow: {
    backAction: "Tilbake til oppsettet",
    processingBody: "Vi analyserer siden og forbereder det valgte filformatet.",
    processingTitle: "Vi forbereder filen din",
    readyBody: "Klikk for å laste ned filen",
    readyTitle: "Filen din er klar",
  },
  closingNote: "Tjenesten fungerer med artikler, dokumentasjon, landingssider og offentlige rapporter. For private sider eller AI-chatter bruker utvidelsen den aktive nettleserfanen og oppretter en midlertidig forhåndsvisning.",
  preview: {
    accessibleLabel: "Eksempel på konverteringsresultat",
    divider: "SIDESKIFTET HOLDER BILDET SAMLET",
    imageNote: "Bildet forblir helt",
    pdfMeta: "12 sider · klar",
    powerpointMeta: "12 lysbilder · klar",
    sourceTitle: "En lang artikkel med et bilde",
    title: "Side → nøyaktig fil",
  },
  promo: {
    body: "Utvidelsen fungerer på to måter: via URL eller med den aktive fanen. Data fra den eksporterte siden slettes fra serveren når forhåndsvisningen lukkes.",
    eyebrow: "CHROME-UTVIDELSE",
    title: "Eksporter gjeldende fane, også når pålogging kreves.",
  },
  features: {
    eyebrow: "FUNKSJONER",
    title: "Fleksible alternativer for eksportert innhold",
    body: "Eksporter nettsider i riktig format: som sidebilder eller med bevarte medier, lenker og struktur.",
    items: [
      { title: "Eksporter AI- og meldingschatter", body: "Eksporter lange samtaler fra ChatGPT, Claude, Gemini, Grok, DeepSeek og andre tjenester til en ryddig PDF." },
      { title: "De 2 mest praktiske formatene", list: { items: ["Lagre sidebilder som PDF/PPTX.", "Opprett redigerbare PDF/PPTX-filer som bevarer medier, lenker og struktur."], style: "unordered" } },
      { title: "Kontroller filinnholdet", body: "Kombiner bevarte medier, lenker og formatering. I forhåndsvisningen kan du også fjerne unødvendige sideelementer." },
      { title: "2 arbeidsmåter", body: "Eksporter gjeldende fane fra et hvilket som helst nettsted, eller skriv inn URL-en til en offentlig side." },
      { title: "Problemer i andre tjenester løst", body: "Få en PDF eller PPTX med hele bilder og uten unødvendig store mellomrom i innholdet." },
      { title: "Sikkert og uten registrering", body: "Du trenger ingen konto. Installer utvidelsen og lagre den valgte siden." },
    ],
  },
  howItWorks: {
    action: "Åpne hele veiledningen",
    body: "Den raskeste måten er utvidelsen: den bruker gjeldende fane og krever ikke at du kopierer en lenke.",
    eyebrow: "SLIK KOMMER DU I GANG",
    extensionAction: "Installer utvidelsen",
    installTime: "På 30 sekunder",
    items: [
      { title: "Installer utvidelsen", body: "Legg Page 2 File til i Chrome. Du trenger ingen Page 2 File-konto." },
      { title: "Åpne siden", list: { items: ["Gå til ønsket fane.", "Åpne Page 2 File.", "Klikk på Preview."], style: "ordered" } },
      { title: "Kontroller og last ned", body: "Kontroller resultatet, fjern deler ved behov og last ned den ferdige filen." },
    ],
    note: "Med eksempler på en offentlig lenke, en privat fane og en AI-chat",
    stepLabels: ["Trinn 1", "Trinn 2", "Trinn 3"],
    title: "Tre trinn til en ferdig fil",
  },
  blog: {
    action: "Les artikkelen",
    allAction: "Alle artikler",
    body: "Praktiske veiledninger om gjengivelse, redigering, lenker, sideskift og sikker håndtering av AI-chatter.",
    eyebrow: "BLOGG",
    items: [{ slug: "why-print-to-pdf-breaks" }, { slug: "visual-vs-editable" }, { slug: "preserve-clickable-links" }, { slug: "long-webpage-page-breaks" }],
    title: "Veiledninger for eksport av ulike typer nettsteder",
  },
  faq: {
    body: "Tydelige svar om sidefangst, utdatamoduser, private faner, midlertidige forhåndsvisninger og chatteksport.",
    eyebrow: "VANLIGE SPØRSMÅL",
    items: [
      { title: "Hvordan konverterer jeg en nettside til PDF eller PowerPoint?", body: "For en offentlig side limer du inn HTTPS-URL-en, velger PDF eller PowerPoint og sidebilder eller redigerbar modus, og kontrollerer delene. For en pålogget side bruker du Page 2 File-utvidelsen i den aktive fanen." },
      { title: "Kan Page 2 File bevare utformingen av siden?", body: "Sidebilder er laget for å bevare det gjengitte utseendet, inkludert layout, farger, bilder og synlige diagrammer. Animasjoner, video og interaktive kontroller gjengis statisk." },
      { title: "Forblir tekst og lenker redigerbare?", body: "Redigerbar modus bevarer støttet tekst og sikre lenkemål. Komplekse moduler, grafikk som nettleseren tegner direkte og elementer som ikke støttes, kan gjengis som bilder. Sidebilder prioriterer utseendet." },
      { title: "Kan lange og dynamiske sider fanges helt?", body: "Utvidelsen bruker den gjengitte aktive fanen. Utvid først innholdet og rull til slutten. Skjult eller ikke innlastet innhold kan ikke eksporteres." },
      { title: "Kan jeg konvertere sider etter pålogging?", body: "Ja, med Chrome-utvidelsen etter at siden er åpnet på vanlig måte. Utvidelsen bruker den aktive fanen og ber ikke om passordet ditt i skjemaet for offentlige URL-er. Den omgår ikke tilgangskontroller." },
      {
        title: "Kan jeg konvertere én side eller et helt nettsted?",
        body: [
          { kind: "text", text: "Nettsidekonvertererne og " },
          { kind: "link", label: "Webpage to PDF Converter — Web2File", route: "page2pdf-gpt" },
          { kind: "text", text: " og " },
          { kind: "link", label: "One Page 2 PowerPoint", route: "one-page2powerpoint-gpt" },
          { kind: "text", text: " behandler én URL. For flere tilgjengelige offentlige sider bruker du " },
          { kind: "link", label: "Web 2 PDF", route: "web2pdf-gpt" },
          { kind: "text", text: " eller " },
          { kind: "link", label: "Web 2 PowerPoint", route: "web2powerpoint-gpt" },
          { kind: "text", text: ": du får en separat PDF eller PPTX for hver valgte side, ikke én kombinert fil." },
        ],
      },
      { title: "Hva er forskjellen på sidebilder og redigerbare moduser?", body: "Sidebilder prioriterer trohet mot den gjengitte siden. Redigerbar modus prioriterer markerbar tekst, støttede bilder, sikre lenker og gjenbrukbare strukturer. Kontroller kompleks grafikk og layout." },
      { title: "Hva skjer med forhåndsvisningsdata når fanen lukkes?", body: "Dataene er midlertidige og slettes når fanen lukkes. Page 2 File har ingen database med konverteringshistorikk og ikke noe arkiv over tidligere forhåndsvisninger." },
      { title: "Trenger jeg en konto?", body: "Du trenger ingen Page 2 File-konto for offentlige URL-er eller forhåndsvisning i utvidelsen. For en privat side kan det være nødvendig å være pålogget kildenettstedet." },
      { title: "Kan jeg eksportere AI- og meldingschatter?", body: "Utvidelsen eksporterer en samtale som er gjengitt i en Chrome-fane, inkludert støttede AI-chatter og nettmeldinger. Last først inn riktig meldingsområde. Apper utenfor nettleseren, som Signal Desktop, fanges ikke." },
    ],
    title: "Nyttig å vite",
  },
  finalCta: {
    body: "Lim inn en offentlig lenke her, eller installer utvidelsen for gjeldende fane.",
    eyebrow: "VIL DU PRØVE MED DIN SIDE?",
    title: "Få en PDF eller PowerPoint før du åpner et redigeringsprogram",
  },
};
