import type { Locale } from "@/shared/i18n/locales";
import type { LandingContent } from "./landings";

type AboutCopy = {
  title: string;
  description: string;
  lead: string;
  operatorHeading: string;
  operatorBody: string;
  editorialHeading: string;
  editorialBody: string;
  sourcesHeading: string;
  sourcesBody: string;
  correctionsHeading: string;
  correctionsBody: string;
};

const aboutCopy: Record<Locale, AboutCopy> = {
  en: {
    title: "About Page 2 File",
    description: "Learn who operates Page 2 File, how its guides are researched and reviewed, which sources are used, and how to report a correction.",
    lead: "Page 2 File publishes practical conversion tools and guides for people who need a clear PDF or PowerPoint copy of a webpage.",
    operatorHeading: "Who operates the service",
    operatorBody: "Page 2 File is operated by {{entityName}} from {{address}}. The service is independent of the websites, AI platforms and messaging services mentioned in its guides.",
    editorialHeading: "How guides are prepared",
    editorialBody: "Each guide starts with a specific user task. We check the described workflow against the current Page 2 File interface, state access and privacy limits before the call to action, and remove claims that cannot be verified.",
    sourcesHeading: "How sources are used",
    sourcesBody: "For product behavior outside Page 2 File, we prefer current documentation from the organization responsible for that product. Sources support factual claims; they do not replace a plain-language explanation or our own verification of Page 2 File.",
    correctionsHeading: "Corrections and contact",
    correctionsBody: "If a guide is unclear, outdated or incorrect, email {{contactEmail}} with the page URL and the passage in question. We review reproducible corrections and update the article date when the published meaning changes.",
  },
  ru: {
    title: "О Page 2 File и редакционных принципах",
    description: "Узнайте, кто управляет Page 2 File, как мы готовим и проверяем инструкции, выбираем источники и принимаем сообщения об ошибках.",
    lead: "Page 2 File публикует понятные инструменты и инструкции для тех, кому нужно сохранить веб-страницу в PDF или PowerPoint.",
    operatorHeading: "Кто управляет сервисом",
    operatorBody: "Сервисом Page 2 File управляет {{entityName}}, адрес: {{address}}. Сервис не связан с сайтами, AI-платформами и мессенджерами, упомянутыми в инструкциях.",
    editorialHeading: "Как готовятся инструкции",
    editorialBody: "Каждая инструкция отвечает на конкретную задачу пользователя. Мы сверяем описанный порядок действий с текущим интерфейсом Page 2 File, заранее объясняем ограничения доступа и приватности и удаляем утверждения, которые нельзя проверить.",
    sourcesHeading: "Как мы используем источники",
    sourcesBody: "Для сведений о сторонних продуктах мы выбираем актуальную документацию их владельцев. Источники подтверждают факты, но не заменяют понятное объяснение и нашу собственную проверку Page 2 File.",
    correctionsHeading: "Исправления и связь",
    correctionsBody: "Если инструкция непонятна, устарела или содержит ошибку, напишите на {{contactEmail}}, укажите адрес страницы и спорный фрагмент. Мы проверяем воспроизводимые замечания и меняем дату статьи, когда обновляется её смысл.",
  },
  de: {
    title: "Über Page 2 File",
    description: "Erfahren Sie, wer Page 2 File betreibt, wie Anleitungen geprüft werden, welche Quellen wir nutzen und wie Sie Fehler melden können.",
    lead: "Page 2 File bietet verständliche Werkzeuge und Anleitungen zum Speichern von Webseiten als PDF oder PowerPoint.",
    operatorHeading: "Wer den Dienst betreibt",
    operatorBody: "Page 2 File wird von {{entityName}} unter der Anschrift {{address}} betrieben. Der Dienst ist unabhängig von den in den Anleitungen genannten Websites, KI-Plattformen und Messengern.",
    editorialHeading: "Wie Anleitungen entstehen",
    editorialBody: "Jede Anleitung beginnt mit einer konkreten Aufgabe. Wir prüfen den Ablauf in der aktuellen Page-2-File-Oberfläche, erklären Zugriffs- und Datenschutzgrenzen vor dem Aufruf zum Handeln und entfernen nicht belegbare Aussagen.",
    sourcesHeading: "Wie wir Quellen nutzen",
    sourcesBody: "Für Angaben zu fremden Produkten bevorzugen wir aktuelle Unterlagen des jeweiligen Anbieters. Quellen belegen Fakten, ersetzen aber weder eine verständliche Erklärung noch unsere eigene Prüfung von Page 2 File.",
    correctionsHeading: "Korrekturen und Kontakt",
    correctionsBody: "Ist eine Anleitung unklar, veraltet oder falsch, senden Sie die Seitenadresse und die betreffende Stelle an {{contactEmail}}. Wir prüfen nachvollziehbare Hinweise und ändern das Artikeldatum, wenn sich die veröffentlichte Aussage ändert.",
  },
  fr: {
    title: "À propos de Page 2 File",
    description: "Découvrez qui gère Page 2 File, comment les guides sont vérifiés, quelles sources sont utilisées et comment signaler une erreur.",
    lead: "Page 2 File propose des outils et des guides clairs pour enregistrer une page web en PDF ou en PowerPoint.",
    operatorHeading: "Qui gère le service",
    operatorBody: "Page 2 File est exploité par {{entityName}}, à l’adresse {{address}}. Le service est indépendant des sites, plateformes d’IA et messageries cités dans ses guides.",
    editorialHeading: "Comment les guides sont préparés",
    editorialBody: "Chaque guide part d’une tâche précise. Nous vérifions les étapes dans l’interface actuelle de Page 2 File, expliquons les limites d’accès et de confidentialité avant l’appel à l’action et retirons les promesses invérifiables.",
    sourcesHeading: "Comment les sources sont utilisées",
    sourcesBody: "Pour les produits tiers, nous privilégions la documentation actuelle de leur responsable. Les sources étayent les faits, sans remplacer une explication claire ni notre propre vérification de Page 2 File.",
    correctionsHeading: "Corrections et contact",
    correctionsBody: "Si un guide est imprécis, ancien ou erroné, envoyez son adresse et le passage concerné à {{contactEmail}}. Nous vérifions les signalements reproductibles et modifions la date quand le sens publié change.",
  },
  es: {
    title: "Acerca de Page 2 File",
    description: "Conozca quién gestiona Page 2 File, cómo revisamos las guías, qué fuentes usamos y cómo puede comunicarnos una corrección.",
    lead: "Page 2 File ofrece herramientas y guías claras para guardar una página web como PDF o PowerPoint.",
    operatorHeading: "Quién gestiona el servicio",
    operatorBody: "Page 2 File está gestionado por {{entityName}}, con dirección en {{address}}. El servicio es independiente de los sitios, plataformas de IA y mensajerías citados en sus guías.",
    editorialHeading: "Cómo preparamos las guías",
    editorialBody: "Cada guía parte de una tarea concreta. Comprobamos los pasos en la interfaz actual de Page 2 File, explicamos antes los límites de acceso y privacidad y retiramos las afirmaciones que no podemos verificar.",
    sourcesHeading: "Cómo usamos las fuentes",
    sourcesBody: "Para productos ajenos preferimos documentación actual del responsable del producto. Las fuentes respaldan hechos, pero no sustituyen una explicación clara ni nuestra propia comprobación de Page 2 File.",
    correctionsHeading: "Correcciones y contacto",
    correctionsBody: "Si una guía es confusa, antigua o incorrecta, envíe a {{contactEmail}} la dirección de la página y el fragmento. Revisamos los avisos reproducibles y cambiamos la fecha cuando se modifica el sentido publicado.",
  },
  nl: {
    title: "Over Page 2 File",
    description: "Lees wie Page 2 File beheert, hoe handleidingen worden gecontroleerd, welke bronnen we gebruiken en hoe je een fout meldt.",
    lead: "Page 2 File biedt duidelijke hulpmiddelen en handleidingen om een webpagina als PDF of PowerPoint op te slaan.",
    operatorHeading: "Wie de dienst beheert",
    operatorBody: "Page 2 File wordt beheerd door {{entityName}} op {{address}}. De dienst staat los van websites, AI-platforms en chatdiensten die in de handleidingen worden genoemd.",
    editorialHeading: "Hoe handleidingen worden gemaakt",
    editorialBody: "Elke handleiding begint met een concrete gebruikerstaak. We controleren de stappen in de actuele Page 2 File-interface, leggen toegangs- en privacygrenzen vooraf uit en verwijderen beweringen die niet controleerbaar zijn.",
    sourcesHeading: "Hoe we bronnen gebruiken",
    sourcesBody: "Voor andere producten gebruiken we bij voorkeur actuele documentatie van de verantwoordelijke organisatie. Bronnen onderbouwen feiten, maar vervangen geen duidelijke uitleg of onze eigen controle van Page 2 File.",
    correctionsHeading: "Correcties en contact",
    correctionsBody: "Is een handleiding onduidelijk, verouderd of onjuist, mail dan de pagina en passage naar {{contactEmail}}. We onderzoeken reproduceerbare meldingen en wijzigen de artikeldatum wanneer de gepubliceerde betekenis verandert.",
  },
  pt: {
    title: "Sobre o Page 2 File",
    description: "Saiba quem gere o Page 2 File, como os guias são verificados, que fontes utilizamos e como comunicar uma correção.",
    lead: "O Page 2 File oferece ferramentas e guias claros para guardar uma página Web em PDF ou PowerPoint.",
    operatorHeading: "Quem gere o serviço",
    operatorBody: "O Page 2 File é gerido por {{entityName}}, em {{address}}. O serviço é independente dos sites, plataformas de IA e serviços de mensagens mencionados nos guias.",
    editorialHeading: "Como preparamos os guias",
    editorialBody: "Cada guia começa com uma tarefa concreta. Verificamos os passos na interface atual do Page 2 File, explicamos antecipadamente os limites de acesso e privacidade e removemos afirmações que não podem ser confirmadas.",
    sourcesHeading: "Como utilizamos fontes",
    sourcesBody: "Para produtos externos, preferimos documentação atual da organização responsável. As fontes sustentam factos, mas não substituem uma explicação clara nem a nossa verificação do Page 2 File.",
    correctionsHeading: "Correções e contacto",
    correctionsBody: "Se um guia estiver pouco claro, desatualizado ou incorreto, envie a página e o trecho para {{contactEmail}}. Verificamos relatos reproduzíveis e alteramos a data quando o sentido publicado muda.",
  },
  it: {
    title: "Informazioni su Page 2 File",
    description: "Scopri chi gestisce Page 2 File, come verifichiamo le guide, quali fonti utilizziamo e come segnalare una correzione.",
    lead: "Page 2 File offre strumenti e guide chiare per salvare una pagina web come PDF o PowerPoint.",
    operatorHeading: "Chi gestisce il servizio",
    operatorBody: "Page 2 File è gestito da {{entityName}}, con sede in {{address}}. Il servizio è indipendente dai siti, dalle piattaforme di IA e dai servizi di messaggistica citati nelle guide.",
    editorialHeading: "Come prepariamo le guide",
    editorialBody: "Ogni guida parte da un compito preciso. Verifichiamo i passaggi nell’interfaccia attuale di Page 2 File, spieghiamo prima i limiti di accesso e privacy e rimuoviamo le affermazioni che non possiamo verificare.",
    sourcesHeading: "Come utilizziamo le fonti",
    sourcesBody: "Per prodotti esterni preferiamo la documentazione aggiornata dell’organizzazione responsabile. Le fonti sostengono i fatti, ma non sostituiscono una spiegazione chiara o la nostra verifica di Page 2 File.",
    correctionsHeading: "Correzioni e contatti",
    correctionsBody: "Se una guida è poco chiara, superata o errata, invia pagina e passaggio a {{contactEmail}}. Verifichiamo le segnalazioni riproducibili e cambiamo la data quando il significato pubblicato viene modificato.",
  },
  pl: {
    title: "O Page 2 File i zasadach redakcyjnych",
    description: "Sprawdź, kto prowadzi Page 2 File, jak weryfikujemy poradniki, z jakich źródeł korzystamy i jak zgłosić poprawkę.",
    lead: "Page 2 File udostępnia proste narzędzia i poradniki do zapisywania strony internetowej jako PDF lub PowerPoint.",
    operatorHeading: "Kto prowadzi usługę",
    operatorBody: "Page 2 File prowadzi {{entityName}} pod adresem {{address}}. Usługa jest niezależna od stron, platform AI i komunikatorów wymienionych w poradnikach.",
    editorialHeading: "Jak powstają poradniki",
    editorialBody: "Każdy poradnik zaczyna się od konkretnego zadania. Sprawdzamy kroki w aktualnym interfejsie Page 2 File, wcześniej wyjaśniamy ograniczenia dostępu i prywatności oraz usuwamy twierdzenia, których nie można potwierdzić.",
    sourcesHeading: "Jak korzystamy ze źródeł",
    sourcesBody: "W przypadku zewnętrznych produktów wybieramy aktualną dokumentację odpowiedzialnej organizacji. Źródła potwierdzają fakty, ale nie zastępują prostego wyjaśnienia ani naszej kontroli Page 2 File.",
    correctionsHeading: "Poprawki i kontakt",
    correctionsBody: "Jeśli poradnik jest niejasny, nieaktualny lub błędny, wyślij adres strony i fragment na {{contactEmail}}. Sprawdzamy odtwarzalne zgłoszenia i zmieniamy datę, gdy zmienia się opublikowany sens.",
  },
  cs: {
    title: "O službě Page 2 File",
    description: "Zjistěte, kdo provozuje Page 2 File, jak kontrolujeme návody, jaké zdroje používáme a jak nám oznámit opravu.",
    lead: "Page 2 File nabízí srozumitelné nástroje a návody pro uložení webové stránky do PDF nebo PowerPointu.",
    operatorHeading: "Kdo službu provozuje",
    operatorBody: "Page 2 File provozuje {{entityName}} na adrese {{address}}. Služba je nezávislá na webech, platformách AI a komunikačních službách uvedených v návodech.",
    editorialHeading: "Jak návody připravujeme",
    editorialBody: "Každý návod vychází z konkrétního úkolu. Kroky ověřujeme v aktuálním rozhraní Page 2 File, předem vysvětlujeme omezení přístupu a soukromí a odstraňujeme tvrzení, která nelze ověřit.",
    sourcesHeading: "Jak používáme zdroje",
    sourcesBody: "U cizích produktů dáváme přednost aktuální dokumentaci odpovědné organizace. Zdroje dokládají fakta, ale nenahrazují jasné vysvětlení ani naši kontrolu služby Page 2 File.",
    correctionsHeading: "Opravy a kontakt",
    correctionsBody: "Je-li návod nejasný, zastaralý nebo chybný, pošlete adresu stránky a sporný úsek na {{contactEmail}}. Ověřujeme opakovatelné podněty a při změně zveřejněného významu upravíme datum článku.",
  },
  sv: {
    title: "Om Page 2 File och redaktionella principer",
    description: "Läs vem som driver Page 2 File, hur guider granskas, vilka källor vi använder och hur du meddelar en rättelse.",
    lead: "Page 2 File erbjuder tydliga verktyg och guider för att spara en webbsida som PDF eller PowerPoint.",
    operatorHeading: "Vem som driver tjänsten",
    operatorBody: "Page 2 File drivs av {{entityName}} på {{address}}. Tjänsten är fristående från webbplatser, AI-plattformar och meddelandetjänster som nämns i guiderna.",
    editorialHeading: "Hur guider tas fram",
    editorialBody: "Varje guide utgår från en tydlig uppgift. Vi kontrollerar stegen i det aktuella Page 2 File-gränssnittet, förklarar åtkomst- och integritetsgränser i förväg och tar bort påståenden som inte kan verifieras.",
    sourcesHeading: "Hur vi använder källor",
    sourcesBody: "För externa produkter föredrar vi aktuell dokumentation från ansvarig organisation. Källor stöder fakta, men ersätter inte en tydlig förklaring eller vår egen kontroll av Page 2 File.",
    correctionsHeading: "Rättelser och kontakt",
    correctionsBody: "Om en guide är oklar, inaktuell eller felaktig, skicka sidan och avsnittet till {{contactEmail}}. Vi granskar reproducerbara uppgifter och ändrar artikelns datum när den publicerade innebörden ändras.",
  },
  no: {
    title: "Om Page 2 File og redaksjonelle prinsipper",
    description: "Les hvem som driver Page 2 File, hvordan veiledninger kontrolleres, hvilke kilder vi bruker og hvordan du melder en rettelse.",
    lead: "Page 2 File tilbyr tydelige verktøy og veiledninger for å lagre en nettside som PDF eller PowerPoint.",
    operatorHeading: "Hvem som driver tjenesten",
    operatorBody: "Page 2 File drives av {{entityName}} på {{address}}. Tjenesten er uavhengig av nettsteder, AI-plattformer og meldingstjenester som omtales i veiledningene.",
    editorialHeading: "Hvordan veiledninger lages",
    editorialBody: "Hver veiledning starter med en konkret oppgave. Vi kontrollerer trinnene i det gjeldende Page 2 File-grensesnittet, forklarer tilgangs- og personverngrenser på forhånd og fjerner påstander som ikke kan bekreftes.",
    sourcesHeading: "Hvordan vi bruker kilder",
    sourcesBody: "For eksterne produkter foretrekker vi oppdatert dokumentasjon fra ansvarlig organisasjon. Kilder underbygger fakta, men erstatter ikke en tydelig forklaring eller vår egen kontroll av Page 2 File.",
    correctionsHeading: "Rettelser og kontakt",
    correctionsBody: "Hvis en veiledning er uklar, utdatert eller feil, sender du siden og avsnittet til {{contactEmail}}. Vi undersøker opplysninger som kan gjenskapes og endrer artikkeldatoen når det publiserte innholdet endres.",
  },
  da: {
    title: "Om Page 2 File og redaktionelle principper",
    description: "Læs hvem der driver Page 2 File, hvordan vejledninger kontrolleres, hvilke kilder vi bruger, og hvordan du melder en rettelse.",
    lead: "Page 2 File tilbyder tydelige værktøjer og vejledninger til at gemme en webside som PDF eller PowerPoint.",
    operatorHeading: "Hvem der driver tjenesten",
    operatorBody: "Page 2 File drives af {{entityName}} på {{address}}. Tjenesten er uafhængig af de websites, AI-platforme og beskedtjenester, der nævnes i vejledningerne.",
    editorialHeading: "Sådan udarbejdes vejledninger",
    editorialBody: "Hver vejledning begynder med en konkret opgave. Vi kontrollerer trinnene i den aktuelle Page 2 File-grænseflade, forklarer adgangs- og privatlivsgrænser på forhånd og fjerner udsagn, der ikke kan bekræftes.",
    sourcesHeading: "Sådan bruger vi kilder",
    sourcesBody: "For eksterne produkter foretrækker vi opdateret dokumentation fra den ansvarlige organisation. Kilder understøtter fakta, men erstatter ikke en klar forklaring eller vores egen kontrol af Page 2 File.",
    correctionsHeading: "Rettelser og kontakt",
    correctionsBody: "Er en vejledning uklar, forældet eller forkert, så send siden og afsnittet til {{contactEmail}}. Vi undersøger oplysninger, der kan gentages, og ændrer artiklens dato, når den offentliggjorte betydning ændres.",
  },
  fi: {
    title: "Tietoa Page 2 Filestä",
    description: "Lue, kuka ylläpitää Page 2 Fileä, miten oppaat tarkistetaan, mitä lähteitä käytämme ja miten ilmoitat korjauksesta.",
    lead: "Page 2 File tarjoaa selkeitä työkaluja ja oppaita verkkosivun tallentamiseen PDF- tai PowerPoint-tiedostoksi.",
    operatorHeading: "Kuka ylläpitää palvelua",
    operatorBody: "Page 2 Fileä ylläpitää {{entityName}} osoitteessa {{address}}. Palvelu on riippumaton oppaissa mainituista sivustoista, AI-palveluista ja viestipalveluista.",
    editorialHeading: "Miten oppaat laaditaan",
    editorialBody: "Jokainen opas alkaa selkeästä tehtävästä. Tarkistamme vaiheet nykyisessä Page 2 File -käyttöliittymässä, selitämme pääsy- ja tietosuojarajat etukäteen ja poistamme väitteet, joita ei voi vahvistaa.",
    sourcesHeading: "Miten käytämme lähteitä",
    sourcesBody: "Muiden tuotteiden tiedoissa suosimme vastuullisen organisaation ajantasaista dokumentaatiota. Lähteet tukevat faktoja, mutta eivät korvaa selvää selitystä tai omaa Page 2 File -tarkistustamme.",
    correctionsHeading: "Korjaukset ja yhteys",
    correctionsBody: "Jos opas on epäselvä, vanhentunut tai virheellinen, lähetä sivu ja kohta osoitteeseen {{contactEmail}}. Tutkimme toistettavat ilmoitukset ja muutamme artikkelin päivämäärää, kun julkaistu merkitys muuttuu.",
  },
  ro: {
    title: "Despre Page 2 File",
    description: "Aflați cine administrează Page 2 File, cum verificăm ghidurile, ce surse folosim și cum ne puteți semnala o corectură.",
    lead: "Page 2 File oferă instrumente și ghiduri clare pentru salvarea unei pagini web în PDF sau PowerPoint.",
    operatorHeading: "Cine administrează serviciul",
    operatorBody: "Page 2 File este administrat de {{entityName}}, la adresa {{address}}. Serviciul este independent de site-urile, platformele AI și serviciile de mesagerie menționate în ghiduri.",
    editorialHeading: "Cum pregătim ghidurile",
    editorialBody: "Fiecare ghid pornește de la o sarcină clară. Verificăm pașii în interfața actuală Page 2 File, explicăm dinainte limitele de acces și confidențialitate și eliminăm afirmațiile care nu pot fi confirmate.",
    sourcesHeading: "Cum folosim sursele",
    sourcesBody: "Pentru produse externe preferăm documentația actuală a organizației responsabile. Sursele susțin faptele, dar nu înlocuiesc o explicație clară sau propria noastră verificare a Page 2 File.",
    correctionsHeading: "Corecturi și contact",
    correctionsBody: "Dacă un ghid este neclar, vechi sau greșit, trimiteți pagina și fragmentul la {{contactEmail}}. Verificăm sesizările reproductibile și schimbăm data articolului când se modifică sensul publicat.",
  },
  hu: {
    title: "A Page 2 File névjegye",
    description: "Ismerje meg, ki működteti a Page 2 File-t, hogyan ellenőrizzük az útmutatókat, milyen forrásokat használunk és hogyan jelezhet hibát.",
    lead: "A Page 2 File érthető eszközöket és útmutatókat kínál weboldalak PDF- vagy PowerPoint-fájlba mentéséhez.",
    operatorHeading: "Ki működteti a szolgáltatást",
    operatorBody: "A Page 2 File működtetője {{entityName}}, címe: {{address}}. A szolgáltatás független az útmutatókban említett webhelyektől, AI-platformoktól és üzenetküldő szolgáltatásoktól.",
    editorialHeading: "Hogyan készülnek az útmutatók",
    editorialBody: "Minden útmutató egy konkrét feladattal indul. A lépéseket az aktuális Page 2 File felületen ellenőrizzük, előre ismertetjük a hozzáférési és adatvédelmi korlátokat, a nem igazolható állításokat pedig eltávolítjuk.",
    sourcesHeading: "Hogyan használjuk a forrásokat",
    sourcesBody: "Külső termékeknél a felelős szervezet naprakész dokumentációját részesítjük előnyben. A források tényeket támasztanak alá, de nem helyettesítik a világos magyarázatot vagy a Page 2 File saját ellenőrzését.",
    correctionsHeading: "Javítások és kapcsolat",
    correctionsBody: "Ha egy útmutató pontatlan, elavult vagy hibás, küldje el az oldal címét és az érintett részt a {{contactEmail}} címre. Ellenőrizzük a megismételhető jelzéseket, és a közzétett jelentés változásakor frissítjük a cikk dátumát.",
  },
};

export const aboutLandingContent = (
  Object.keys(aboutCopy) as ReadonlyArray<Locale>
).reduce<Record<Locale, LandingContent>>(
  (result, locale) => {
    const copy = aboutCopy[locale];
    result[locale] = {
        route: "about",
        eyebrow: "Page 2 File",
        title: copy.title,
        description: copy.description,
        lead: copy.lead,
        sections: [
          { heading: copy.operatorHeading, body: copy.operatorBody },
          { heading: copy.editorialHeading, body: copy.editorialBody },
          { heading: copy.sourcesHeading, body: copy.sourcesBody },
          { heading: copy.correctionsHeading, body: copy.correctionsBody },
        ],
        legal: false,
      };
    return result;
  },
  {} as Record<Locale, LandingContent>,
);
