import type { LandingContent } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

export const czechLegalLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  privacy: {
    route: "privacy",
    eyebrow: "Soukromí a zpracování údajů",
    title: "Zásady ochrany osobních údajů",
    description: "Jak Page 2 File zpracovává webový obsah, dočasné soubory, cookies, analytická data a žádosti týkající se soukromí.",
    lead: "Tyto Zásady vysvětlují, jaké údaje Page 2 File zpracovává při návštěvě webu, používání rozšíření Chrome nebo převodu stránky do PDFu.",
    sections: [
      { heading: "Provozovatel a rozsah", body: "{{entityName}}, se sídlem na adrese {{address}}, provozuje Page 2 File a odpovídá za popsané zpracování. Zásady platí pro web, rozšíření a související konverzní služby." },
      { heading: "Definice", body: "„Služba“ znamená Page 2 File a jeho funkce. „Obsah konverze“ zahrnuje URL, viditelný obsah, možnosti a vytvořený PDF nebo PDF. „Osobní údaje“ jsou informace, které identifikují osobu nebo s ní mohou být rozumně spojeny." },
      { heading: "Údaje, které zpracováváme", body: "Podle způsobu použití můžeme zpracovávat technické údaje požadavku, IP adresu, prohlížeč a zařízení, navštívené stránky, povolené parametry kampaně, veřejnou URL nebo obsah aktivní karty, nastavení, dočasné identifikátory a vytvořené soubory." },
      { heading: "Údaje, které nepožadujeme", body: "Page 2 File nevyžaduje účet ani údaje o platební kartě, fakturační adresy či hesla zdrojového webu. Rozšíření používá již otevřenou stránku a nedostává heslo použité pro přístup." },
      { heading: "Jak údaje používáme", body: "Údaje zpracováváme pro poskytování náhledů a souborů, prevenci zneužití, diagnostiku chyb, zachování spolehlivosti, pochopení souhrnného použití, vyřizování žádostí a plnění zákona. Osobní údaje neprodáváme." },
      { heading: "Obsah konverze a dočasné zpracování", body: "Konverze veřejné URL nebo náhled rozšíření vyžaduje dočasné zpracování stránky a možností. Nenabízíme historii spojenou s účtem. Data a soubory jsou krátkodobé a odstraní se po zavření náhledu nebo technickém vypršení." },
      { heading: "Analytika a atribuce", body: "Je-li nastaven platný identifikátor, Google Analytics se načítá na veřejných stránkách a může získat údaje o stránce, zařízení, prohlížeči, přibližné poloze a kampani. Povolené hodnoty UTM se normalizují v paměti; Page 2 File je neukládá do vlastního atribučního cookie." },
      { heading: "Poskytovatelé a sdílení", body: "Page 2 File používá {{processors}} k poskytování, ochraně a měření Služby. Technické údaje mohou zpracovat jen v nezbytném rozsahu a podle svých zásad. Údaje můžeme sdělit i na základě zákona, k ochraně práv či bezpečnosti nebo při zákonném převodu podniku." },
      { heading: "Uchovávání a mazání", body: "Obsah konverze se uchovává pouze během dočasného procesu, ne jako viditelná historie. Bezpečnostní, infrastrukturní a analytické záznamy a korespondence mohou být uchovány po dobu rozumně potřebnou k provozu, zákonným povinnostem nebo vyřízení žádosti." },
      { heading: "Zabezpečení", body: "Page 2 File používá trasy stejného původu, anonymní relace, kontroly Origin a CSRF, podepsané požadavky, validaci URL, izolované vykreslení a dočasné soubory. Žádné opatření nezaručuje absolutní bezpečnost; nepřevádějte materiál, který nesmíte sdělit." },
      { heading: "Mezinárodní zpracování", body: "Naši poskytovatelé mohou zpracovávat technická či analytická data mimo vaši zemi. Kde je to nutné, spoléháme na jejich záruky a zákonné mechanismy přenosu. Provozovatel sídlí v {{jurisdiction}}." },
      { heading: "Vaše práva", body: "Podle příslušného práva můžete požádat o přístup, opravu, výmaz či omezení nebo vznést námitku. Protože neexistují účty ani archiv konverzí, můžeme potřebovat údaje k nalezení relevantního provozního záznamu." },
      { heading: "Weby třetích stran", body: "Page 2 File může otevírat nebo převádět obsah třetích stran a odkazovat na externí služby. Jejich obsah, bezpečnost a soukromí závisejí na těchto stranách a jejich podmínkách." },
      { heading: "Děti", body: "Služba není určena dětem mladším 13 let a vědomě jejich údaje neshromažďujeme. Rodič nebo opatrovník nás může kontaktovat s žádostí o výmaz." },
      { id: "cookies", heading: "Cookies", body: "Page 2 File používá krátkodobé cookies p2f_session a p2f_csrf k udržení anonymní relace a ochraně požadavků. Používají SameSite Strict a vyprší po hodině. Google Analytics může nastavovat analytické cookies. Neukládáme do nich obsah konverze ani přímo identifikovatelné profily." },
      { heading: "Blokování a mazání cookies", body: "Cookies můžete blokovat nebo mazat v prohlížeči. Blokování relačních nebo CSRF cookies může zabránit konverzi. Blokování Google Analytics omezuje měření, ale ne načítání veřejných stránek. Pro výmaz použijte nastavení prohlížeče." },
      { heading: "Změny těchto zásad", body: "Zásady můžeme aktualizovat při změně Služby, poskytovatelů nebo zákona. Novou verzi zveřejníme s datem; podstatné změny platí od uvedeného dne." },
      { heading: "Kontakt", body: "Dotazy a žádosti o soukromí posílejte na {{contactEmail}}. Provozovatelem je {{entityName}}, {{address}}, podle právních předpisů {{jurisdiction}}." },
    ],
    legal: true,
  },
  terms: {
    route: "terms",
    eyebrow: "Smlouva o službě",
    title: "Podmínky používání",
    description: "Přečtěte si podmínky používání Page 2 File včetně povolených zdrojů, omezení, odpovědnosti, dostupnosti služby a kontaktu.",
    lead: "Tyto Podmínky upravují používání webu Page 2 File, rozšíření Chrome a služeb konverze do PDF nebo PDFu.",
    sections: [
      { heading: "Souhlas a provozovatel", body: "Přístupem nebo používáním Page 2 File přijímáte tyto Podmínky. Službu provozuje {{entityName}}, se sídlem na adrese {{address}}. Jednáte-li za organizaci, potvrzujete oprávnění přijmout Podmínky jejím jménem." },
      { heading: "Definice", body: "„Služba“ zahrnuje web, rozšíření a konverzní funkce. „Zdrojový obsah“ je stránka, obsah aktivní karty nebo jiný odeslaný materiál. „Výsledek“ je PDF, náhled nebo jiný vytvořený soubor." },
      { heading: "Omezená licence", body: "Udělujeme odvolatelné, nevýhradní, nepřenosné a omezené právo používat Službu podle Podmínek. Vlastnictví softwaru, značky ani chráněných materiálů se nepřevádí." },
      { heading: "Povolené zdroje a vaše odpovědnost", body: "Můžete převádět jen obsah, k němuž máte zákonné právo přístupu, zpracování, reprodukce a stažení. Odpovídáte za URL, obsah, nastavení a použití či distribuci každého Výsledku." },
      { heading: "Zakázané použití", body: "Nepoužívejte Službu k porušení zákona nebo práv, obcházení plateb či kontrol, šíření malwaru, odesílání nezákonného obsahu, zkoumání soukromých sítí, narušování bezpečnosti, přetěžování systémů, nadměrné automatizaci, zpětnému inženýrství chráněných částí ani zkreslování souborů." },
      { heading: "Zdrojový obsah a práva třetích stran", body: "Svých práv k obsahu se nevzdáváte. Page 2 File neposkytuje práva k cizím materiálům. Prohlašujete, že zpracování a Výsledek neporušují autorská práva, soukromí, důvěrnost, smlouvy ani jiná práva." },
      { heading: "Dočasné zpracování", body: "Služba může dočasně zpracovat obsah, nastavení a soubory pro náhled a stažení. Neexistuje historie spojená s účtem. Zásady ochrany osobních údajů popisují data, cookies a poskytovatele." },
      { heading: "Omezení výsledku a věrnosti", body: "Skripty, animace, video, chráněná média, písma, canvas, dynamická data a složitá rozvržení nemusí být reprodukovány přesně. Accurate copy upřednostňuje vzhled; Editable document obnovuje podporovaný text, obrázky a odkazy. Zkontrolujte náhled a Výsledek." },
      { heading: "Služby a odkazy třetích stran", body: "Služba může převádět weby třetích stran nebo na ně odkazovat. Page 2 File neodpovídá za jejich dostupnost, obsah, přesnost, zákonnost, bezpečnost ani soukromí. Platí podmínky poskytovatele." },
      { heading: "Soukromí a cookies", body: "Zásady ochrany osobních údajů vysvětlují dočasné zpracování, analytiku, poskytovatele a cookies. Používáním Služby berete na vědomí zpracování nutné pro požadovanou konverzi." },
      { heading: "Duševní vlastnictví Page 2 File", body: "Služba, software, design, text, loga a další materiály patří nebo jsou licencovány společnosti {{entityName}} a jsou chráněny. Bez výslovného zákonného oprávnění nesmíte odstraňovat označení ani Službu kopírovat, prodávat, sublicencovat nebo komerčně využívat." },
      { heading: "Zpětná vazba", body: "Poskytnete-li dobrovolné návrhy, udělujete nám celosvětové, trvalé a bezplatné právo použít je ke zlepšení či vývoji Služby bez povinnosti odměny. Zdrojový obsah se tím nepřevádí." },
      { heading: "Změny, aktualizace a dostupnost", body: "Můžeme Službu nebo funkce aktualizovat, omezit, pozastavit či ukončit a zavést limity pro bezpečnost, spolehlivost či spravedlivé použití. Kde je to možné, podstatné změny uvedeme na webu." },
      { heading: "Pozastavení a ukončení", body: "Službu můžete kdykoli přestat používat. Přístup můžeme zablokovat při důvodném přesvědčení o porušení Podmínek, ohrožení systémů nebo zákonné povinnosti jednat. Ustanovení určená k dalšímu trvání zůstávají účinná." },
      { heading: "Stížnosti na porušení práv", body: "Domníváte-li se, že materiál dostupný přes Page 2 File porušuje vaše práva, kontaktujte {{contactEmail}} a uveďte dílo, materiál nebo URL, své údaje a důvod stížnosti." },
      { heading: "Bez záruk", body: "V rozsahu dovoleném zákonem jsou Služba a každý Výsledek poskytovány „tak, jak jsou“ a „dle dostupnosti“. Nezaručujeme nepřerušovaný provoz, bezchybnou konverzi, úplnou věrnost, dostupnost třetích stran, vhodnost ani splnění všech potřeb." },
      { heading: "Omezení odpovědnosti", body: "V rozsahu dovoleném zákonem {{entityName}} neodpovídá za nepřímé, náhodné, zvláštní, následné či sankční škody ani ztrátu zisku, dat, podnikání, soukromí či náklady používání nebo nemožnosti použití. Nezrušitelná práva zůstávají nedotčena." },
      { heading: "Odškodnění", body: "V rozsahu dovoleném zákonem souhlasíte s obranou a odškodněním {{entityName}} proti nárokům třetích stran z odeslaného obsahu, použití či distribuce Výsledku, porušení Podmínek nebo práv jiných." },
      { heading: "Oddělitelnost, vzdání se a úplná dohoda", body: "Je-li ustanovení neplatné, ostatní zůstávají účinná a dotčené se vyloží co nejblíže účelu. Nevymáhání není vzdáním se. Podmínky a Zásady ochrany osobních údajů tvoří dohodu." },
      { heading: "Rozhodné právo a spory", body: "Podmínky se řídí právem {{jurisdiction}}. Před řízením se vy a {{entityName}} pokusíte spor v dobré víře vyřešit písemným oznámením. Nevyřešené spory mohou být předloženy příslušným soudům {{jurisdiction}}, pokud kogentní právo nevyžaduje jinak." },
      { heading: "Změny těchto podmínek", body: "Podmínky můžeme měnit při změnách Služby, poskytovatelů nebo zákona. Zveřejníme novou verzi s datem. Další používání po účinnosti znamená souhlas; jinak musíte používání ukončit." },
      { heading: "Kontakt", body: "Dotazy nebo oznámení posílejte na {{contactEmail}} nebo na {{entityName}}, {{address}}." },
    ],
    legal: true,
  },
};
