import type { LandingContent, RelatedRoute } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

const gptRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "page2pdf-gpt", label: "Webpage to PDF Converter — Web2File" },
  { route: "web2pdf-gpt", label: "Web 2 PDF" },
  { route: "html2pdf-gpt", label: "HTML 2 PDF" },
  { route: "one-page2powerpoint-gpt", label: "One Page 2 PowerPoint" },
  { route: "web2powerpoint-gpt", label: "Web 2 PowerPoint" },
];
const chatRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "export-ai-chat-to-pdf", label: "Všechny exporty AI chatů" },
  { route: "export-chatgpt-to-pdf", label: "ChatGPT do PDF" },
  { route: "export-claude-to-pdf", label: "Claude do PDF" },
  { route: "export-gemini-to-pdf", label: "Gemini do PDF" },
  { route: "export-grok-to-pdf", label: "Grok do PDF" },
];

export const czechLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  "page2pdf-gpt": {
    route: "page2pdf-gpt",
    eyebrow: "Aplikace GPT · přesné URL, PDF nebo snímky",
    title: "Webpage to PDF Converter — Web2File",
    displayTitle: "GPT: Webpage 2 PDF",
    description: "Webpage to PDF Converter — Web2File zpracuje přesné veřejné URL, PDF webových stránek a snímky jako Visual PDF nebo Interactive PDF.",
    lead: "Zadejte přesnou veřejnou URL, seznam přesných URL, PDF webové stránky nebo celostránkové či navazující snímky. Zvolte Visual PDF pro uložení webu jako snímků nebo Interactive PDF pro označitelný text a klikací odkazy.",
    sections: [
      { heading: "1. Zadejte jednu nebo více URL", body: "Odešlete veřejnou URL, seznam přesných veřejných URL, existující PDF webové stránky nebo celostránkové či navazující snímky. Každá webová stránka zůstane v samostatném PDF." },
      { heading: "2. Zvolte typ PDF", body: "Zvolte Visual PDF pro obrazový výsledek upřednostňující vzhled stránky, nebo Interactive PDF, pokud jsou důležitější označitelný text a klikací odkazy. Pro celý seznam URL platí jeden režim." },
      { heading: "3. Převádějte pouze zadané stránky", body: "Aplikace otevírá jen přesné veřejné URL. Neprochází domény ani sitemapy, nevyhledává stránky, nenásleduje interní odkazy a neobchází přihlášení, paywally, CAPTCHA, geografická ani jiná omezení přístupu. Pro nalezení celého webu použijte Web2File: Website 2 PDF." },
      { heading: "4. Zpracujte PDF a snímky", body: "Nahrané snímky lze sestavit shora dolů do Visual PDF. PDF webových stránek se zpracují bez vymýšlení chybějícího obsahu; Interactive PDF upřednostňuje existující text, rozvržení, obrázky a ověřené odkazy." },
      { heading: "5. Získejte vhodný návod a ověřte výsledek", body: "Pokud přímý převod není dostupný nebo je neúplný, aplikace poskytne postup pro konkrétní stránku, prohlížeč nebo nativní export. Zkontrolujte chybějící či oříznutý obsah, prázdná místa, čitelnost, pořadí, rozvržení, odkazy a věrnost režimu." },
    ],
    externalLinkKey: "page2pdfGpt",
    primaryLabel: "Otevřít GPT Webpage 2 PDF",
    articleLinks: [{ slug: "save-webpage-as-pdf", label: "Uložit webovou stránku jako PDF" }, { slug: "long-webpage-page-breaks", label: "Opravit zalomení dlouhých stránek" }],
    relatedRoutes: gptRoutes,
    workflowOverride: {
      detailsTitle: "Návod k použití",
      firstStageDescription: "Zadejte aplikaci GPT funkční URL.",
      firstStageLabel: "Odešlete adresy URL",
    },
  },
  "web2pdf-gpt": {
    route: "web2pdf-gpt",
    eyebrow: "Aplikace GPT · dostupné webové stránky",
    title: "Převeďte stránky webu do samostatných PDF pomocí Web 2 PDF",
    description: "Web 2 PDF najde dostupné veřejné stránky webu, nechá vás potvrdit výběr a vrátí samostatný soubor PDF pro každou převedenou stránku.",
    lead: "Zadejte aplikaci Web 2 PDF veřejnou adresu. Může najít dostupné stránky, převést vybrané URL a vrátit více odkazů ke stažení, jeden pro každou stránku.",
    sections: [
      { heading: "1. Zadejte web", body: "Odešlete počáteční veřejnou URL. Aplikace najde dostupné stránky a před konverzí zobrazí zvolený rozsah." },
      { heading: "2. Zkontrolujte seznam stránek", body: "Potvrďte, které dostupné stránky patří do požadavku. Přihlášené stránky, blokované URL a externí domény jsou vyloučeny." },
      { heading: "3. Stáhněte samostatná PDF", body: "Každá převedená stránka je dodána jako nezávislé PDF. Web 2 PDF neslibuje sloučený dokument webu ani dataset pro scraping." },
    ],
    externalLinkKey: "web2pdfGpt",
    primaryLabel: "Otevřít aplikaci GPT Web 2 PDF",
    articleLinks: [{ slug: "multi-page-website-to-pdf", label: "Převést vícestránkový web do PDF" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typy webů vhodné k exportu" }],
    relatedRoutes: gptRoutes,
  },
  "html2pdf-gpt": {
    route: "html2pdf-gpt",
    eyebrow: "Aplikace GPT · nahraný soubor HTML",
    title: "HTML to PDF Converter — Web2File",
    displayTitle: "GPT: HTML 2 PDF",
    description: "HTML to PDF Converter — Web2File převede jeden nahraný soubor HTML do ověřeného PDF a zachová rozvržení, obrázky, text i odkazy.",
    lead: "Nahrajte právě jeden soubor HTML. GPT HTML 2 PDF zobrazí náhled vzhledu, načte dostupné styly, písma a obrázky a vytvoří ověřené PDF s označitelným textem a klikacími odkazy, pokud je to možné.",
    sections: [
      { heading: "1. Nahrajte právě jeden soubor HTML", body: "Přiložte jediný dokument HTML. Aplikace GPT místo něj nepřijímá URL, nezpracovává více souborů HTML, neprochází weby, nenásleduje odkazy na další stránky a neslučuje dokumenty." },
      { heading: "2. Zahrňte styly a zdroje", body: "Vložené styly se automaticky použijí spolu s dostupnými vzdálenými styly, písmy a obrázky. Pokud HTML odkazuje na chybějící místní soubor CSS, nahrajte odpovídající soubor pro věrnější výsledek nebo pokračujte bez něj." },
      { heading: "3. Zkontrolujte náhled a zachovejte vzhled", body: "Před převodem se HTML zobrazí v náhledu s vhodnou šířkou plochy. PDF se snaží zachovat motiv, barvy, typografii, mezery, sloupce, karty, obrázky a pořadí obsahu bez aktivace interaktivních ovládacích prvků." },
      { heading: "4. Vytvořte jedno čitelné PDF", body: "Aplikace GPT vytvoří jedno PDF s označitelným textem a funkčními odkazy, pokud je to možné. Široká rozvržení mohou použít orientaci na šířku nebo vhodný formát, aby se důležité prvky nestlačily, neořízly ani nerozdělily." },
      { heading: "5. Zkontrolujte hotový soubor", body: "Každé PDF se před předáním kontroluje na chybějící obsah, oříznuté prvky, nevysvětlené prázdné plochy, čitelnost, zalomení stránek, umístění obrázků a podporované odkazy." },
    ],
    externalLinkKey: "html2pdfGpt",
    primaryLabel: "Otevřít GPT HTML 2 PDF",
    articleLinks: [{ slug: "html-to-pdf-safely", label: "Bezpečně převést HTML do PDF" }, { slug: "webpage-capture-vs-web-scraping", label: "Zachycení stránky versus web scraping" }],
    relatedRoutes: gptRoutes,
    workflowOverride: {
      detailsTitle: "Pět kroků od HTML k PDF",
      firstStageDescription: "Předejte aplikaci GPT jeden soubor HTML.",
      firstStageLabel: "Nahrát HTML",
    },
  },
  "one-page2powerpoint-gpt": {
    route: "one-page2powerpoint-gpt",
    eyebrow: "Aplikace GPT · jedna veřejná URL",
    title: "Převeďte URL do PPTX pomocí One Page 2 PowerPoint",
    description: "One Page 2 PowerPoint je specializovaná aplikace GPT, která převede veřejnou URL a vrátí prezentaci PPTX dané stránky.",
    lead: "Zadejte aplikaci veřejnou URL s HTTPS. One Page 2 PowerPoint odešle stránku ke konverzi a vrátí prezentaci PPTX ke stažení.",
    sections: [
      { heading: "1. Odešlete veřejnou URL", body: "Vložte přesnou adresu stránky. Aplikace zpracuje jednu stránku na požadavek a neprochází zbytek webu." },
      { heading: "2. Získejte PPTX", body: "Stránka se rozloží do prezentace a dodá jako soubor PowerPointu. Zkontrolujte hranice snímků a vizuální či upravitelné náhrady." },
      { heading: "3. Soukromé karty ponechte v Chromu", body: "Aplikace GPT pro veřejné URL nemůže převzít relaci prohlížeče. Pokud je zdroj otevřený po přihlášení, použijte rozšíření Page 2 File." },
    ],
    externalLinkKey: "onePage2PowerpointGpt",
    primaryLabel: "Otevřít One Page 2 PowerPoint",
    articleLinks: [{ slug: "webpage-to-powerpoint", label: "Převést webovou stránku do PowerPointu" }, { slug: "sections-to-slides", label: "Převést části stránky na snímky" }],
    relatedRoutes: gptRoutes,
  },
  "web2powerpoint-gpt": {
    route: "web2powerpoint-gpt",
    eyebrow: "Aplikace GPT · dostupné webové stránky",
    title: "Převeďte stránky webu do PPTX pomocí Web 2 PowerPoint",
    description: "Web 2 PowerPoint najde dostupné stránky, převede vybrané a vrátí samostatné PPTX pro každou stránku.",
    lead: "Zadejte aplikaci Web 2 PowerPoint veřejnou adresu. Najde dostupné stránky, převede vybrané URL a vrátí více odkazů na prezentace.",
    sections: [
      { heading: "1. Zadejte web", body: "Odešlete počáteční veřejnou URL a jasně určete rozsah webu. Externí domény a soukromé stránky nejsou tiše zahrnuty." },
      { heading: "2. Potvrďte dostupné stránky", body: "Před konverzí zkontrolujte nalezený seznam. Do Page 2 File se odešlou pouze vybrané a dostupné stránky." },
      { heading: "3. Stáhněte samostatné soubory PPTX", body: "Každá převedená stránka je dodána jako nezávislá prezentace. Aplikace neslibuje jednu sloučenou prezentaci celého webu." },
    ],
    externalLinkKey: "web2powerpointGpt",
    primaryLabel: "Otevřít Web 2 PowerPoint",
    articleLinks: [{ slug: "website-to-powerpoint", label: "Převést web do PowerPointu" }, { slug: "screenshot-vs-editable-powerpoint", label: "Snímky jako obrázky nebo upravitelné" }],
    relatedRoutes: gptRoutes,
  },
  "export-ai-chat-to-pdf": {
    route: "export-ai-chat-to-pdf",
    eyebrow: "Export AI chatů",
    title: "Exportujte konverzaci z aktivní karty",
    description: "Exportujte podporované konverzace ChatGPT, Claude, Gemini a Grok do PDF s rozšířením, dočasným náhledem a bez historie konverzí.",
    lead: "Zvolte původní vzhled nebo jednoduchý dokument ke čtení. Rozšíření exportuje chat přímo z aktivní karty prohlížeče.",
    sections: [
      { heading: "Podporovaná chatovací rozhraní", body: "Page 2 File podporuje ChatGPT, Claude, Gemini a Grok a nabízí opatrný záložní režim pro další chaty v prohlížeči.", points: ["ChatGPT", "Claude", "Gemini", "Grok"] },
      { heading: "Původní vzhled", body: "Zachová se seskupení zpráv, bloky kódu, tabulky a viditelné odkazy na zdroje." },
      { heading: "Přehledný dokument", body: "Podporovaný text se upraví do klidnějšího dokumentu se zachováním autorů a cílů odkazů." },
      { heading: "Nezávislý produkt", body: "Page 2 File není přidružen, podporován ani provozován žádnou z podporovaných AI platforem." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Nainstalovat rozšíření",
    articleLinks: [{ slug: "export-ai-chats-privately", label: "Exportovat AI chaty soukromě" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typy webů vhodné k exportu" }],
    relatedRoutes: chatRoutes,
  },
  "export-chatgpt-to-pdf": {
    route: "export-chatgpt-to-pdf",
    eyebrow: "Export ChatGPT",
    title: "Exportujte dlouhé konverzace ChatGPT do PDF",
    description: "Exportujte viditelné zprávy ChatGPT, kód, tabulky, odkazy a dlouhé konverzace z aktivní karty do zkontrolovaného PDF.",
    lead: "Zachyťte konverzaci viditelnou v aktivní kartě, zkontrolujte zalomení stránek a stáhněte soubor bez účtu Page 2 File.",
    sections: [
      { heading: "Co se zachová", body: "Zprávy, pořadí účastníků, kód, tabulky a viditelné odkazy se zobrazí v náhledu." },
      { heading: "Dva styly čtení", body: "Zachovejte původní vizuální rytmus nebo zvolte klidnější dokument pro čtení a tisk." },
      { heading: "Omezení platformy", body: "Sbalené větve, nenačtené zprávy a obsah, který prohlížeč ještě nenačetl může být nutné před zachycením otevřít nebo načíst." },
      { heading: "Bez oficiálního vztahu", body: "Page 2 File je nezávislý nástroj a není podporován ani provozován společností OpenAI nebo ChatGPT." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Nainstalovat pro ChatGPT",
    articleLinks: [{ slug: "export-chatgpt-conversation-to-pdf", label: "Exportovat konverzaci ChatGPT do PDF" }, { slug: "export-ai-chats-privately", label: "Chránit data náhledu AI chatů" }],
    relatedRoutes: chatRoutes,
  },
  "export-claude-to-pdf": {
    route: "export-claude-to-pdf",
    eyebrow: "Export Claude",
    title: "Uložte konverzace Claude a viditelné artefakty",
    description: "Exportujte konverzace Claude, Markdown, kód, citace a viditelný kontext artefaktů z aktivní karty do zkontrolovaného PDF.",
    lead: "Po výslovném kliknutí rozšíření přečte aktivní konverzaci a vytvoří dočasný náhled pro kontrolu dlouhých odpovědí.",
    sections: [
      { heading: "Dlouhé odpovědi zachovají strukturu", body: "Nadpisy, seznamy, citace a kód zůstávají ve správném pořadí čtení." },
      { heading: "Kontext artefaktů", body: "Viditelné názvy a dostupný obsah artefaktů lze zobrazit bez tvrzení o skrytém přístupu." },
      { heading: "Bez oficiálního vztahu", body: "Page 2 File je nezávislý nástroj a není podporován společností Anthropic." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Nainstalovat pro Claude",
    articleLinks: [{ slug: "export-claude-chat-to-pdf", label: "Exportovat chat Claude do PDF" }, { slug: "export-ai-chats-privately", label: "Chránit data náhledu AI chatů" }],
    relatedRoutes: chatRoutes,
  },
  "export-gemini-to-pdf": {
    route: "export-gemini-to-pdf",
    eyebrow: "Export Gemini",
    title: "Převeďte konverzaci Gemini do čitelného PDF",
    description: "Exportujte viditelné zprávy Gemini, karty zdrojů, kód a citace z aktivní karty do zkontrolovaného PDF s dočasným náhledem.",
    lead: "Před vytvořením přehledného nebo vizuálně věrného dokumentu zkontrolujte, jak se zobrazují karty zdrojů a viditelné obrázky.",
    sections: [
      { heading: "Zdroje zůstávají užitečné", body: "Viditelné citace a odkazy zůstávají klikatelné, pokud jsou jejich cíle bezpečné." },
      { heading: "Obrázky závisejí na načtené stránce", body: "V dočasném náhledu se mohou zobrazit pouze média dostupná aktivní stránce." },
      { heading: "Bez oficiálního vztahu", body: "Page 2 File je nezávislý a není produktem společnosti Google ani Gemini." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Nainstalovat pro Gemini",
    articleLinks: [{ slug: "export-gemini-chat-to-pdf", label: "Exportovat chat Gemini do PDF" }, { slug: "export-ai-chats-privately", label: "Chránit data náhledu AI chatů" }],
    relatedRoutes: chatRoutes,
  },
  "export-grok-to-pdf": {
    route: "export-grok-to-pdf",
    eyebrow: "Export Grok",
    title: "Exportujte konverzace Grok s viditelnými zdroji",
    description: "Exportujte viditelné konverzace Grok, odkazy X, citované příspěvky a zdroje z aktivní karty do zkontrolovaného PDF.",
    lead: "Zachyťte aktivní konverzaci, zachovejte viditelný kontext zdrojů a zvolte vizuální náhled nebo přehledný dokument ke čtení.",
    sections: [
      { heading: "Pořadí odpovídající konverzaci", body: "Zprávy a kontext citovaných příspěvků zůstanou seskupené místo jednoho neoznačeného proudu textu." },
      { heading: "Viditelné odkazy X", body: "URL příspěvků a zdroje zůstanou klikatelné, pokud projdou bezpečnostní kontrolou." },
      { heading: "Bez oficiálního vztahu", body: "Page 2 File je nezávislý produkt a není podporován společností xAI ani X." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Nainstalovat pro Grok",
    articleLinks: [{ slug: "export-other-ai-chats-to-pdf", label: "Exportovat jiné AI chaty do PDF" }, { slug: "export-ai-chats-privately", label: "Chránit data náhledu AI chatů" }],
    relatedRoutes: chatRoutes,
  },
};
