import type { LandingContent, RelatedRoute } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

const gptRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "page2pdf-gpt", label: "One Page 2 PDF" },
  { route: "web2pdf-gpt", label: "Web 2 PDF" },
  { route: "html2pdf-gpt", label: "HTML 2 PDF" },
  { route: "one-page2powerpoint-gpt", label: "One Page 2 PowerPoint" },
  { route: "web2powerpoint-gpt", label: "Web 2 PowerPoint" },
];
const chatRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "export-ai-chat-to-pdf", label: "Všechny exporty AI chatů" },
  { route: "export-chatgpt-to-pdf", label: "ChatGPT do PDF" },
  { route: "export-claude-to-pdf", label: "Claude do PDF" },
  { route: "export-gemini-to-pdf", label: "Gemini do PDF" },
  { route: "export-grok-to-pdf", label: "Grok do PDF" },
];

export const czechLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  "page2pdf-gpt": {
    route: "page2pdf-gpt",
    eyebrow: "Aplikace GPT · jedna veřejná URL",
    title: "Převeďte veřejnou URL do PDF pomocí One Page 2 PDF",
    description: "One Page 2 PDF je specializovaná aplikace GPT, která odešle veřejnou URL ke konverzi a vrátí PDF této jediné stránky.",
    lead: "Zadejte aplikaci GPT veřejnou URL s HTTPS. One Page 2 PDF odešle adresu službě Page 2 File a vrátí PDF požadované stránky ke stažení.",
    sections: [
      { heading: "1. Odešlete veřejnou URL", body: "Vložte přesnou adresu HTTPS stránky, kterou chcete převést. Požadavek zahrnuje jednu stránku a nespouští procházení celého webu." },
      { heading: "2. Získejte PDF", body: "Aplikace GPT vrátí odkaz na PDF dané stránky. Před použitím zkontrolujte text, odkazy, obrázky a zalomení stránek." },
      { heading: "3. Dodržte správný rozsah", body: "One Page 2 PDF neotevírá přihlášené karty ani neobchází řízení přístupu. Pro stránku otevřenou po přihlášení použijte rozšíření Page 2 File." },
    ],
    externalLinkKey: "page2pdfGpt",
    primaryLabel: "Otevřít aplikaci GPT One Page 2 PDF",
    articleLinks: [{ slug: "save-webpage-as-pdf", label: "Uložit webovou stránku jako PDF" }, { slug: "long-webpage-page-breaks", label: "Opravit zalomení dlouhých stránek" }],
    relatedRoutes: gptRoutes,
  },
  "web2pdf-gpt": {
    route: "web2pdf-gpt",
    eyebrow: "Aplikace GPT · dostupné webové stránky",
    title: "Převeďte stránky webu do samostatných PDF pomocí Web 2 PDF",
    description: "Web 2 PDF najde dostupné stránky webu, převede vybrané a vrátí samostatné PDF pro každou stránku.",
    lead: "Zadejte aplikaci Web 2 PDF veřejnou adresu. Může najít dostupné stránky, převést vybrané URL a vrátit více odkazů ke stažení, jeden pro každou stránku.",
    sections: [
      { heading: "1. Zadejte web", body: "Odešlete počáteční veřejnou URL. Aplikace najde dostupné stránky a před konverzí zobrazí zvolený rozsah." },
      { heading: "2. Zkontrolujte seznam stránek", body: "Potvrďte, které dostupné stránky patří do požadavku. Přihlášené stránky, blokované URL a externí domény jsou vyloučeny." },
      { heading: "3. Stáhněte samostatná PDF", body: "Každá převedená stránka je dodána jako nezávislé PDF. Web 2 PDF neslibuje sloučený dokument webu ani dataset pro scraping." },
    ],
    externalLinkKey: "web2pdfGpt",
    primaryLabel: "Otevřít aplikaci GPT Web 2 PDF",
    articleLinks: [{ slug: "multi-page-website-to-pdf", label: "Převést vícestránkový web do PDF" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typy webů vhodné k exportu" }],
    relatedRoutes: gptRoutes,
  },
  "html2pdf-gpt": {
    route: "html2pdf-gpt",
    eyebrow: "Aplikace GPT · nahraný soubor HTML",
    title: "Převeďte nahraný soubor HTML pomocí HTML 2 PDF",
    description: "HTML 2 PDF přijme nahraný soubor HTML a vrátí přehledné PDF v rámci viditelných limitů vykreslení.",
    lead: "Nahrajte soubor HTML do aplikace GPT. HTML 2 PDF jej vykreslí izolovaně a vrátí PDF; tento postup pro zdrojový soubor je dostupný pouze v aplikaci.",
    sections: [
      { heading: "1. Nahrajte soubor HTML", body: "Přidejte dokument HTML, který smíte zpracovat. Tento postup začíná souborem, nikoli veřejnou URL webové stránky." },
      { heading: "2. Převeďte jej do PDF", body: "Aplikace vrátí PDF nahraného dokumentu. Externí zdroje, skripty, vlastní písma a funkce prohlížeče se mohou lišit." },
      { heading: "3. Považujte HTML za nedůvěryhodný vstup", body: "Bezpečné vykreslení vyžaduje izolaci privátních sítí, místních souborů a nekontrolovaných skriptů. Výsledkem je konverze dokumentu, nikoli hostované spuštění webu." },
    ],
    externalLinkKey: "html2pdfGpt",
    primaryLabel: "Otevřít aplikaci GPT HTML 2 PDF",
    articleLinks: [{ slug: "html-to-pdf-safely", label: "Bezpečně převést HTML do PDF" }, { slug: "webpage-capture-vs-web-scraping", label: "Zachycení stránky versus web scraping" }],
    relatedRoutes: gptRoutes,
  },
  "one-page2powerpoint-gpt": {
    route: "one-page2powerpoint-gpt",
    eyebrow: "Aplikace GPT · jedna veřejná URL",
    title: "Převeďte URL do PPTX pomocí One Page 2 PowerPoint",
    description: "One Page 2 PowerPoint je specializovaná aplikace GPT, která převede veřejnou URL a vrátí prezentaci PPTX dané stránky.",
    lead: "Zadejte aplikaci veřejnou URL s HTTPS. One Page 2 PowerPoint odešle stránku ke konverzi a vrátí prezentaci PPTX ke stažení.",
    sections: [
      { heading: "1. Odešlete veřejnou URL", body: "Vložte přesnou adresu stránky. Aplikace zpracuje jednu stránku na požadavek a neprochází zbytek webu." },
      { heading: "2. Získejte PPTX", body: "Stránka se rozloží do prezentace a dodá jako soubor PowerPointu. Zkontrolujte hranice snímků a vizuální či upravitelné náhrady." },
      { heading: "3. Soukromé karty ponechte v Chromu", body: "Aplikace GPT pro veřejné URL nemůže převzít relaci prohlížeče. Pokud je zdroj otevřený po přihlášení, použijte rozšíření Page 2 File." },
    ],
    externalLinkKey: "onePage2PowerpointGpt",
    primaryLabel: "Otevřít One Page 2 PowerPoint",
    articleLinks: [{ slug: "webpage-to-powerpoint", label: "Převést webovou stránku do PowerPointu" }, { slug: "sections-to-slides", label: "Převést části stránky na snímky" }],
    relatedRoutes: gptRoutes,
  },
  "web2powerpoint-gpt": {
    route: "web2powerpoint-gpt",
    eyebrow: "Aplikace GPT · dostupné webové stránky",
    title: "Převeďte stránky webu do PPTX pomocí Web 2 PowerPoint",
    description: "Web 2 PowerPoint najde dostupné stránky, převede vybrané a vrátí samostatné PPTX pro každou stránku.",
    lead: "Zadejte aplikaci Web 2 PowerPoint veřejnou adresu. Najde dostupné stránky, převede vybrané URL a vrátí více odkazů na prezentace.",
    sections: [
      { heading: "1. Zadejte web", body: "Odešlete počáteční veřejnou URL a jasně určete rozsah webu. Externí domény a soukromé stránky nejsou tiše zahrnuty." },
      { heading: "2. Potvrďte dostupné stránky", body: "Před konverzí zkontrolujte nalezený seznam. Do Page 2 File se odešlou pouze vybrané a dostupné stránky." },
      { heading: "3. Stáhněte samostatné soubory PPTX", body: "Každá převedená stránka je dodána jako nezávislá prezentace. Aplikace neslibuje jednu sloučenou prezentaci celého webu." },
    ],
    externalLinkKey: "web2powerpointGpt",
    primaryLabel: "Otevřít Web 2 PowerPoint",
    articleLinks: [{ slug: "website-to-powerpoint", label: "Převést web do PowerPointu" }, { slug: "screenshot-vs-editable-powerpoint", label: "Snímky jako obrázky nebo upravitelné" }],
    relatedRoutes: gptRoutes,
  },
  "export-ai-chat-to-pdf": {
    route: "export-ai-chat-to-pdf",
    eyebrow: "Export AI chatů",
    title: "Exportujte konverzaci z aktivní karty",
    description: "Exportujte podporované konverzace ChatGPT, Claude, Gemini a Grok do PDF s rozšířením, dočasným náhledem a bez historie konverzí.",
    lead: "Zvolte původní vzhled nebo jednoduchý dokument ke čtení. Rozšíření exportuje chat přímo z aktivní karty prohlížeče.",
    sections: [
      { heading: "Podporovaná chatovací rozhraní", body: "Page 2 File podporuje ChatGPT, Claude, Gemini a Grok a nabízí opatrný záložní režim pro další chaty v prohlížeči.", points: ["ChatGPT", "Claude", "Gemini", "Grok"] },
      { heading: "Původní vzhled", body: "Zachová se seskupení zpráv, bloky kódu, tabulky a viditelné odkazy na zdroje." },
      { heading: "Přehledný dokument", body: "Podporovaný text se upraví do klidnějšího dokumentu se zachováním autorů a cílů odkazů." },
      { heading: "Nezávislý produkt", body: "Page 2 File není přidružen, podporován ani provozován žádnou z podporovaných AI platforem." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Nainstalovat rozšíření",
    articleLinks: [{ slug: "export-ai-chats-privately", label: "Exportovat AI chaty soukromě" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typy webů vhodné k exportu" }],
    relatedRoutes: chatRoutes,
  },
  "export-chatgpt-to-pdf": {
    route: "export-chatgpt-to-pdf",
    eyebrow: "Export ChatGPT",
    title: "Exportujte dlouhé konverzace ChatGPT do PDF",
    description: "Exportujte viditelné zprávy ChatGPT, kód, tabulky, odkazy a dlouhé konverzace z aktivní karty do zkontrolovaného PDF.",
    lead: "Zachyťte konverzaci viditelnou v aktivní kartě, zkontrolujte zalomení stránek a stáhněte soubor bez účtu Page 2 File.",
    sections: [
      { heading: "Co se zachová", body: "Zprávy, pořadí účastníků, kód, tabulky a viditelné odkazy se zobrazí v náhledu." },
      { heading: "Dva styly čtení", body: "Zachovejte původní vizuální rytmus nebo zvolte klidnější dokument pro čtení a tisk." },
      { heading: "Omezení platformy", body: "Sbalené větve, nenačtené zprávy a obsah mimo DOM může být nutné před zachycením otevřít nebo načíst." },
      { heading: "Bez oficiálního vztahu", body: "Page 2 File je nezávislý nástroj a není podporován ani provozován společností OpenAI nebo ChatGPT." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Nainstalovat pro ChatGPT",
    articleLinks: [{ slug: "export-chatgpt-conversation-to-pdf", label: "Exportovat konverzaci ChatGPT do PDF" }, { slug: "export-ai-chats-privately", label: "Chránit data náhledu AI chatů" }],
    relatedRoutes: chatRoutes,
  },
  "export-claude-to-pdf": {
    route: "export-claude-to-pdf",
    eyebrow: "Export Claude",
    title: "Uložte konverzace Claude a viditelné artefakty",
    description: "Exportujte konverzace Claude, Markdown, kód, citace a viditelný kontext artefaktů z aktivní karty do zkontrolovaného PDF.",
    lead: "Po výslovném kliknutí rozšíření přečte aktivní konverzaci a vytvoří dočasný náhled pro kontrolu dlouhých odpovědí.",
    sections: [
      { heading: "Dlouhé odpovědi zachovají strukturu", body: "Nadpisy, seznamy, citace a kód zůstávají ve správném pořadí čtení." },
      { heading: "Kontext artefaktů", body: "Viditelné názvy a dostupný obsah artefaktů lze zobrazit bez tvrzení o skrytém přístupu." },
      { heading: "Bez oficiálního vztahu", body: "Page 2 File je nezávislý nástroj a není podporován společností Anthropic." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Nainstalovat pro Claude",
    articleLinks: [{ slug: "export-claude-chat-to-pdf", label: "Exportovat chat Claude do PDF" }, { slug: "export-ai-chats-privately", label: "Chránit data náhledu AI chatů" }],
    relatedRoutes: chatRoutes,
  },
  "export-gemini-to-pdf": {
    route: "export-gemini-to-pdf",
    eyebrow: "Export Gemini",
    title: "Převeďte konverzaci Gemini do čitelného PDF",
    description: "Exportujte viditelné zprávy Gemini, karty zdrojů, kód a citace z aktivní karty do zkontrolovaného PDF s dočasným náhledem.",
    lead: "Před vytvořením přehledného nebo vizuálně věrného dokumentu zkontrolujte, jak se zobrazují karty zdrojů a viditelné obrázky.",
    sections: [
      { heading: "Zdroje zůstávají užitečné", body: "Viditelné citace a odkazy zůstávají klikatelné, pokud jsou jejich cíle bezpečné." },
      { heading: "Obrázky se řídí DOM", body: "V dočasném náhledu se mohou zobrazit pouze média dostupná aktivní stránce." },
      { heading: "Bez oficiálního vztahu", body: "Page 2 File je nezávislý a není produktem společnosti Google ani Gemini." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Nainstalovat pro Gemini",
    articleLinks: [{ slug: "export-gemini-chat-to-pdf", label: "Exportovat chat Gemini do PDF" }, { slug: "export-ai-chats-privately", label: "Chránit data náhledu AI chatů" }],
    relatedRoutes: chatRoutes,
  },
  "export-grok-to-pdf": {
    route: "export-grok-to-pdf",
    eyebrow: "Export Grok",
    title: "Exportujte konverzace Grok s viditelnými zdroji",
    description: "Exportujte viditelné konverzace Grok, odkazy X, citované příspěvky a zdroje z aktivní karty do zkontrolovaného PDF.",
    lead: "Zachyťte aktivní konverzaci, zachovejte viditelný kontext zdrojů a zvolte vizuální náhled nebo přehledný dokument ke čtení.",
    sections: [
      { heading: "Pořadí odpovídající konverzaci", body: "Zprávy a kontext citovaných příspěvků zůstanou seskupené místo jednoho neoznačeného proudu textu." },
      { heading: "Viditelné odkazy X", body: "URL příspěvků a zdroje zůstanou klikatelné, pokud projdou bezpečnostní kontrolou." },
      { heading: "Bez oficiálního vztahu", body: "Page 2 File je nezávislý produkt a není podporován společností xAI ani X." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Nainstalovat pro Grok",
    articleLinks: [{ slug: "export-other-ai-chats-to-pdf", label: "Exportovat jiné AI chaty do PDF" }, { slug: "export-ai-chats-privately", label: "Chránit data náhledu AI chatů" }],
    relatedRoutes: chatRoutes,
  },
};
