import type { LandingContent, RelatedRoute } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

const gptRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "page2pdf-gpt", label: "Webpage to PDF Converter — Web2File" },
  { route: "web2pdf-gpt", label: "Web 2 PDF" },
  { route: "html2pdf-gpt", label: "HTML 2 PDF" },
  { route: "one-page2powerpoint-gpt", label: "One Page 2 PowerPoint" },
  { route: "web2powerpoint-gpt", label: "Web 2 PowerPoint" },
];
const chatRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "export-ai-chat-to-pdf", label: "Alle AI-chateksporter" },
  { route: "export-chatgpt-to-pdf", label: "ChatGPT til PDF" },
  { route: "export-claude-to-pdf", label: "Claude til PDF" },
  { route: "export-gemini-to-pdf", label: "Gemini til PDF" },
  { route: "export-grok-to-pdf", label: "Grok til PDF" },
];

export const danishLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  "page2pdf-gpt": {
    route: "page2pdf-gpt",
    eyebrow: "GPT-app · nøjagtige URL'er, PDF'er eller skærmbilleder",
    title: "Webpage to PDF Converter — Web2File",
    displayTitle: "GPT: Webpage 2 PDF",
    description: "Webpage to PDF Converter — Web2File behandler nøjagtige offentlige adresser, webside-PDF'er og skærmbilleder som Visual PDF eller Interactive PDF.",
    lead: "Angiv en nøjagtig offentlig URL, en liste med nøjagtige URL'er, en webside-PDF eller helsides eller sammenhængende skærmbilleder. Vælg Visual PDF for at gemme webstedet som skærmbilleder eller Interactive PDF for markerbar tekst og klikbare links.",
    sections: [
      { heading: "1. Angiv en eller flere URL'er", body: "Send en offentlig URL, en liste med nøjagtige offentlige URL'er, en eksisterende webside-PDF eller helsides eller sammenhængende skærmbilleder. Hver webside forbliver en separat PDF." },
      { heading: "2. Vælg PDF-type", body: "Vælg Visual PDF for et billedbaseret resultat, der prioriterer sidens udseende, eller Interactive PDF, når markerbar tekst og klikbare links er vigtigst. Én tilstand gælder for hele URL-listen." },
      { heading: "3. Konvertér kun angivne sider", body: "Appen åbner kun de nøjagtige offentlige URL'er. Den gennemgår ikke domæner eller sitemaps, finder ikke sider, følger ikke interne links og omgår ikke login, betalingsmure, CAPTCHA, geografiske eller andre adgangsbegrænsninger. Brug Web2File: Website 2 PDF til hele webstedet." },
      { heading: "4. Behandl PDF'er og skærmbilleder", body: "Uploadede skærmbilleder kan samles oppefra og ned i en Visual PDF. Webside-PDF'er behandles uden at opfinde manglende indhold; Interactive PDF prioriterer eksisterende tekst, layout, billeder og verificerede links." },
      { heading: "5. Få tilpasset hjælp og kontrollér resultatet", body: "Hvis direkte konvertering er utilgængelig eller ufuldstændig, giver appen trin til siden, browseren eller den indbyggede eksport. Kontrollér manglende eller beskåret indhold, tomme områder, læsbarhed, rækkefølge, layout, links og overensstemmelse med tilstanden." },
    ],
    externalLinkKey: "page2pdfGpt",
    primaryLabel: "Åbn GPT Webpage 2 PDF",
    articleLinks: [{ slug: "save-webpage-as-pdf", label: "Gem en webside som PDF" }, { slug: "long-webpage-page-breaks", label: "Ret sideskift på lange websider" }],
    relatedRoutes: gptRoutes,
    workflowOverride: {
      detailsTitle: "Brugsanvisning",
      firstStageDescription: "Giv GPT-appen en fungerende URL.",
      firstStageLabel: "Send URL'er",
    },
  },
  "web2pdf-gpt": {
    route: "web2pdf-gpt",
    eyebrow: "GPT-app · tilgængelige websider",
    title: "Konvertér webstedssider til separate PDF-filer med Web 2 PDF",
    description: "Web 2 PDF finder tilgængelige sider på et websted, konverterer de valgte og returnerer en separat PDF for hver side.",
    lead: "Giv Web 2 PDF en offentlig adresse. Appen kan finde tilgængelige sider, konvertere valgte URL'er og returnere flere downloadlinks — ét pr. side.",
    sections: [
      { heading: "1. Angiv webstedet", body: "Send den første offentlige URL. Appen finder tilgængelige sider og viser det valgte omfang før konverteringen." },
      { heading: "2. Kontrollér sidelisten", body: "Bekræft, hvilke tilgængelige sider der hører til anmodningen. Sider med login, blokerede URL'er og eksterne domæner udelades." },
      { heading: "3. Download separate PDF-filer", body: "Hver konverteret side leveres som sin egen PDF. Web 2 PDF lover ikke ét samlet webstedsdokument eller et datasæt til scraping." },
    ],
    externalLinkKey: "web2pdfGpt",
    primaryLabel: "Åbn GPT-appen Web 2 PDF",
    articleLinks: [{ slug: "multi-page-website-to-pdf", label: "Konvertér et websted med flere sider til PDF" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typer af websteder, der kan eksporteres" }],
    relatedRoutes: gptRoutes,
  },
  "html2pdf-gpt": {
    route: "html2pdf-gpt",
    eyebrow: "GPT-app · uploadet HTML-fil",
    title: "HTML to PDF Converter — Web2File",
    displayTitle: "GPT: HTML 2 PDF",
    description: "HTML to PDF Converter — Web2File omdanner én uploadet HTML-fil til en kontrolleret PDF og bevarer layout, billeder, tekst og links.",
    lead: "Upload præcis én HTML-fil. GPT HTML 2 PDF forhåndsviser designet, indlæser tilgængelige typografier, skrifttyper og billeder og opretter en kontrolleret PDF med markerbar tekst og klikbare links, hvor det er muligt.",
    sections: [
      { heading: "1. Upload præcis én HTML-fil", body: "Vedhæft ét HTML-dokument. GPT-appen accepterer ikke en URL i stedet, behandler ikke flere HTML-filer, gennemgår ikke websteder, følger ikke links til ekstra sider og fletter ikke dokumenter." },
      { heading: "2. Medtag typografier og ressourcer", body: "Inline og indlejrede typografier bruges automatisk sammen med tilgængelige eksterne stylesheets, skrifttyper og billeder. Hvis HTML-filen henviser til en manglende lokal CSS-fil, kan du uploade den matchende fil for et mere præcist resultat eller fortsætte uden den." },
      { heading: "3. Forhåndsvis og bevar designet", body: "HTML-filen forhåndsvises i en passende skrivebordsbredde før konvertering. PDF-filen forsøger at bevare tema, farver, typografi, afstande, kolonner, kort, billeder og indholdsrækkefølge uden at aktivere interaktive kontroller." },
      { heading: "4. Opret én læsbar PDF", body: "GPT-appen opretter én PDF med markerbar tekst og fungerende hyperlinks, hvor det er muligt. Brede layouts kan bruge liggende format eller en passende sidestørrelse, så vigtige elementer ikke klemmes, beskæres eller opdeles." },
      { heading: "5. Kontrollér den færdige fil", body: "Hver PDF kontrolleres før levering for manglende indhold, beskårne komponenter, uforklarlige tomme områder, læsbarhed, sideskift, billedplacering og understøttede links." },
    ],
    externalLinkKey: "html2pdfGpt",
    primaryLabel: "Åbn GPT HTML 2 PDF",
    articleLinks: [{ slug: "html-to-pdf-safely", label: "Konvertér HTML sikkert til PDF" }, { slug: "webpage-capture-vs-web-scraping", label: "Sideoptagelse sammenlignet med web scraping" }],
    relatedRoutes: gptRoutes,
    workflowOverride: {
      detailsTitle: "Fem trin fra HTML til PDF",
      firstStageDescription: "Giv GPT-appen én HTML-fil.",
      firstStageLabel: "Upload HTML",
    },
  },
  "one-page2powerpoint-gpt": {
    route: "one-page2powerpoint-gpt",
    eyebrow: "GPT-app · én offentlig URL",
    title: "Konvertér en URL til PPTX med One Page 2 PowerPoint",
    description: "One Page 2 PowerPoint er en fokuseret GPT-app, der konverterer én offentlig URL og returnerer én PPTX-præsentation af siden.",
    lead: "Giv appen én offentlig HTTPS-URL. One Page 2 PowerPoint sender siden til konvertering og returnerer en PPTX-præsentation, der kan downloades.",
    sections: [
      { heading: "1. Send en offentlig URL", body: "Indsæt sidens nøjagtige adresse. Appen behandler én side pr. anmodning og udforsker ikke resten af webstedet." },
      { heading: "2. Modtag én PPTX", body: "Siden organiseres i en præsentation og leveres som én PowerPoint-fil. Kontrollér diasgrænser og visuelle eller redigerbare erstatninger." },
      { heading: "3. Behold private faner i Chrome", body: "En GPT-app til offentlige URL'er kan ikke bruge din browsersession. Brug Page 2 File-udvidelsen, når kilden er åben efter login." },
    ],
    externalLinkKey: "onePage2PowerpointGpt",
    primaryLabel: "Åbn One Page 2 PowerPoint",
    articleLinks: [{ slug: "webpage-to-powerpoint", label: "Konvertér en webside til PowerPoint" }, { slug: "sections-to-slides", label: "Konvertér sideafsnit til dias" }],
    relatedRoutes: gptRoutes,
  },
  "web2powerpoint-gpt": {
    route: "web2powerpoint-gpt",
    eyebrow: "GPT-app · tilgængelige websider",
    title: "Konvertér webstedssider til PPTX med Web 2 PowerPoint",
    description: "Web 2 PowerPoint finder tilgængelige sider, konverterer de valgte og returnerer en separat PPTX for hver side.",
    lead: "Giv Web 2 PowerPoint en offentlig adresse. Appen finder tilgængelige sider, konverterer valgte URL'er og returnerer flere links til præsentationer.",
    sections: [
      { heading: "1. Angiv webstedet", body: "Send den første offentlige URL, og angiv webstedets omfang tydeligt. Eksterne domæner og private sider inkluderes ikke uden varsel." },
      { heading: "2. Bekræft tilgængelige sider", body: "Kontrollér den fundne liste før konverteringen. Kun valgte og tilgængelige sider sendes til Page 2 File." },
      { heading: "3. Download separate PPTX-filer", body: "Hver konverteret side leveres som sin egen præsentation. Appen lover ikke én samlet præsentation for hele webstedet." },
    ],
    externalLinkKey: "web2powerpointGpt",
    primaryLabel: "Åbn Web 2 PowerPoint",
    articleLinks: [{ slug: "website-to-powerpoint", label: "Konvertér et websted til PowerPoint" }, { slug: "screenshot-vs-editable-powerpoint", label: "Dias som billeder eller redigerbare elementer" }],
    relatedRoutes: gptRoutes,
  },
  "export-ai-chat-to-pdf": {
    route: "export-ai-chat-to-pdf",
    eyebrow: "Eksport af AI-chats",
    title: "Eksportér en samtale fra den aktive fane",
    description: "Eksportér understøttede samtaler fra ChatGPT, Claude, Gemini og Grok til PDF med udvidelsen, midlertidig forhåndsvisning og uden historik.",
    lead: "Vælg det oprindelige udseende eller et enkelt læsedokument. Udvidelsen eksporterer chatten direkte fra den aktive browserfane.",
    sections: [
      { heading: "Understøttede chatgrænseflader", body: "Page 2 File understøtter ChatGPT, Claude, Gemini og Grok samt en forsigtig reserve til andre browserchats.", points: ["ChatGPT", "Claude", "Gemini", "Grok"] },
      { heading: "Oprindeligt udseende", body: "Gruppering af beskeder, kodeblokke, tabeller og synlige kildelinks bevares." },
      { heading: "Overskueligt dokument", body: "Understøttet tekst tilpasses et roligere dokument med bevarede afsendere og linkmål." },
      { heading: "Uafhængigt produkt", body: "Page 2 File er ikke tilknyttet, godkendt eller drevet af nogen understøttet AI-platform." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installer udvidelsen",
    articleLinks: [{ slug: "export-ai-chats-privately", label: "Eksportér AI-chats privat" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typer af websteder, der kan eksporteres" }],
    relatedRoutes: chatRoutes,
  },
  "export-chatgpt-to-pdf": {
    route: "export-chatgpt-to-pdf",
    eyebrow: "Eksport fra ChatGPT",
    title: "Eksportér lange ChatGPT-samtaler til PDF",
    description: "Eksportér synlige ChatGPT-beskeder, kode, tabeller, links og lange samtaler fra den aktive fane til en gennemgået PDF.",
    lead: "Optag samtalen, der vises i den aktive fane, kontrollér sideskift, og download filen uden en Page 2 File-konto.",
    sections: [
      { heading: "Det bevares", body: "Beskeder, deltagerrækkefølge, kode, tabeller og synlige links vises i forhåndsvisningen." },
      { heading: "To læsestile", body: "Behold den oprindelige visuelle rytme, eller vælg et roligere dokument til læsning og udskrivning." },
      { heading: "Platformens begrænsninger", body: "Sammenfoldede grene, beskeder der ikke er indlæst, og indhold som browseren endnu ikke har indlæst kan kræve rulning eller åbning før optagelse." },
      { heading: "Ingen officiel tilknytning", body: "Page 2 File er et uafhængigt værktøj og er ikke godkendt eller drevet af OpenAI eller ChatGPT." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installer til ChatGPT",
    articleLinks: [{ slug: "export-chatgpt-conversation-to-pdf", label: "Eksportér en ChatGPT-samtale til PDF" }, { slug: "export-ai-chats-privately", label: "Beskyt data i AI-chatforhåndsvisningen" }],
    relatedRoutes: chatRoutes,
  },
  "export-claude-to-pdf": {
    route: "export-claude-to-pdf",
    eyebrow: "Eksport fra Claude",
    title: "Gem Claude-samtaler og synlige artifacts",
    description: "Eksportér Claude-samtaler, Markdown, kode, citater og synlig artifact-kontekst fra den aktive fane til en gennemgået PDF.",
    lead: "Efter et tydeligt klik læser udvidelsen den aktive samtale og opretter en midlertidig forhåndsvisning af lange svar.",
    sections: [
      { heading: "Lange svar bevarer strukturen", body: "Overskrifter, lister, citater og kode bevarer læserækkefølgen." },
      { heading: "Artifact-kontekst", body: "Synlige titler og tilgængeligt artifact-indhold kan gengives uden at påstå skjult adgang." },
      { heading: "Ingen officiel tilknytning", body: "Page 2 File er et uafhængigt værktøj og er ikke godkendt af Anthropic." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installer til Claude",
    articleLinks: [{ slug: "export-claude-chat-to-pdf", label: "Eksportér en Claude-chat til PDF" }, { slug: "export-ai-chats-privately", label: "Beskyt data i AI-chatforhåndsvisningen" }],
    relatedRoutes: chatRoutes,
  },
  "export-gemini-to-pdf": {
    route: "export-gemini-to-pdf",
    eyebrow: "Eksport fra Gemini",
    title: "Omdan en Gemini-samtale til en læsbar PDF",
    description: "Eksportér synlige Gemini-beskeder, kildekort, kode og citater fra den aktive fane til en gennemgået PDF med midlertidig forhåndsvisning.",
    lead: "Kontrollér, hvordan kildekort og synlige billeder vises, før du opretter et overskueligt eller visuelt nøjagtigt dokument.",
    sections: [
      { heading: "Kilderne forbliver nyttige", body: "Synlige citater og links forbliver klikbare, når målene er sikre." },
      { heading: "Billeder afhænger af den indlæste side", body: "Kun medier, der er tilgængelige for den aktive side, kan vises i den midlertidige forhåndsvisning." },
      { heading: "Ingen officiel tilknytning", body: "Page 2 File er uafhængigt og er ikke et produkt fra Google eller Gemini." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installer til Gemini",
    articleLinks: [{ slug: "export-gemini-chat-to-pdf", label: "Eksportér en Gemini-chat til PDF" }, { slug: "export-ai-chats-privately", label: "Beskyt data i AI-chatforhåndsvisningen" }],
    relatedRoutes: chatRoutes,
  },
  "export-grok-to-pdf": {
    route: "export-grok-to-pdf",
    eyebrow: "Eksport fra Grok",
    title: "Eksportér Grok-samtaler med synlige kilder",
    description: "Eksportér synlige Grok-samtaler, X-links, citerede opslag og kilder fra den aktive fane til en gennemgået PDF.",
    lead: "Optag den aktive samtale, bevar synlig kildekontekst, og vælg en visuel forhåndsvisning eller et overskueligt læsedokument.",
    sections: [
      { heading: "Læserækkefølge, der følger samtalen", body: "Beskeder og kontekst fra citerede opslag forbliver grupperet i stedet for at blive én umærket tekststrøm." },
      { heading: "Synlige X-links", body: "Opslags-URL'er og kilder forbliver klikbare, når de består sikkerhedskontrollen." },
      { heading: "Ingen officiel tilknytning", body: "Page 2 File er et uafhængigt produkt og er ikke godkendt af xAI eller X." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installer til Grok",
    articleLinks: [{ slug: "export-other-ai-chats-to-pdf", label: "Eksportér andre AI-chats til PDF" }, { slug: "export-ai-chats-privately", label: "Beskyt data i AI-chatforhåndsvisningen" }],
    relatedRoutes: chatRoutes,
  },
};
