import type { LandingContent, RelatedRoute } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

const gptRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "page2pdf-gpt", label: "One Page 2 PDF" },
  { route: "web2pdf-gpt", label: "Web 2 PDF" },
  { route: "html2pdf-gpt", label: "HTML 2 PDF" },
  { route: "one-page2powerpoint-gpt", label: "One Page 2 PowerPoint" },
  { route: "web2powerpoint-gpt", label: "Web 2 PowerPoint" },
];
const chatRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "export-ai-chat-to-pdf", label: "Kaikki AI-keskustelujen viennit" },
  { route: "export-chatgpt-to-pdf", label: "ChatGPT PDF-tiedostoksi" },
  { route: "export-claude-to-pdf", label: "Claude PDF-tiedostoksi" },
  { route: "export-gemini-to-pdf", label: "Gemini PDF-tiedostoksi" },
  { route: "export-grok-to-pdf", label: "Grok PDF-tiedostoksi" },
];

export const finnishLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  "page2pdf-gpt": {
    route: "page2pdf-gpt",
    eyebrow: "GPT-sovellus · yksi julkinen URL",
    title: "Muunna julkinen URL PDF-tiedostoksi One Page 2 PDF:llä",
    description: "One Page 2 PDF on kohdennettu GPT-sovellus, joka lähettää yhden julkisen verkkosivun URL-osoitteen muunnettavaksi ja palauttaa yhden PDF-tiedoston.",
    lead: "Anna GPT-sovellukselle yksi julkinen HTTPS-URL. One Page 2 PDF lähettää osoitteen Page 2 File -palveluun ja palauttaa ladattavan PDF-tiedoston.",
    sections: [
      { heading: "1. Lähetä julkinen URL", body: "Liitä muunnettavan sivun tarkka HTTPS-osoite. Pyyntö koskee yhtä sivua eikä käynnistä koko sivuston läpikäyntiä." },
      { heading: "2. Vastaanota yksi PDF", body: "GPT-sovellus palauttaa linkin sivusta luotuun PDF-tiedostoon. Tarkista teksti, linkit, kuvat ja sivunvaihdot ennen tiedoston käyttöä." },
      { heading: "3. Käytä oikeaa laajuutta", body: "One Page 2 PDF ei avaa kirjautuneita välilehtiä eikä ohita käyttöoikeuksia. Käytä Page 2 File -laajennusta sivulle, joka on jo avattu kirjautumisen jälkeen." },
    ],
    externalLinkKey: "page2pdfGpt",
    primaryLabel: "Avaa One Page 2 PDF -GPT-sovellus",
    articleLinks: [{ slug: "save-webpage-as-pdf", label: "Tallenna verkkosivu PDF-tiedostoksi" }, { slug: "long-webpage-page-breaks", label: "Korjaa pitkien verkkosivujen sivunvaihdot" }],
    relatedRoutes: gptRoutes,
  },
  "web2pdf-gpt": {
    route: "web2pdf-gpt",
    eyebrow: "GPT-sovellus · saavutettavat verkkosivut",
    title: "Muunna sivuston sivut erillisiksi PDF-tiedostoiksi Web 2 PDF:llä",
    description: "Web 2 PDF löytää sivuston saavutettavat sivut, muuntaa valitut ja palauttaa erillisen PDF-tiedoston jokaisesta sivusta.",
    lead: "Anna Web 2 PDF:lle julkinen osoite. Sovellus voi löytää saavutettavat sivut, muuntaa valitut URL-osoitteet ja palauttaa useita latauslinkkejä — yhden sivua kohden.",
    sections: [
      { heading: "1. Anna sivusto", body: "Lähetä julkinen aloitus-URL. Sovellus löytää saavutettavat sivut ja näyttää valitun laajuuden ennen muunnosta." },
      { heading: "2. Tarkista sivuluettelo", body: "Vahvista, mitkä saavutettavat sivut kuuluvat pyyntöön. Kirjautumista vaativat sivut, estetyt URL-osoitteet ja ulkoiset verkkotunnukset jätetään pois." },
      { heading: "3. Lataa erilliset PDF-tiedostot", body: "Jokainen muunnettu sivu palautetaan omana PDF-tiedostonaan. Web 2 PDF ei lupaa yhtä yhdistettyä sivustoasiakirjaa tai scraping-aineistoa." },
    ],
    externalLinkKey: "web2pdfGpt",
    primaryLabel: "Avaa Web 2 PDF -GPT-sovellus",
    articleLinks: [{ slug: "multi-page-website-to-pdf", label: "Muunna monisivuinen sivusto PDF-tiedostoiksi" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Vietävät verkkosivustotyypit" }],
    relatedRoutes: gptRoutes,
  },
  "html2pdf-gpt": {
    route: "html2pdf-gpt",
    eyebrow: "GPT-sovellus · ladattu HTML-tiedosto",
    title: "Muunna ladattu HTML-tiedosto HTML 2 PDF:llä",
    description: "HTML 2 PDF vastaanottaa ladatun HTML-tiedoston ja palauttaa selkeän PDF-tiedoston näkyvien renderöintirajojen puitteissa.",
    lead: "Lataa HTML-tiedosto GPT-sovellukseen. HTML 2 PDF renderöi sen eristetysti ja palauttaa PDF-tiedoston; tämä raakatiedostojen työnkulku on käytettävissä vain sovelluksessa.",
    sections: [
      { heading: "1. Lataa HTML-tiedosto", body: "Liitä HTML-asiakirja, jonka käsittelyyn sinulla on oikeus. Työnkulku alkaa tiedostosta, ei julkisen verkkosivun URL-osoitteesta." },
      { heading: "2. Muunna PDF-tiedostoksi", body: "Sovellus palauttaa ladatusta asiakirjasta PDF-tiedoston. Ulkoiset resurssit, skriptit, mukautetut fontit ja selainominaisuudet voivat vaihdella." },
      { heading: "3. Käsittele HTML:ää epäluotettavana syötteenä", body: "Turvallinen renderöinti vaatii eristyksen yksityisistä verkoista, paikallisista tiedostoista ja hallitsemattomista skripteistä. Tulos on asiakirjamuunnos, ei isännöityä verkkokoodin suorittamista." },
    ],
    externalLinkKey: "html2pdfGpt",
    primaryLabel: "Avaa HTML 2 PDF -GPT-sovellus",
    articleLinks: [{ slug: "html-to-pdf-safely", label: "Muunna HTML turvallisesti PDF-tiedostoksi" }, { slug: "webpage-capture-vs-web-scraping", label: "Sivukaappaus verrattuna web scrapingiin" }],
    relatedRoutes: gptRoutes,
  },
  "one-page2powerpoint-gpt": {
    route: "one-page2powerpoint-gpt",
    eyebrow: "GPT-sovellus · yksi julkinen URL",
    title: "Muunna URL PPTX-tiedostoksi One Page 2 PowerPointilla",
    description: "One Page 2 PowerPoint on kohdennettu GPT-sovellus, joka muuntaa yhden julkisen URL-osoitteen ja palauttaa yhden PPTX-esityksen.",
    lead: "Anna sovellukselle yksi julkinen HTTPS-URL. One Page 2 PowerPoint lähettää sivun muunnettavaksi ja palauttaa ladattavan PPTX-esityksen.",
    sections: [
      { heading: "1. Lähetä julkinen URL", body: "Liitä sivun tarkka osoite. Sovellus käsittelee yhden sivun pyyntöä kohden eikä tutki muuta sivustoa." },
      { heading: "2. Vastaanota yksi PPTX", body: "Sivu järjestetään esitykseksi ja palautetaan yhtenä PowerPoint-tiedostona. Tarkista diojen rajat ja visuaaliset tai muokattavat korvaukset." },
      { heading: "3. Pidä yksityiset välilehdet Chromessa", body: "Julkisten URL-osoitteiden GPT-sovellus ei voi käyttää selainistuntoasi. Käytä Page 2 File -laajennusta, kun lähde on avattu kirjautumisen jälkeen." },
    ],
    externalLinkKey: "onePage2PowerpointGpt",
    primaryLabel: "Avaa One Page 2 PowerPoint",
    articleLinks: [{ slug: "webpage-to-powerpoint", label: "Muunna verkkosivu PowerPoint-tiedostoksi" }, { slug: "sections-to-slides", label: "Muunna sivun osiot dioiksi" }],
    relatedRoutes: gptRoutes,
  },
  "web2powerpoint-gpt": {
    route: "web2powerpoint-gpt",
    eyebrow: "GPT-sovellus · saavutettavat verkkosivut",
    title: "Muunna sivuston sivut PPTX-tiedostoiksi Web 2 PowerPointilla",
    description: "Web 2 PowerPoint löytää saavutettavat sivut, muuntaa valitut ja palauttaa erillisen PPTX-tiedoston jokaisesta sivusta.",
    lead: "Anna Web 2 PowerPointille julkinen osoite. Sovellus löytää saavutettavat sivut, muuntaa valitut URL-osoitteet ja palauttaa useita esityslinkkejä.",
    sections: [
      { heading: "1. Anna sivusto", body: "Lähetä julkinen aloitus-URL ja pidä sivuston laajuus selkeänä. Ulkoisia verkkotunnuksia ja yksityisiä sivuja ei sisällytetä huomaamatta." },
      { heading: "2. Vahvista saavutettavat sivut", body: "Tarkista löydetty luettelo ennen muunnosta. Page 2 File -palveluun lähetetään vain valitut ja saavutettavat sivut." },
      { heading: "3. Lataa erilliset PPTX-tiedostot", body: "Jokainen muunnettu sivu palautetaan omana esityksenään. Sovellus ei lupaa yhtä yhdistettyä esitystä koko sivustosta." },
    ],
    externalLinkKey: "web2powerpointGpt",
    primaryLabel: "Avaa Web 2 PowerPoint",
    articleLinks: [{ slug: "website-to-powerpoint", label: "Muunna sivusto PowerPoint-tiedostoiksi" }, { slug: "screenshot-vs-editable-powerpoint", label: "Kuvadiana tai muokattavana diana" }],
    relatedRoutes: gptRoutes,
  },
  "export-ai-chat-to-pdf": {
    route: "export-ai-chat-to-pdf",
    eyebrow: "AI-keskustelujen vienti",
    title: "Vie keskustelu aktiiviselta välilehdeltä",
    description: "Vie tuettuja ChatGPT-, Claude-, Gemini- ja Grok-keskusteluja PDF-tiedostoksi laajennuksella, väliaikaisella esikatselulla ja ilman historiaa.",
    lead: "Valitse alkuperäinen ulkoasu tai yksinkertainen lukuasiakirja. Laajennus vie keskustelun suoraan aktiiviselta selainvälilehdeltä.",
    sections: [
      { heading: "Tuetut keskustelukäyttöliittymät", body: "Page 2 File tukee ChatGPT:tä, Claudea, Geminiä ja Grokia sekä varovaista varavaihtoehtoa muille selainkeskusteluille.", points: ["ChatGPT", "Claude", "Gemini", "Grok"] },
      { heading: "Alkuperäinen ulkoasu", body: "Viestien ryhmittely, koodilohkot, taulukot ja näkyvät lähdelinkit säilyvät." },
      { heading: "Selkeä asiakirja", body: "Tuettu teksti sovitetaan rauhallisempaan asiakirjaan niin, että lähettäjät ja linkkikohteet säilyvät." },
      { heading: "Riippumaton tuote", body: "Page 2 File ei ole minkään tuetun AI-alustan kumppani, hyväksymä tai ylläpitämä." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Asenna laajennus",
    articleLinks: [{ slug: "export-ai-chats-privately", label: "Vie AI-keskustelut yksityisesti" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Vietävät verkkosivustotyypit" }],
    relatedRoutes: chatRoutes,
  },
  "export-chatgpt-to-pdf": {
    route: "export-chatgpt-to-pdf",
    eyebrow: "Vienti ChatGPT:stä",
    title: "Vie pitkät ChatGPT-keskustelut PDF-tiedostoksi",
    description: "Vie näkyvät ChatGPT-viestit, koodi, taulukot, linkit ja pitkät keskustelut aktiiviselta välilehdeltä tarkistettuun PDF-tiedostoon.",
    lead: "Kaappaa aktiivisella välilehdellä näkyvä keskustelu, tarkista sivunvaihdot ja lataa tiedosto ilman Page 2 File -tiliä.",
    sections: [
      { heading: "Tämä säilyy", body: "Viestit, osallistujien järjestys, koodi, taulukot ja näkyvät linkit näkyvät esikatselussa." },
      { heading: "Kaksi lukutyyliä", body: "Säilytä alkuperäinen visuaalinen rytmi tai valitse rauhallisempi asiakirja lukemista ja tulostamista varten." },
      { heading: "Alustakohtaiset rajoitukset", body: "Suljetut haarat, lataamattomat viestit ja DOM:n ulkopuolinen sisältö on ehkä avattava tai ladattava ennen kaappausta." },
      { heading: "Ei virallista yhteyttä", body: "Page 2 File on riippumaton vientityökalu, jota OpenAI tai ChatGPT ei hyväksy eikä ylläpidä." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Asenna ChatGPT:tä varten",
    articleLinks: [{ slug: "export-chatgpt-conversation-to-pdf", label: "Vie ChatGPT-keskustelu PDF-tiedostoksi" }, { slug: "export-ai-chats-privately", label: "Suojaa AI-keskustelun esikatselutiedot" }],
    relatedRoutes: chatRoutes,
  },
  "export-claude-to-pdf": {
    route: "export-claude-to-pdf",
    eyebrow: "Vienti Claudesta",
    title: "Tallenna Claude-keskustelut ja näkyvät artifacts",
    description: "Vie Claude-keskustelut, Markdown, koodi, lainaukset ja näkyvä artifact-konteksti aktiiviselta välilehdeltä tarkistettuun PDF-tiedostoon.",
    lead: "Selkeän napsautuksen jälkeen laajennus lukee aktiivisen keskustelun ja luo väliaikaisen esikatselun pitkille vastauksille.",
    sections: [
      { heading: "Pitkät vastaukset säilyttävät rakenteen", body: "Otsikot, luettelot, lainaukset ja koodi säilyttävät lukujärjestyksen." },
      { heading: "Artifact-konteksti", body: "Näkyvät otsikot ja käytettävissä oleva artifact-sisältö voidaan renderöidä väittämättä pääsyä piilotettuun sisältöön." },
      { heading: "Ei virallista yhteyttä", body: "Page 2 File on riippumaton työkalu, jota Anthropic ei ole hyväksynyt." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Asenna Claudea varten",
    articleLinks: [{ slug: "export-claude-chat-to-pdf", label: "Vie Claude-keskustelu PDF-tiedostoksi" }, { slug: "export-ai-chats-privately", label: "Suojaa AI-keskustelun esikatselutiedot" }],
    relatedRoutes: chatRoutes,
  },
  "export-gemini-to-pdf": {
    route: "export-gemini-to-pdf",
    eyebrow: "Vienti Geministä",
    title: "Muunna Gemini-keskustelu luettavaksi PDF-tiedostoksi",
    description: "Vie näkyvät Gemini-viestit, lähdekortit, koodi ja lainaukset aktiiviselta välilehdeltä tarkistettuun PDF-tiedostoon väliaikaisella esikatselulla.",
    lead: "Tarkista, miten lähdekortit ja näkyvät kuvat esitetään, ennen kuin luot selkeän tai visuaalisesti tarkan asiakirjan.",
    sections: [
      { heading: "Lähteet säilyvät hyödyllisinä", body: "Näkyvät viittaukset ja linkit säilyvät napsautettavina, kun kohteet ovat turvallisia." },
      { heading: "Kuvat seuraavat DOM:ia", body: "Väliaikaisessa esikatselussa voidaan näyttää vain media, joka on aktiivisen sivun käytettävissä." },
      { heading: "Ei virallista yhteyttä", body: "Page 2 File on riippumaton eikä ole Googlen tai Geminin tuote." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Asenna Geminiä varten",
    articleLinks: [{ slug: "export-gemini-chat-to-pdf", label: "Vie Gemini-keskustelu PDF-tiedostoksi" }, { slug: "export-ai-chats-privately", label: "Suojaa AI-keskustelun esikatselutiedot" }],
    relatedRoutes: chatRoutes,
  },
  "export-grok-to-pdf": {
    route: "export-grok-to-pdf",
    eyebrow: "Vienti Grokista",
    title: "Vie Grok-keskustelut näkyvine lähteineen",
    description: "Vie näkyvät Grok-keskustelut, X-linkit, lainatut julkaisut ja lähteet aktiiviselta välilehdeltä tarkistettuun PDF-tiedostoon.",
    lead: "Kaappaa aktiivinen keskustelu, säilytä näkyvä lähdekonteksti ja valitse visuaalinen esikatselu tai selkeä lukuasiakirja.",
    sections: [
      { heading: "Keskustelua seuraava lukujärjestys", body: "Viestit ja lainattujen julkaisujen konteksti pysyvät ryhmiteltyinä sen sijaan, että niistä tulisi yksi merkitsemätön tekstivirta." },
      { heading: "Näkyvät X-linkit", body: "Julkaisujen URL-osoitteet ja lähteet säilyvät napsautettavina, kun ne läpäisevät turvallisuustarkistuksen." },
      { heading: "Ei virallista yhteyttä", body: "Page 2 File on riippumaton tuote, jota xAI tai X ei ole hyväksynyt." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Asenna Grokia varten",
    articleLinks: [{ slug: "export-other-ai-chats-to-pdf", label: "Vie muita AI-keskusteluja PDF-tiedostoksi" }, { slug: "export-ai-chats-privately", label: "Suojaa AI-keskustelun esikatselutiedot" }],
    relatedRoutes: chatRoutes,
  },
};
