import type { ExtensionSeoLandingContent } from "./extension-seo-landings";
import type { ExtensionSeoRoute } from "@/shared/routes/routes";

const steps: ExtensionSeoLandingContent["steps"] = [
  {
    title: "Seite öffnen",
    body: "Öffnen Sie die Seite oder den unterstützten Dialog in Chrome und laden Sie die Inhalte, die in das PDF gehören.",
  },
  {
    title: "Ausgabe wählen",
    body: "Wählen Sie Accurate copy, Editable document oder AI / Chat passend zum gewünschten Ergebnis und stellen Sie die verfügbaren Optionen ein.",
  },
  {
    title: "PDF prüfen",
    body: "Klicken Sie auf Get PDF, lassen Sie den Quell-Tab während der Vorbereitung geöffnet und prüfen Sie das Ergebnis in der PDF-Vorschau von Chrome.",
  },
];

const privacy =
  "Page 2 PDF liest den Tab, in dem Sie die Erweiterung starten, und erstellt das Dokument innerhalb des Erweiterungsablaufs. Seiten- und Chatinhalte werden nicht auf Server von Page 2 File hochgeladen.";

const demos = {
  webpage: {
    title: "Eine lange Seite als vollständiges PDF",
    body: "Dieses Beispiel wurde mit der kontrollierten Testseite für verschachtelte Scrollbereiche erzeugt. Es zeigt eine lange Darstellung, die auf mehrere bildbasierte PDF-Seiten verteilt wurde.",
    image: "/samples/accurate-copy-preview.svg",
    imageAlt: "Vorher-Nachher-Ansicht einer langen Webseite als mehrseitiges PDF",
    samplePdf: "/samples/accurate-copy.pdf",
    sampleLabel: "Geprüftes Beispiel für Accurate copy öffnen",
  },
  editable: {
    title: "Nützliche Seiteninhalte auswählbar halten",
    body: "Das mit der Erweiterung erzeugte Beispiel enthält auswählbaren Text und verfügbare Links aus der Chromium-PDF-Ausgabe und ist kein Screenshot in einer PDF-Hülle.",
    image: "/samples/editable-document-preview.svg",
    imageAlt: "Vorschau einer Webseite als PDF mit auswählbarem Text und Links",
    samplePdf: "/samples/editable-document.pdf",
    sampleLabel: "Geprüftes Beispiel für Editable document öffnen",
  },
  chat: {
    title: "Den aktuellen Dialog als übersichtliches PDF",
    body: "Dieses mit der Erweiterung erzeugte Beispiel bewahrt Reihenfolge und unterstützte Inhaltsstruktur des Dialogs, ohne die umgebende Seitenleiste der Anwendung.",
    image: "/samples/ai-chat-preview.svg",
    imageAlt: "Vorschau eines unterstützten Browser-Dialogs als aufgeräumtes PDF",
    samplePdf: "/samples/ai-chat.pdf",
    sampleLabel: "Geprüftes Beispiel für AI / Chat öffnen",
  },
} satisfies Record<"webpage" | "editable" | "chat", ExtensionSeoLandingContent["demo"]>;

export const germanExtensionSeoLandings: Record<
  ExtensionSeoRoute,
  ExtensionSeoLandingContent
> = {
  "chrome-extension/webpage-to-pdf": {
    route: "chrome-extension/webpage-to-pdf",
    title: "Webseite als PDF in Chrome speichern",
    description: "Speichern Sie die im aktiven Chrome-Tab geöffnete Webseite mit Page 2 PDF als visuelle Ganzseitenkopie oder als Dokument mit auswählbarem Text und sicheren Links.",
    eyebrow: "WEBSEITE ALS PDF · CHROME-ERWEITERUNG",
    heading: "Die geöffnete Webseite als PDF speichern",
    lead: "Page 2 PDF arbeitet mit dem aktuellen Chrome-Tab. Wählen Sie eine visuelle Kopie, wenn das Erscheinungsbild zählt, oder ein bearbeitbares Dokument für auswählbaren Text und verfügbare Links.",
    demo: demos.webpage,
    steps,
    supportedTitle: "Geeignete Seiten",
    supported: ["Öffentliche Webseiten im aktiven Tab.", "Bereits geöffnete Seiten nach einer Anmeldung.", "Lokale HTML-Dateien mit erteilter Chrome-Berechtigung."],
    limitsTitle: "Wichtige Grenzen",
    limits: ["Die Erweiterung nimmt keine eingefügte URL entgegen.", "Geschützte Frames und nicht geladene Inhalte können fehlen.", "Ein PDF ersetzt keine interaktive Website."],
    privacy,
    faqs: [
      { question: "Kann Page 2 PDF Seiten nach der Anmeldung speichern?", answer: "Ja, wenn die Seite bereits im aktiven Tab geöffnet ist und Chrome der Erweiterung den Zugriff erlaubt. Zugangskontrollen werden nicht umgangen." },
      { question: "Bleibt Text im PDF auswählbar?", answer: "Editable document erhält verfügbaren Text und sichere Links. Accurate copy erzeugt dagegen bildbasierte Seiten." },
      { question: "Kann ich einfach eine URL einfügen?", answer: "Nein. Page 2 PDF verarbeitet den bereits geöffneten aktiven Tab." },
    ],
    related: ["chrome-extension/full-page-pdf", "chrome-extension/webpage-to-pdf-with-links", "chrome-extension/chrome-print-vs-page-2-pdf"],
  },
  "chrome-extension/ai-chat-to-pdf": {
    route: "chrome-extension/ai-chat-to-pdf",
    title: "KI-Chat als PDF exportieren",
    description: "Exportieren Sie den aktuellen unterstützten KI-Dialog aus Chrome als strukturiertes PDF mit Nachrichtenrollen, Code, Tabellen, Quellen und verfügbaren Medien.",
    eyebrow: "KI-CHAT ALS PDF · CHROME-ERWEITERUNG",
    heading: "Den aktuellen KI-Chat als PDF exportieren",
    lead: "Der Modus AI / Chat übernimmt den geöffneten unterstützten Dialog, nicht das gesamte Konto. Wählen Sie alle Nachrichten oder nur Antworten und prüfen Sie den Anfang des Exports.",
    demo: demos.chat,
    steps,
    supportedTitle: "Unterstützte KI-Dienste",
    supported: ["ChatGPT, Claude und Gemini.", "Grok, Perplexity, Microsoft Copilot und Manus.", "Andere Seiten nur bei eindeutig erkennbaren Benutzer- und Assistentenrollen."],
    limitsTitle: "Umfang des Exports",
    limits: ["Nur der aktuelle geöffnete Dialog wird verarbeitet.", "Die geladene Historie ist begrenzt.", "Nicht erreichbare Medien oder ältere Nachrichten können fehlen."],
    privacy,
    faqs: [
      { question: "Ist das ein Export des gesamten Kontos?", answer: "Nein. Der Modus verarbeitet nur den aktuellen Dialog im aktiven Tab." },
      { question: "Kann ich nur KI-Antworten speichern?", answer: "Ja. Wählen Sie replies only, wenn die Eingaben für das Verständnis nicht erforderlich sind." },
      { question: "Bleiben Code und Tabellen erhalten?", answer: "Unterstützte Blöcke werden strukturiert übernommen. Prüfen Sie dennoch Umbrüche und Vollständigkeit in der Vorschau." },
    ],
    related: ["chrome-extension/chatgpt-to-pdf", "chrome-extension/claude-to-pdf", "chrome-extension/messenger-chat-to-pdf"],
  },
  "chrome-extension/messenger-chat-to-pdf": {
    route: "chrome-extension/messenger-chat-to-pdf",
    title: "Messenger-Chat im Browser als PDF speichern",
    description: "Speichern Sie den aktuellen unterstützten WhatsApp-Web- oder Telegram-Web-Dialog mit Page 2 PDF als lesbares PDF aus dem aktiven Chrome-Tab.",
    eyebrow: "MESSENGER-CHAT ALS PDF · CHROME",
    heading: "Den geöffneten Messenger-Chat als PDF sichern",
    lead: "Page 2 PDF formatiert den aktuell geöffneten unterstützten Dialog. Es erstellt keine Sicherung des Kontos und exportiert nicht alle Unterhaltungen auf einmal.",
    demo: demos.chat,
    steps,
    supportedTitle: "Unterstützte Messenger",
    supported: ["Aktueller Dialog in WhatsApp Web.", "Chats und Kanäle in Telegram Web.", "Geladene Nachrichten, Absender, Zeiten und unterstützte Medien."],
    limitsTitle: "Nicht enthalten",
    limits: ["Keine mobile App und kein Geräte-Backup.", "Keine Stapelverarbeitung aller Chats.", "Nicht geladene oder geschützte Medien können fehlen."],
    privacy,
    faqs: [
      { question: "Werden alle Chats exportiert?", answer: "Nein. Exportiert wird nur die aktuell geöffnete unterstützte Unterhaltung." },
      { question: "Funktioniert die Erweiterung in der mobilen App?", answer: "Nein. Dieser Ablauf ist für unterstützte Web-Oberflächen im Chrome-Tab vorgesehen." },
      { question: "Kann ich Medien entfernen?", answer: "Ja. Im Modus AI / Chat lassen sich Medien und Links aus der Ausgabe ausschließen." },
    ],
    related: ["chrome-extension/whatsapp-chat-to-pdf", "chrome-extension/telegram-chat-to-pdf", "chrome-extension/ai-chat-to-pdf"],
  },
  "chrome-extension/full-page-pdf": {
    route: "chrome-extension/full-page-pdf",
    title: "Vollständige Webseite als PDF erfassen",
    description: "Erfassen Sie eine lange Webseite aus dem aktiven Chrome-Tab als bildbasiertes Ganzseiten-PDF und prüfen Sie verzögert geladene sowie dynamische Bereiche.",
    eyebrow: "GANZSEITEN-PDF · AKTIVER TAB",
    heading: "Eine lange Webseite vollständig als PDF erfassen",
    lead: "Accurate copy bereitet den Haupt-Scrollbereich vor und teilt die sichtbare Darstellung auf PDF-Seiten auf. Die Methode priorisiert das Aussehen, nicht Textauswahl oder Suche.",
    demo: demos.webpage,
    steps,
    supportedTitle: "Wofür der Modus passt",
    supported: ["Lange Artikel und Dokumentationsseiten.", "Dashboards mit bereits geladenen Bereichen.", "Layouts, deren sichtbare Gestaltung erhalten bleiben soll."],
    limitsTitle: "Vorher prüfen",
    limits: ["Virtuelle Listen können Elemente außerhalb des Bildschirms ersetzen.", "Verzögert geladene Bilder müssen verfügbar sein.", "Fixierte Elemente und geschützte Frames können die Ausgabe beeinflussen."],
    privacy,
    faqs: [
      { question: "Ist das PDF durchsuchbar?", answer: "Nein. Accurate copy erzeugt bildbasierte Seiten. Für auswählbaren Text verwenden Sie Editable document." },
      { question: "Werden alle Lazy-Load-Bilder erfasst?", answer: "Die Erweiterung versucht verfügbare Inhalte begrenzt nachzuladen. Nicht erreichbare Ressourcen können trotzdem fehlen." },
      { question: "Funktionieren sehr lange Seiten immer vollständig?", answer: "Nein. Virtuelle Listen, wechselnde Inhalte und technische Größenlimits können eine vollständige Erfassung verhindern." },
    ],
    related: ["chrome-extension/webpage-to-pdf", "chrome-extension/chrome-print-vs-page-2-pdf", "chrome-extension/webpage-to-pdf-with-links"],
  },
  "chrome-extension/webpage-to-pdf-with-links": {
    route: "chrome-extension/webpage-to-pdf-with-links",
    title: "Webseite als PDF mit auswählbarem Text und Links",
    description: "Erstellen Sie aus dem aktiven Chrome-Tab ein PDF mit auswählbarem Text und verfügbaren sicheren Links über die Chromium-PDF-Ausgabe.",
    eyebrow: "PDF MIT LINKS · EDITABLE DOCUMENT",
    heading: "Webseite mit Text und Links als PDF speichern",
    lead: "Editable document eignet sich für Recherche, Weitergabe und Textprüfung. Wählen Sie Bildschirm- oder Drucklayout und testen Sie Links sowie Textsuche im fertigen PDF.",
    demo: demos.editable,
    steps,
    supportedTitle: "Was erhalten bleiben kann",
    supported: ["Auswählbarer Text und unterstützte Bilder.", "Sichere HTTP- und HTTPS-Links.", "Bildschirm- oder Drucklayout der Seite."],
    limitsTitle: "Was geprüft werden muss",
    limits: ["Skripte und interaktive Zustände werden nicht zu einer PDF-Anwendung.", "Unsichere oder nicht unterstützte Links werden entfernt.", "Komplexe Canvas- oder Frame-Inhalte können vereinfacht werden."],
    privacy,
    faqs: [
      { question: "Sind alle Links anklickbar?", answer: "Nur unterstützte sichere Links können erhalten bleiben. Testen Sie wichtige Ziele im fertigen Dokument." },
      { question: "Kann ich Text kopieren?", answer: "Ja, wenn die Chromium-PDF-Ausgabe den Text der Seite übernehmen kann." },
      { question: "Wann ist Accurate copy besser?", answer: "Wenn visuelle Übereinstimmung wichtiger ist als Textauswahl, Suche oder Links." },
    ],
    related: ["chrome-extension/webpage-to-pdf", "chrome-extension/html-page-to-pdf", "chrome-extension/full-page-pdf"],
  },
  "chrome-extension/html-page-to-pdf": {
    route: "chrome-extension/html-page-to-pdf",
    title: "Geöffnete HTML-Seite als PDF speichern",
    description: "Speichern Sie eine in Chrome geöffnete öffentliche oder lokale HTML-Seite als visuelles oder auswählbares PDF, ohne HTML-Code hochzuladen.",
    eyebrow: "HTML-SEITE ALS PDF · CHROME",
    heading: "Eine geöffnete HTML-Seite in PDF umwandeln",
    lead: "Page 2 PDF verarbeitet die gerenderte Seite im aktiven Tab. Für lokale Dateien kann Chrome die Berechtigung zum Zugriff auf Datei-URLs verlangen.",
    demo: demos.editable,
    steps,
    supportedTitle: "Mögliche Eingaben",
    supported: ["Öffentliche HTML-Seiten im aktiven Tab.", "Lokale HTML-Dateien mit erteilter Berechtigung.", "Visuelle oder auswählbare PDF-Ausgabe."],
    limitsTitle: "Technische Grenzen",
    limits: ["Die Erweiterung nimmt keinen eingefügten Quellcode entgegen.", "Fehlende lokale CSS-, Bild- oder Schriftdateien werden nicht rekonstruiert.", "Skripte bleiben im PDF nicht interaktiv."],
    privacy,
    faqs: [
      { question: "Kann ich eine lokale HTML-Datei speichern?", answer: "Ja, nachdem der Dateizugriff für Page 2 PDF in den Chrome-Einstellungen erlaubt wurde." },
      { question: "Kann ich HTML-Code einfügen?", answer: "Nein. Öffnen Sie das gerenderte Dokument als Tab; Page 2 PDF ist kein Code-Upload-Dienst." },
      { question: "Bleiben externe Ressourcen erhalten?", answer: "Nur Ressourcen, die die geöffnete Seite tatsächlich laden kann, stehen für die Ausgabe zur Verfügung." },
    ],
    related: ["chrome-extension/webpage-to-pdf", "chrome-extension/webpage-to-pdf-with-links", "chrome-extension/full-page-pdf"],
  },
  "chrome-extension/chatgpt-to-pdf": {
    route: "chrome-extension/chatgpt-to-pdf",
    title: "ChatGPT-Dialog als PDF exportieren",
    description: "Exportieren Sie den aktuell geöffneten ChatGPT-Dialog aus Chrome als strukturiertes PDF mit unterstütztem Text, Code, Tabellen, Quellen und Medien.",
    eyebrow: "CHATGPT ALS PDF · AKTIVER DIALOG",
    heading: "Den aktuellen ChatGPT-Dialog als PDF speichern",
    lead: "Der ChatGPT-Adapter erkennt Benutzer- und Assistentenbeiträge im geöffneten Dialog. Wählen Sie den Nachrichtenumfang und prüfen Sie, ob der erste benötigte Beitrag geladen wurde.",
    demo: demos.chat,
    steps,
    supportedTitle: "Unterstützte Inhalte",
    supported: ["Benutzer- und Assistentennachrichten.", "Codeblöcke, Tabellen und Quellen.", "Alle Nachrichten oder nur Assistentenantworten."],
    limitsTitle: "Abgrenzung",
    limits: ["Kein Export des gesamten ChatGPT-Kontos.", "Nur der aktuelle geladene Dialog.", "Die Oberfläche des Anbieters kann sich ändern und den Adapter vorübergehend beeinträchtigen."],
    privacy,
    faqs: [
      { question: "Ersetzt das den offiziellen Datenexport?", answer: "Nein. Ein Dialog-PDF ist ein Lesedokument; der offizielle Export umfasst weitere Kontodaten." },
      { question: "Kann ich nur Antworten exportieren?", answer: "Ja. Verwenden Sie replies only und prüfen Sie, ob der verbleibende Kontext verständlich ist." },
      { question: "Werden Quellen übernommen?", answer: "Unterstützte Quellen und Links können enthalten sein. Prüfen Sie jedes wichtige Ziel im Ergebnis." },
    ],
    related: ["chrome-extension/ai-chat-to-pdf", "chrome-extension/claude-to-pdf", "chrome-extension/webpage-to-pdf-with-links"],
  },
  "chrome-extension/claude-to-pdf": {
    route: "chrome-extension/claude-to-pdf",
    title: "Claude-Dialog als PDF exportieren",
    description: "Speichern Sie den aktuell geöffneten Claude-Dialog aus Chrome als strukturiertes PDF und prüfen Sie Text, Code, Tabellen, Quellen und verfügbare Anhänge.",
    eyebrow: "CLAUDE ALS PDF · AKTIVER DIALOG",
    heading: "Den aktuellen Claude-Dialog als PDF speichern",
    lead: "Page 2 PDF verarbeitet den geöffneten Claude-Dialog mit dem dafür vorgesehenen Adapter. Es übernimmt nur geladene und erkennbare Inhalte aus diesem Tab.",
    demo: demos.chat,
    steps,
    supportedTitle: "Geeignete Inhalte",
    supported: ["Geladene Benutzer- und Assistentenbeiträge.", "Unterstützte Codeblöcke, Tabellen und Links.", "Alle Nachrichten oder nur Antworten."],
    limitsTitle: "Vor dem Export",
    limits: ["Ältere Beiträge müssen im Dialog geladen sein.", "Nicht verfügbare Anhänge können fehlen.", "Der Export ist kein Kontoarchiv."],
    privacy,
    faqs: [
      { question: "Wird mein gesamter Claude-Verlauf exportiert?", answer: "Nein. Page 2 PDF verarbeitet nur den aktuellen Dialog." },
      { question: "Kann ich Medien auslassen?", answer: "Ja. Deaktivieren Sie Medien, wenn ein textbezogenes Dokument ausreicht." },
      { question: "Warum fehlt ein älterer Beitrag?", answer: "Er war möglicherweise nicht geladen oder lag außerhalb der begrenzten Verlaufserfassung." },
    ],
    related: ["chrome-extension/ai-chat-to-pdf", "chrome-extension/chatgpt-to-pdf", "chrome-extension/webpage-to-pdf-with-links"],
  },
  "chrome-extension/whatsapp-chat-to-pdf": {
    route: "chrome-extension/whatsapp-chat-to-pdf",
    title: "WhatsApp-Web-Chat als PDF exportieren",
    description: "Exportieren Sie die aktuell geöffnete WhatsApp-Web-Unterhaltung mit Page 2 PDF als lesbares PDF aus dem aktiven Chrome-Tab.",
    eyebrow: "WHATSAPP WEB ALS PDF · CHROME",
    heading: "Den aktuellen WhatsApp-Web-Chat als PDF speichern",
    lead: "Der Adapter formatiert die geladene aktuelle Unterhaltung mit Absendern, Zeiten und unterstützten Medien. Andere Chats und Kontodaten bleiben außerhalb des Exports.",
    demo: demos.chat,
    steps,
    supportedTitle: "Im aktuellen Chat",
    supported: ["Geladene Nachrichten und Absender.", "Erkennbare Zeitangaben.", "Unterstützte Medien und Links, sofern ausgewählt."],
    limitsTitle: "Nicht versprochen",
    limits: ["Kein Export aller WhatsApp-Unterhaltungen.", "Kein mobiles Backup und keine Wiederherstellungsdatei.", "Nicht geladene Nachrichten und geschützte Medien können fehlen."],
    privacy,
    faqs: [
      { question: "Kann ich alle WhatsApp-Chats auf einmal speichern?", answer: "Nein. Der Ablauf gilt für die aktuell geöffnete Unterhaltung in WhatsApp Web." },
      { question: "Ist das eine WhatsApp-Sicherung?", answer: "Nein. Das PDF ist ein Lesedokument und kann nicht als Konto- oder Gerätebackup wiederhergestellt werden." },
      { question: "Kann ich Bilder entfernen?", answer: "Ja. Im Modus AI / Chat können Medien vor der Ausgabe ausgeschlossen werden." },
    ],
    related: ["chrome-extension/messenger-chat-to-pdf", "chrome-extension/telegram-chat-to-pdf", "chrome-extension/ai-chat-to-pdf"],
  },
  "chrome-extension/telegram-chat-to-pdf": {
    route: "chrome-extension/telegram-chat-to-pdf",
    title: "Telegram-Web-Chat oder Kanal als PDF exportieren",
    description: "Speichern Sie den aktuell geöffneten Telegram-Web-Chat oder -Kanal mit Page 2 PDF als strukturiertes PDF aus dem aktiven Chrome-Tab.",
    eyebrow: "TELEGRAM WEB ALS PDF · CHROME",
    heading: "Telegram-Web-Chat oder -Kanal als PDF speichern",
    lead: "Page 2 PDF verarbeitet den aktuell geöffneten und geladenen Dialog oder Kanal. Es durchsucht keine anderen Unterhaltungen und erstellt kein Telegram-Kontoarchiv.",
    demo: demos.chat,
    steps,
    supportedTitle: "Unterstützter Umfang",
    supported: ["Aktueller Chat in Telegram Web.", "Aktuell geöffneter Telegram-Kanal.", "Geladene Beiträge, Absender und unterstützte Medien."],
    limitsTitle: "Zu beachten",
    limits: ["Nur geladene Nachrichten können erfasst werden.", "Andere Chats werden nicht automatisch einbezogen.", "Interaktive Medien bleiben im PDF statisch."],
    privacy,
    faqs: [
      { question: "Kann ich einen Telegram-Kanal speichern?", answer: "Ja, wenn der Kanal in Telegram Web geöffnet und sein benötigter Inhalt geladen ist." },
      { question: "Werden alle Unterhaltungen exportiert?", answer: "Nein. Der Export bleibt auf den aktuellen Chat oder Kanal beschränkt." },
      { question: "Bleiben Videos abspielbar?", answer: "Nein. Ein PDF bildet unterstützte Medien statisch ab oder lässt sie aus." },
    ],
    related: ["chrome-extension/messenger-chat-to-pdf", "chrome-extension/whatsapp-chat-to-pdf", "chrome-extension/ai-chat-to-pdf"],
  },
  "chrome-extension/chrome-print-vs-page-2-pdf": {
    route: "chrome-extension/chrome-print-vs-page-2-pdf",
    title: "Chrome Print oder Page 2 PDF vergleichen",
    description: "Vergleichen Sie Chrome Print mit Page 2 PDF für lange oder angemeldete Webseiten und wählen Sie Drucklayout, visuelle Kopie oder auswählbares Dokument.",
    eyebrow: "CHROME PRINT IM VERGLEICH · PDF",
    heading: "Wann Chrome Print genügt und wann Page 2 PDF hilft",
    lead: "Beginnen Sie mit Chrome Print, wenn die Vorschau vollständig und gut lesbar ist. Wechseln Sie nur bei einem konkreten Problem wie abgeschnittenen Bereichen, ungeeignetem Druckstil oder benötigter visueller Wiedergabe.",
    demo: demos.webpage,
    steps,
    supportedTitle: "Page 2 PDF ergänzt",
    supported: ["Visuelle Ganzseitenkopien über Accurate copy.", "Auswählbaren Text über Editable document.", "Strukturierte unterstützte Chat-Exporte."],
    limitsTitle: "Chrome Print bleibt besser, wenn",
    limits: ["Die Druckvorschau bereits vollständig ist.", "Papierformat, Ränder und Skalierung direkt eingestellt werden sollen.", "Keine zusätzliche Erweiterung benötigt wird."],
    privacy,
    faqs: [
      { question: "Sollte ich zuerst Chrome Print versuchen?", answer: "Ja. Wenn Inhalt, Lesbarkeit und Seitenumbrüche stimmen, ist Chrome Print häufig ausreichend." },
      { question: "Welche Methode bewahrt das Aussehen?", answer: "Accurate copy priorisiert die sichtbare Darstellung, erzeugt jedoch bildbasierte Seiten." },
      { question: "Welche Methode hält Text auswählbar?", answer: "Editable document nutzt die Chromium-PDF-Ausgabe, um verfügbaren Text und sichere Links zu erhalten." },
    ],
    related: ["chrome-extension/full-page-pdf", "chrome-extension/webpage-to-pdf-with-links", "chrome-extension/webpage-to-pdf"],
  },
};
