import type { LandingContent, RelatedRoute } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

const gptRelatedRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "page2pdf-gpt", label: "Webpage to PDF Converter — Web2File" },
  { route: "html2pdf-gpt", label: "HTML 2 PDF" },
];

export const germanLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  "page2pdf-gpt": {
    route: "page2pdf-gpt",
    eyebrow: "Web2File GPT · genaue URLs, PDFs oder Screenshots",
    title: "Webseite in PDF umwandeln — Web2File",
    displayTitle: "GPT: Webpage 2 PDF",
    description: "Web2File verarbeitet öffentliche URLs, vorhandene Webseiten-PDFs oder geordnete Screenshots und gibt pro Webseite ein separates visuelles oder interaktives PDF zurück.",
    lead: "Übermitteln Sie genau die öffentlichen Seiten oder Dateien, die verarbeitet werden sollen. Für jede Webseite entsteht ein eigenes PDF: Visual PDF priorisiert die Darstellung, Interactive PDF vorhandenen auswählbaren Text und überprüfbare Links.",
    sections: [
      { heading: "1. Genaue Seite oder Datei bereitstellen", body: "Senden Sie eine öffentliche URL, eine Liste genauer öffentlicher URLs, ein vorhandenes Webseiten-PDF oder geordnete Ganzseiten-Screenshots. Jede übermittelte Webseite bleibt eine eigene Ausgabedatei." },
      { heading: "2. Visuelle oder interaktive Ausgabe wählen", body: "Visual PDF priorisiert das Erscheinungsbild der gelieferten Seite. Interactive PDF priorisiert vorhandenen auswählbaren Text und Links, die geprüft werden können. Innerhalb einer Anfrage gilt für alle URLs derselbe Modus." },
      { heading: "3. Beim übermittelten Umfang bleiben", body: "Web2File öffnet nur die genauen öffentlichen URLs aus der Anfrage. Es durchsucht keine Domain oder Sitemap, folgt keinen Links zu weiteren Seiten und umgeht weder Anmeldung noch Paywall, CAPTCHA, regionale Sperre oder andere Zugriffskontrollen." },
      { heading: "4. PDFs und Screenshots als Beleg verwenden", body: "Geordnete Screenshots können zu einem Visual PDF zusammengesetzt werden. Ein hochgeladenes Webseiten-PDF wird anhand seines vorhandenen Inhalts geprüft und verarbeitet; fehlende Seiteninhalte werden nicht rekonstruiert oder erfunden." },
      { heading: "5. Jede gelieferte Datei prüfen", body: "Prüfen Sie Reihenfolge, abgeschnittene oder fehlende Bereiche, unerklärte Leerflächen, Lesbarkeit, Layout und unterstützte Links. Ist eine direkte Konvertierung blockiert, erklärt Web2File einen Browser- oder Exportweg, statt eine Erfassung vorzutäuschen." },
    ],
    externalLinkKey: "page2pdfGpt",
    primaryLabel: "GPT Webpage 2 PDF öffnen",
    relatedRoutes: gptRelatedRoutes,
    workflowOverride: {
      detailsTitle: "Anleitung",
      firstStageDescription: "Übergeben Sie der GPT-App eine funktionierende URL.",
      firstStageLabel: "URLs senden",
    },
  },
  "html2pdf-gpt": {
    route: "html2pdf-gpt",
    eyebrow: "Web2File GPT · eine hochgeladene HTML-Datei",
    title: "HTML in PDF umwandeln — Web2File",
    displayTitle: "GPT: HTML 2 PDF",
    description: "Web2File rendert eine hochgeladene HTML-Datei und liefert ein geprüftes PDF mit dem verfügbaren Layout, Text, Bildern und Links.",
    lead: "Laden Sie ein HTML-Dokument hoch. Web2File rendert die Datei mit erreichbaren Stilen und Ressourcen, wählt eine geeignete Seitenausrichtung und prüft das PDF auf abgeschnittene oder fehlende Inhalte.",
    sections: [
      { heading: "1. Ein HTML-Dokument hochladen", body: "Dieser Ablauf akzeptiert eine HTML-Datei. Er ersetzt die Datei nicht durch eine URL, verarbeitet keinen Stapel, durchsucht keine verlinkten Seiten und führt nicht mehrere Dokumente zusammen." },
      { heading: "2. Benötigte Ressourcen erreichbar machen", body: "Eingebettete Stile laden mit dem Dokument. Erreichbare externe Stylesheets, Schriften und Bilder können ebenfalls geladen werden. Fehlende lokale CSS- oder Bilddateien müssen beigefügt werden, wenn sie für die beabsichtigte Darstellung nötig sind." },
      { heading: "3. Dokument ohne aktive Anwendung rendern", body: "Web2File zeigt das HTML in einer geeigneten Desktopbreite und erhält verfügbare Reihenfolge, Typografie, Abstände, Spalten, Karten und Bilder. Interaktive Steuerelemente werden nicht zu einer funktionierenden Anwendung." },
      { heading: "4. Dokument auf PDF-Seiten verteilen", body: "Wo möglich, bleiben vorhandener auswählbarer Text und unterstützte Links erhalten. Für ein breites Layout können Querformat oder ein geeigneteres Seitenformat Quetschung, Beschnitt und ungünstige Spaltenumbrüche verringern." },
      { heading: "5. Ergebnis kontrollieren", body: "Prüfen Sie vor der Übergabe fehlende Ressourcen, abgeschnittene Komponenten, unerklärte Leerflächen, unleserlichen Text, schlechte Seitenumbrüche, verschobene Bilder und nicht erhaltene Links." },
    ],
    externalLinkKey: "html2pdfGpt",
    primaryLabel: "GPT HTML 2 PDF öffnen",
    relatedRoutes: gptRelatedRoutes,
    workflowOverride: {
      detailsTitle: "Fünf Schritte von HTML zu PDF",
      firstStageDescription: "Übergeben Sie der GPT-App eine HTML-Datei.",
      firstStageLabel: "HTML hochladen",
    },
  },
  privacy: {
    route: "privacy",
    eyebrow: "Datenschutz und Datenverarbeitung",
    title: "Datenschutzerklärung von Page 2 File",
    description: "Wie Page 2 File Dienst-, Support- und eingewilligte Analytics-Daten verarbeitet, wie lange sie gespeichert werden und wie Sie Ihre Rechte ausüben.",
    lead: "Diese Datenschutzerklärung beschreibt die Verarbeitung beim Besuch der Website, bei einer Supportanfrage, bei der Nutzung der Erweiterung Page 2 PDF und bei verfügbaren Konvertierungsabläufen. Optionale Google Analytics bleiben bis zu Ihrer Einwilligung ausgeschaltet.",
    sections: [
      { heading: "Verantwortlicher und Geltungsbereich", body: "{{entityName}} mit der Anschrift {{address}} betreibt Page 2 File und ist für die hier beschriebene Verarbeitung verantwortlich. Diese Erklärung gilt für die Website, die Browser-Erweiterung Page 2 PDF und zugehörige Konvertierungsdienste." },
      { heading: "Datenquellen und Kategorien", body: "Wir erhalten Daten von Ihnen, Ihrem Browser und der Infrastruktur, die den Dienst ausliefert. Je nach Funktion können dazu IP-Adresse und technische Anfragedaten, Browser- und Geräteinformationen, nach Einwilligung besuchte Page-2-File-Seiten, zulässige Kampagnenwerte, E-Mail-Adresse und Supporttext, eine öffentliche URL, Konvertierungseinstellungen, temporäre Auftragskennungen und erzeugte Dateien gehören." },
      { heading: "Nicht angeforderte Daten und Grenze der Erweiterung", body: "Page 2 File verlangt kein Benutzerkonto und fragt weder Zahlungskartendaten noch Rechnungsadresse oder Passwort der ursprünglichen Website ab. Die Erweiterung arbeitet mit dem bereits geöffneten Tab und erstellt das Dokument innerhalb ihres Ablaufs. Seiten- oder Chatinhalte werden weder an Page 2 File noch an Google Analytics gesendet." },
      { heading: "Zwecke und Rechtsgrundlagen", body: "Daten werden verarbeitet, um eine angeforderte Funktion bereitzustellen, Supportnachrichten zu beantworten, den Dienst zu schützen und zu betreiben, Fehler zu untersuchen, rechtliche Pflichten zu erfüllen und — nur mit Einwilligung — die Nutzung öffentlicher Seiten zu messen. Je nach anwendbarem Recht stützen wir uns auf Vertragserfüllung oder vorvertragliche Maßnahmen, berechtigte Interessen an Sicherheit und Zuverlässigkeit, rechtliche Pflichten und Einwilligung für optionale Analytics oder eine Supportübermittlung, soweit diese erforderlich ist." },
      { heading: "Konvertierungsinhalt und temporäre Verarbeitung", body: "Eine Website-Konvertierung erfordert, soweit verfügbar, eine temporäre Verarbeitung der übermittelten öffentlichen Seite und Optionen. Die Antwort nennt Ablaufzeiten für Auftrag, Vorschau und Datei. Page 2 File führt keinen kontobasierten Verlauf; temporäre Daten werden zum genannten technischen Zeitpunkt oder früher gelöscht, wenn der Ablauf dies zulässt." },
      { heading: "Supportnachrichten", body: "Nach Auswahl von Senden werden E-Mail-Adresse und Kommentar über die Telegram Bot API an ein privates Entwicklungsthema von Page 2 File übermittelt. Der Hinweis steht vor dem Absenden am Formular. Zugriff haben nur zuständige Teammitglieder. Die Korrespondenz bleibt bis zur Lösung der Anfrage und verbundener Sicherheits- oder Rechtsfragen gespeichert und wird danach gelöscht oder anonymisiert, sobald sie nicht mehr benötigt wird." },
      { heading: "Optionale Google Analytics", body: "Google Analytics ist im Basic Consent Mode eingebunden. Vor der Auswahl „Analytics erlauben“ wird der Google-Tag nicht geladen; auch Einwilligungssignale, Seitenaufrufe oder Ereignisse werden nicht an Google gesendet. Nach Einwilligung kann Google beim Empfang die IP-Adresse, Seitentitel und Seitenadresse ohne Abfrage oder Fragment, die Herkunft eines externen Referrers, Browser- und Geräteinformationen, einen groben Standort, normalisierte Kampagnenwerte und wenige Ereignisse zu Produktlinks erhalten. Supportfelder und Konvertierungsinhalte werden nie übermittelt." },
      { heading: "Analytics-Einstellungen und Aufbewahrung", body: "Nach der Einwilligung setzt Google Analytics First-Party-Cookies mit dem Präfix p2f_ga. Sie laufen spätestens 180 Tage nach der ersten Einwilligung ab und werden bei späteren Seitenaufrufen nicht verlängert. Für die Analytics-Property gilt die kürzeste verfügbare Aufbewahrung für Nutzer- und Ereignisdaten von zwei Monaten; aggregierte Standardberichte können nach den Produktregeln von Google länger bestehen. Google Signals, Anzeigenpersonalisierung, automatische erweiterte Analysen sowie die detaillierte Erfassung von Standort- und Gerätedaten sind deaktiviert." },
      { heading: "Dienstleister und Empfänger", body: "Cloudflare hostet, liefert und schützt die Website; Google stellt die eingewilligte Analyse bereit; Telegram übermittelt Supportnachrichten. Jeder Anbieter verarbeitet nur die für seine Rolle erforderlichen Kategorien nach den jeweils anwendbaren Bedingungen. Eine Offenlegung kann außerdem gesetzlich vorgeschrieben sein, Rechte oder Sicherheit schützen oder bei einer rechtmäßigen Unternehmensübertragung mit geeigneten Garantien erfolgen." },
      { heading: "Weitere Aufbewahrungsfristen", body: "Notwendige Sitzungs- und CSRF-Werte laufen nach einer Stunde ab. Temporäre Konvertierungsdaten folgen der für den Auftrag ausgegebenen Frist. Infrastruktur- und Sicherheitsdaten bleiben nur so lange erhalten, wie Betrieb, Missbrauchsuntersuchung, Vorgaben des Anbieters oder rechtliche Pflichten es erfordern. Für Support gilt das oben beschriebene Kriterium. Enden Zweck und Pflicht, werden personenbezogene Daten gelöscht oder anonymisiert." },
      { heading: "Internationale Verarbeitung", body: "Der Betreiber hat seinen Sitz in {{jurisdiction}}. Cloudflare, Google und Telegram können Daten in anderen Ländern verarbeiten. Soweit Garantien erforderlich sind, verwenden wir die Datenverarbeitungsbedingungen und verfügbaren vertraglichen Übermittlungsmechanismen des Anbieters. Verlangt anwendbares Recht eine Einwilligung zur Dritt- oder Auslandsübermittlung, wird sie vor optionalen Analytics eingeholt; die Supportübermittlung wird vor dem Absenden klar angezeigt." },
      { heading: "Sicherheit", body: "Page 2 File verwendet gleichursprüngliche Routen, kurzlebige anonyme Sitzungen, Origin- und CSRF-Prüfungen, signierte Backend-Anfragen, URL-Validierung, isoliertes Rendering und temporäre Dateien. Zugriffe sind nach Aufgaben beschränkt. Keine Maßnahme garantiert absolute Sicherheit; übermitteln Sie daher nur Inhalte, zu deren Offenlegung Sie berechtigt sind." },
      { heading: "Ihre Datenschutzrechte", body: "Je nach anwendbarem Recht können Sie Information und Auskunft, Berichtigung, Löschung, Einschränkung oder Übertragbarkeit verlangen und einer Verarbeitung widersprechen. Eine Einwilligung kann ohne Auswirkung auf die frühere Rechtmäßigkeit widerrufen werden. Sie können sich bei der zuständigen Datenschutzaufsicht beschweren. Page 2 File trifft keine ausschließlich automatisierten Entscheidungen mit rechtlicher oder vergleichbar erheblicher Wirkung. Zur Suche eines Datensatzes und Prüfung der anfragenden Person können wenige zusätzliche Angaben nötig sein." },
      { heading: "Kein Verkauf, keine zielgerichtete Werbung und kein Profiling", body: "Page 2 File verkauft keine personenbezogenen Daten, gibt sie nicht für kontextübergreifende verhaltensbezogene Werbung weiter, leitet aus sensiblen Daten keine Merkmale ab und zeigt keine zielgerichtete Werbung. Ein Global-Privacy-Control-Signal wird als Ablehnung optionaler Analytics behandelt, auch wenn dies für diese Verarbeitung nicht ausdrücklich vorgeschrieben ist." },
      { id: "cookies", heading: "Cookies und lokaler Speicher", body: "Die unbedingt erforderlichen First-Party-Cookies p2f_session und p2f_csrf halten eine anonyme gleichursprüngliche Sitzung und schützen eine angeforderte Support- oder Konvertierungsaktion. Sie verwenden Strict SameSite und laufen nach einer Stunde ab. Der Local-Storage-Schlüssel page2file-analytics-consent-v2 speichert eine Zustimmung oder Ablehnung höchstens 180 Tage, damit die Website sie beachtet. Erst nach Einwilligung setzt Google First-Party-Cookies mit dem Präfix p2f_ga für höchstens 180 Tage. Supporttext oder Konvertierungsinhalt sind darin nicht enthalten." },
      { heading: "Ihre Analytics-Auswahl", body: "Das erste Dialogfeld bietet gleichwertig „Ohne Analytics fortfahren“ und „Analytics erlauben“ an. Über „Datenschutzeinstellungen“ im Footer können Sie die Auswahl prüfen oder widerrufen. Nach dem Widerruf werden keine neuen Ereignisse gesendet und erreichbare p2f_ga-Cookies entfernt. Nach Ablauf oder Löschen der Auswahl sind Analytics wieder aus. Das Blockieren von Sitzungs- oder CSRF-Cookies kann geschützte Anfragen verhindern; öffentliche Seiten bleiben erreichbar." },
      { heading: "Nur für Volljährige", body: "Der Dienst ist nur für Personen bestimmt, die mindestens 18 Jahre alt und an ihrem Wohnort volljährig sind. Wir erheben nicht wissentlich Daten Minderjähriger. Eltern oder Sorgeberechtigte können eine Löschung anfragen, wenn sie eine Übermittlung durch eine minderjährige Person vermuten." },
      { heading: "Websites Dritter", body: "Page 2 File kann Inhalte fremder Websites öffnen oder konvertieren und auf externe Dienste verweisen. Diese Parteien bestimmen Inhalt, Sicherheit und Datenschutz selbst; bei ihrer Nutzung gelten deren Bedingungen." },
      { heading: "Änderungen dieser Erklärung", body: "Diese Erklärung kann bei Änderungen des Dienstes, der Anbieter oder rechtlicher Anforderungen überarbeitet werden. Die neue Fassung wird hier mit geändertem Datum veröffentlicht. Eine wesentliche Änderung einwilligungsbasierter Verarbeitung macht die gespeicherte Analytics-Auswahl ungültig, damit sie erneut abgefragt wird." },
      { heading: "Kontakt und Beschwerden", body: "Richten Sie Datenschutzfragen oder Anträge an {{contactEmail}}. Verantwortlicher ist {{entityName}}, {{address}}. Wir antworten innerhalb der nach anwendbarem Recht geltenden Frist. Sie können sich außerdem an die zuständige Aufsichtsbehörde an Ihrem Wohnort oder am Ort des vermuteten Verstoßes wenden." },
    ],
    legal: true,
  },
  terms: {
    route: "terms",
    eyebrow: "Nutzungsvereinbarung",
    title: "Nutzungsbedingungen",
    description: "Bedingungen für Page 2 File, einschließlich zulässiger Inhalte, Konvertierungsgrenzen, Verantwortung der Nutzer und Verfügbarkeit.",
    lead: "Diese Bedingungen regeln die Nutzung der Website Page 2 File, der Chrome-Erweiterung Page 2 PDF und zugehöriger Konvertierungsdienste.",
    sections: [
      { heading: "Vereinbarung und Betreiber", body: "Mit dem Zugriff auf Page 2 File stimmen Sie diesen Bedingungen zu. Sie müssen mindestens 18 Jahre alt und an Ihrem Wohnort volljährig sein. Betreiber ist {{entityName}} mit Sitz unter {{address}}. Bei Nutzung für eine Organisation bestätigen Sie, zur Annahme in deren Namen befugt zu sein." },
      { heading: "Begriffe", body: "„Dienst“ bezeichnet Website, Chrome-Erweiterung Page 2 PDF und zugehörige Funktionen. „Übermittelte Inhalte“ sind Webseiten, Inhalte aktiver Tabs oder anderes Material zur Konvertierung. „Ausgabe“ bezeichnet PDF, Vorschau oder ein anderes erzeugtes Ergebnis." },
      { heading: "Beschränkte Lizenz", body: "Wir gewähren ein widerrufliches, nicht ausschließliches, nicht übertragbares und beschränktes Recht, den Dienst nach diesen Bedingungen zu nutzen. Eigentum an Software, Marken oder anderem geschütztem Material wird nicht übertragen." },
      { heading: "Zulässige Inhalte und Verantwortung", body: "Sie dürfen nur Inhalte konvertieren, auf die Sie rechtmäßig zugreifen dürfen und die Sie verarbeiten, vervielfältigen und herunterladen dürfen. Sie tragen die Verantwortung für übermittelte URLs und Tab-Inhalte, gewählte Einstellungen sowie Nutzung und Weitergabe jeder Ausgabe." },
      { heading: "Verbotene Nutzung", body: "Der Dienst darf nicht für rechtswidrige Handlungen, Rechtsverletzungen, Umgehung von Bezahlschranken oder Zugriffskontrollen, Malware, missbräuchliche Inhalte, Prüfung privater Netze, Störung von Sicherheitsmaßnahmen, übermäßige automatisierte Anfragen, Reverse Engineering geschützter Teile oder falsche Darstellung erzeugter Dateien verwendet werden." },
      { heading: "Übermittelte Inhalte und Rechte Dritter", body: "Bestehende Rechte an übermittelten Inhalten bleiben bei Ihnen. Page 2 File gewährt keine Rechte an fremdem Material. Sie sichern zu, dass Verarbeitung und Ausgabe keine Urheber-, Datenschutz-, Vertraulichkeits-, Vertrags- oder sonstigen anwendbaren Rechte verletzen." },
      { heading: "Temporäre Verarbeitung", body: "Der Dienst kann Inhalte, Einstellungen und erzeugte Dateien temporär verarbeiten, um Vorschau und Download bereitzustellen. Ein kontobasierter Verlauf wird nicht angeboten. Einzelheiten stehen in der Datenschutzerklärung." },
      { heading: "Grenzen der Ausgabe und Wiedergabetreue", body: "Webseiten können Skripte, Animationen, Videos, geschützte Medien, eigene Schriften, Canvas-Grafiken, dynamische Daten und komplexe Layouts enthalten, die nicht exakt in einem statischen PDF reproduziert werden. Accurate copy priorisiert die Darstellung; Editable document rekonstruiert unterstützten Text, Bilder und Links. Prüfen Sie Vorschau und Ausgabe vor der Verwendung." },
      { heading: "Dienste und Links Dritter", body: "Der Dienst kann fremde Websites verarbeiten oder verlinken. Page 2 File ist nicht für Verfügbarkeit, Inhalt, Richtigkeit, Rechtmäßigkeit, Sicherheit oder Datenschutz Dritter verantwortlich. Es gelten weiterhin die Bedingungen des jeweiligen Anbieters." },
      { heading: "Datenschutz und Cookies", body: "Die Datenschutzerklärung beschreibt notwendige Verarbeitung, optionale Analytics, Dienstleister, Cookies und Ihre Auswahl. Eine angeforderte Funktion erfordert die zu ihrer Bereitstellung nötige Verarbeitung; Google Analytics bleiben optional und werden nur durch eine gesonderte bestätigende Handlung aktiviert." },
      { heading: "Geistiges Eigentum von Page 2 File", body: "Dienst, Software, Gestaltung, Texte, Logos und anderes Material von Page 2 File gehören {{entityName}} oder Lizenzgebern und sind rechtlich geschützt. Eigentumshinweise dürfen nicht entfernt und der Dienst außerhalb gesetzlicher Erlaubnisse nicht kopiert, verkauft, unterlizenziert oder kommerziell verwertet werden." },
      { heading: "Feedback", body: "Für freiwillige Vorschläge oder Rückmeldungen gewähren Sie uns ein weltweites, unbefristetes und unentgeltliches Recht zur Nutzung für Verbesserung oder Entwicklung des Dienstes. Rechte an übermittelten Inhalten werden dadurch nicht übertragen." },
      { heading: "Änderungen, Aktualisierungen und Verfügbarkeit", body: "Wir können den Dienst oder Funktionen aktualisieren, begrenzen, aussetzen oder einstellen und versprechen keine dauerhafte Verfügbarkeit einzelner Funktionen. Technische Grenzen können für Sicherheit, Zuverlässigkeit oder faire Nutzung eingesetzt werden." },
      { heading: "Sperrung und Beendigung", body: "Sie können die Nutzung jederzeit beenden. Wir können Zugriff sperren, wenn ein Verstoß vermutet wird, eine Gefahr für den Dienst oder andere Systeme besteht oder rechtliches Handeln erforderlich ist. Fortgeltende Bestimmungen bleiben wirksam." },
      { heading: "Urheberrechts- und sonstige Beschwerden", body: "Wenn Sie eine Rechtsverletzung vermuten, senden Sie an {{contactEmail}} Angaben zum geschützten Werk, betroffenen Material oder URL, Ihre Kontaktdaten und eine Begründung." },
      { heading: "Keine Gewährleistung", body: "Soweit rechtlich zulässig, werden Dienst und Ausgaben „wie besehen“ und „wie verfügbar“ bereitgestellt. Wir garantieren weder unterbrechungsfreien oder fehlerfreien Betrieb noch vollständige Wiedergabetreue, Verfügbarkeit fremder Seiten, Eignung für einen bestimmten Zweck oder Erfüllung aller Anforderungen." },
      { heading: "Haftungsbeschränkung", body: "Soweit nach anwendbarem Recht zulässig, haftet {{entityName}} nicht für indirekte, beiläufige, besondere, Folge- oder Strafschäden, entgangenen Gewinn, Daten-, Geschäfts- oder Datenschutzverluste oder Kosten aus Nutzung oder Nichtnutzbarkeit. Zwingende Rechte bleiben unberührt." },
      { heading: "Freistellung", body: "Soweit zulässig, stellen Sie {{entityName}} von Ansprüchen Dritter frei, die aus übermittelten Inhalten, Nutzung oder Weitergabe einer Ausgabe, Verstößen gegen diese Bedingungen oder Verletzungen fremder Rechte entstehen." },
      { heading: "Salvatorische Klausel, Verzicht und Gesamtvereinbarung", body: "Ist eine Bestimmung unwirksam oder nicht durchsetzbar, bleiben die übrigen wirksam und die betroffene Bestimmung wird ihrem Zweck möglichst nahe ausgelegt. Nichtdurchsetzung ist kein Verzicht. Diese Bedingungen und die Datenschutzerklärung bilden die Vereinbarung über den Dienst." },
      { heading: "Anwendbares Recht und Streitigkeiten", body: "Diese Bedingungen unterliegen dem Recht von {{jurisdiction}} ohne Kollisionsrecht. Vor einem formellen Verfahren bemühen sich beide Seiten nach schriftlicher Mitteilung um eine einvernehmliche Lösung. Ungelöste Streitigkeiten können den zuständigen Gerichten vorgelegt werden, soweit zwingendes Recht nichts anderes verlangt." },
      { heading: "Änderungen dieser Bedingungen", body: "Die Bedingungen können bei Änderungen des Dienstes, der Anbieter oder rechtlicher Anforderungen überarbeitet werden. Die neue Fassung wird mit Datum veröffentlicht. Wer den Dienst danach weiter nutzt, stimmt der neuen Fassung zu; andernfalls ist die Nutzung zu beenden." },
      { heading: "Kontakt", body: "Fragen oder Mitteilungen können an {{contactEmail}} oder an {{entityName}}, {{address}}, gerichtet werden." },
    ],
    legal: true,
  },
};
