import type { LandingContent, RelatedRoute } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

const gptRelatedRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "page2pdf-gpt", label: "Webpage to PDF Converter — Web2File" },
  { route: "html2pdf-gpt", label: "HTML 2 PDF" },
];

export const germanLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  "page2pdf-gpt": {
    route: "page2pdf-gpt",
    eyebrow: "Web2File GPT · genaue URLs, PDFs oder Screenshots",
    title: "Webseite in PDF umwandeln — Web2File",
    displayTitle: "GPT: Webpage 2 PDF",
    description: "Web2File verarbeitet öffentliche URLs, vorhandene Webseiten-PDFs oder geordnete Screenshots und gibt pro Webseite ein separates visuelles oder interaktives PDF zurück.",
    lead: "Übermitteln Sie genau die öffentlichen Seiten oder Dateien, die verarbeitet werden sollen. Für jede Webseite entsteht ein eigenes PDF: Visual PDF priorisiert die Darstellung, Interactive PDF vorhandenen auswählbaren Text und überprüfbare Links.",
    sections: [
      { heading: "1. Genaue Seite oder Datei bereitstellen", body: "Senden Sie eine öffentliche URL, eine Liste genauer öffentlicher URLs, ein vorhandenes Webseiten-PDF oder geordnete Ganzseiten-Screenshots. Jede übermittelte Webseite bleibt eine eigene Ausgabedatei." },
      { heading: "2. Visuelle oder interaktive Ausgabe wählen", body: "Visual PDF priorisiert das Erscheinungsbild der gelieferten Seite. Interactive PDF priorisiert vorhandenen auswählbaren Text und Links, die geprüft werden können. Innerhalb einer Anfrage gilt für alle URLs derselbe Modus." },
      { heading: "3. Beim übermittelten Umfang bleiben", body: "Web2File öffnet nur die genauen öffentlichen URLs aus der Anfrage. Es durchsucht keine Domain oder Sitemap, folgt keinen Links zu weiteren Seiten und umgeht weder Anmeldung noch Paywall, CAPTCHA, regionale Sperre oder andere Zugriffskontrollen." },
      { heading: "4. PDFs und Screenshots als Beleg verwenden", body: "Geordnete Screenshots können zu einem Visual PDF zusammengesetzt werden. Ein hochgeladenes Webseiten-PDF wird anhand seines vorhandenen Inhalts geprüft und verarbeitet; fehlende Seiteninhalte werden nicht rekonstruiert oder erfunden." },
      { heading: "5. Jede gelieferte Datei prüfen", body: "Prüfen Sie Reihenfolge, abgeschnittene oder fehlende Bereiche, unerklärte Leerflächen, Lesbarkeit, Layout und unterstützte Links. Ist eine direkte Konvertierung blockiert, erklärt Web2File einen Browser- oder Exportweg, statt eine Erfassung vorzutäuschen." },
    ],
    externalLinkKey: "page2pdfGpt",
    primaryLabel: "GPT Webpage 2 PDF öffnen",
    relatedRoutes: gptRelatedRoutes,
    workflowOverride: {
      detailsTitle: "Anleitung",
      firstStageDescription: "Übergeben Sie der GPT-App eine funktionierende URL.",
      firstStageLabel: "URLs senden",
    },
  },
  "html2pdf-gpt": {
    route: "html2pdf-gpt",
    eyebrow: "Web2File GPT · eine hochgeladene HTML-Datei",
    title: "HTML in PDF umwandeln — Web2File",
    displayTitle: "GPT: HTML 2 PDF",
    description: "Web2File rendert eine hochgeladene HTML-Datei und liefert ein geprüftes PDF mit dem verfügbaren Layout, Text, Bildern und Links.",
    lead: "Laden Sie ein HTML-Dokument hoch. Web2File rendert die Datei mit erreichbaren Stilen und Ressourcen, wählt eine geeignete Seitenausrichtung und prüft das PDF auf abgeschnittene oder fehlende Inhalte.",
    sections: [
      { heading: "1. Ein HTML-Dokument hochladen", body: "Dieser Ablauf akzeptiert eine HTML-Datei. Er ersetzt die Datei nicht durch eine URL, verarbeitet keinen Stapel, durchsucht keine verlinkten Seiten und führt nicht mehrere Dokumente zusammen." },
      { heading: "2. Benötigte Ressourcen erreichbar machen", body: "Eingebettete Stile laden mit dem Dokument. Erreichbare externe Stylesheets, Schriften und Bilder können ebenfalls geladen werden. Fehlende lokale CSS- oder Bilddateien müssen beigefügt werden, wenn sie für die beabsichtigte Darstellung nötig sind." },
      { heading: "3. Dokument ohne aktive Anwendung rendern", body: "Web2File zeigt das HTML in einer geeigneten Desktopbreite und erhält verfügbare Reihenfolge, Typografie, Abstände, Spalten, Karten und Bilder. Interaktive Steuerelemente werden nicht zu einer funktionierenden Anwendung." },
      { heading: "4. Dokument auf PDF-Seiten verteilen", body: "Wo möglich, bleiben vorhandener auswählbarer Text und unterstützte Links erhalten. Für ein breites Layout können Querformat oder ein geeigneteres Seitenformat Quetschung, Beschnitt und ungünstige Spaltenumbrüche verringern." },
      { heading: "5. Ergebnis kontrollieren", body: "Prüfen Sie vor der Übergabe fehlende Ressourcen, abgeschnittene Komponenten, unerklärte Leerflächen, unleserlichen Text, schlechte Seitenumbrüche, verschobene Bilder und nicht erhaltene Links." },
    ],
    externalLinkKey: "html2pdfGpt",
    primaryLabel: "GPT HTML 2 PDF öffnen",
    relatedRoutes: gptRelatedRoutes,
    workflowOverride: {
      detailsTitle: "Fünf Schritte von HTML zu PDF",
      firstStageDescription: "Übergeben Sie der GPT-App eine HTML-Datei.",
      firstStageLabel: "HTML hochladen",
    },
  },
  privacy: {
    route: "privacy",
    eyebrow: "Datenschutz und Datenverarbeitung",
    title: "Datenschutzerklärung von Page 2 File",
    description: "Wie Page 2 File Webseiteninhalte, temporäre Konvertierungsdateien, technische Cookies, Analytics-Daten und Datenschutzanfragen verarbeitet.",
    lead: "Diese Datenschutzerklärung beschreibt die Verarbeitung beim Besuch der Website, bei der Nutzung der Chrome-Erweiterung Page 2 PDF und bei verfügbaren Konvertierungsabläufen.",
    sections: [
      { heading: "Verantwortlicher und Geltungsbereich", body: "{{entityName}} mit Sitz unter {{address}} betreibt Page 2 File und ist für die hier beschriebene Verarbeitung verantwortlich. Diese Erklärung gilt für die Website, die Browser-Erweiterung Page 2 PDF und zugehörige Konvertierungsdienste." },
      { heading: "Begriffe", body: "„Dienst“ bezeichnet Page 2 File und seine Konvertierungsfunktionen. „Konvertierungsinhalt“ bezeichnet URL, sichtbaren Webseiteninhalt, gewählte Optionen und erzeugte PDF-Datei. „Personenbezogene Daten“ sind Informationen, die eine Person identifizieren oder vernünftigerweise mit ihr verknüpft werden können." },
      { heading: "Verarbeitete Informationen", body: "Je nach Nutzung können technische Anfragedaten, IP-Adresse, Browser- und Geräteinformationen, besuchte Page-2-File-Seiten, zulässige Kampagnenparameter, eine öffentliche URL oder Inhalt des aktiven Tabs, Einstellungen, temporäre Auftragskennungen und erzeugte Dateien verarbeitet werden." },
      { heading: "Nicht angeforderte Informationen", body: "Page 2 File verlangt kein Benutzerkonto und fragt weder Zahlungskartendaten noch Rechnungsadresse oder Passwort der ursprünglichen Website ab. Die Erweiterung verwendet die bereits geöffnete Seite und erhält das dort verwendete Passwort nicht." },
      { heading: "Verwendungszwecke", body: "Informationen werden verarbeitet, um Vorschauen und Dateien bereitzustellen, Missbrauch abzuwehren, Fehler zu untersuchen, Zuverlässigkeit zu erhalten, aggregierte Nutzung öffentlicher Seiten zu verstehen, Anfragen zu beantworten und rechtliche Pflichten zu erfüllen. Personenbezogene Daten werden nicht verkauft." },
      { heading: "Konvertierungsinhalt und temporäre Verarbeitung", body: "Eine Website-Konvertierung erfordert, soweit verfügbar, eine temporäre serverseitige Verarbeitung der übermittelten öffentlichen Seite und Optionen. Page 2 PDF erstellt Dokumente innerhalb der Erweiterung und lädt Seiten- oder Chatinhalte nicht auf Page-2-File-Server hoch. Es gibt keinen kontobasierten Verlauf; temporäre Vorschauen und Dateien werden nach ihrem Lebenszyklus oder technischen Ablauf entfernt." },
      { heading: "Supportnachrichten", body: "Beim Supportformular werden E-Mail-Adresse und Kommentar an ein privates Telegram-Entwicklungsthema gesendet. Die Korrespondenz kann so lange aufbewahrt werden, wie dies für Antwort, Untersuchung, Schutz des Dienstes oder Dokumentation der Lösung vernünftigerweise nötig ist." },
      { heading: "Analytics und Zuordnung", body: "Ist eine gültige Google-Analytics-Mess-ID eingerichtet, lädt Google Analytics auf öffentlichen Seiten im cookielosen Modus. Analytics-Speicherung bleibt verweigert. Google kann Seitentitel, bereinigte Seitenadresse und Referrer, Geräte- und Browserinformationen, ungefähren Standort sowie normalisierte Kampagnenwerte erhalten. Supportfelder und Konvertierungsinhalte werden nicht an Google Analytics gesendet." },
      { heading: "Dienstleister und Offenlegung", body: "Page 2 File verwendet {{processors}}, um den Dienst bereitzustellen, zu schützen und zu messen. Diese Anbieter verarbeiten technische Daten nur, soweit dies für ihre Dienste nötig ist, und nach ihren eigenen Datenschutzbedingungen. Eine Offenlegung kann außerdem gesetzlich, zum Schutz von Rechten oder Sicherheit oder bei einer rechtmäßigen Unternehmensübertragung erfolgen." },
      { heading: "Aufbewahrung und Löschung", body: "Konvertierungsinhalte werden nur für den temporären Verarbeitungs- und Downloadablauf gehalten und nicht als sichtbarer Verlauf gespeichert. Sicherheitsprotokolle, Infrastrukturdaten, Analytics-Daten und Korrespondenz können für Betrieb, Sicherheit, rechtliche Pflichten oder die Bearbeitung einer Anfrage aufbewahrt werden." },
      { heading: "Sicherheit", body: "Page 2 File verwendet gleichursprüngliche Konvertierungsrouten, anonyme Sitzungssteuerung, Origin- und CSRF-Prüfungen, signierte Backend-Anfragen, URL-Validierung, isoliertes Rendering und temporäre Dateien. Keine Maßnahme garantiert absolute Sicherheit; verarbeiten Sie daher keine Inhalte, zu deren Offenlegung Sie nicht berechtigt sind." },
      { heading: "Internationale Verarbeitung", body: "Anbieter können technische oder analytische Daten außerhalb Ihres Landes verarbeiten. Soweit anwendbar, stützen wir uns auf Schutzmaßnahmen der Anbieter und zulässige Übermittlungsmechanismen. Der Betreiber hat seinen Sitz in {{jurisdiction}}." },
      { heading: "Datenschutzrechte", body: "Je nach anwendbarem Recht können Sie Auskunft, Berichtigung, Löschung oder Einschränkung personenbezogener Daten verlangen oder bestimmter Verarbeitung widersprechen. Da Page 2 File keine Konten oder Konvertierungsarchive führt, können zusätzliche Angaben zur Zuordnung eines betrieblichen Datensatzes nötig sein." },
      { heading: "Websites Dritter", body: "Page 2 File kann Inhalte fremder Websites öffnen oder konvertieren und auf externe Dienste verweisen. Inhalt, Sicherheit und Datenschutz dieser Angebote werden von den jeweiligen Dritten bestimmt; bei ihrer Nutzung gelten deren Bedingungen." },
      { heading: "Kinder", body: "Der Dienst richtet sich nicht an Kinder unter 13 Jahren. Wir erheben wissentlich keine personenbezogenen Daten von Kindern unter 13 Jahren. Eltern oder Sorgeberechtigte können eine Löschung anfragen, wenn sie eine Übermittlung vermuten." },
      { id: "cookies", heading: "Analytics-Speicherung und technische Cookies", body: "Die kurzlebigen Cookies p2f_session und p2f_csrf halten eine anonyme gleichursprüngliche Sitzung und schützen Anfragen wie Supportfeedback. Sie verwenden Strict SameSite und laufen nach einer Stunde ab. Google Analytics arbeitet mit verweigerter Analytics-Speicherung und liest oder schreibt keine Analytics-Cookies. Feedbacktext, Konvertierungsinhalt und direkt identifizierende Profildaten werden nicht in diesen Cookies abgelegt." },
      { heading: "Cookies blockieren oder löschen", body: "Die Website bietet keine Analytics-Einstellungen. Netzwerkzugriffe können dennoch blockiert und technische Cookies im Browser gelöscht werden. Das Blockieren von Sitzungs- oder CSRF-Cookies kann Support und andere geschützte Anfragen verhindern, nicht jedoch das Laden öffentlicher Kernseiten." },
      { heading: "Änderungen dieser Erklärung", body: "Diese Erklärung kann bei Änderungen des Dienstes, der Anbieter oder rechtlicher Anforderungen aktualisiert werden. Die neue Fassung wird mit geändertem Datum veröffentlicht; wesentliche Änderungen gelten ab dem angegebenen Zeitpunkt." },
      { heading: "Kontakt", body: "Fragen und Datenschutzanfragen können an {{contactEmail}} gerichtet werden. Verantwortlicher ist {{entityName}}, {{address}}, nach dem Recht von {{jurisdiction}}." },
    ],
    legal: true,
  },
  terms: {
    route: "terms",
    eyebrow: "Nutzungsvereinbarung",
    title: "Nutzungsbedingungen",
    description: "Bedingungen für Page 2 File, einschließlich zulässiger Inhalte, Konvertierungsgrenzen, Verantwortung der Nutzer und Verfügbarkeit.",
    lead: "Diese Bedingungen regeln die Nutzung der Website Page 2 File, der Chrome-Erweiterung Page 2 PDF und zugehöriger Konvertierungsdienste.",
    sections: [
      { heading: "Vereinbarung und Betreiber", body: "Mit dem Zugriff auf Page 2 File stimmen Sie diesen Bedingungen zu. Betreiber ist {{entityName}} mit Sitz unter {{address}}. Bei Nutzung für eine Organisation bestätigen Sie, zur Annahme in deren Namen befugt zu sein." },
      { heading: "Begriffe", body: "„Dienst“ bezeichnet Website, Chrome-Erweiterung Page 2 PDF und zugehörige Funktionen. „Übermittelte Inhalte“ sind Webseiten, Inhalte aktiver Tabs oder anderes Material zur Konvertierung. „Ausgabe“ bezeichnet PDF, Vorschau oder ein anderes erzeugtes Ergebnis." },
      { heading: "Beschränkte Lizenz", body: "Wir gewähren ein widerrufliches, nicht ausschließliches, nicht übertragbares und beschränktes Recht, den Dienst nach diesen Bedingungen zu nutzen. Eigentum an Software, Marken oder anderem geschütztem Material wird nicht übertragen." },
      { heading: "Zulässige Inhalte und Verantwortung", body: "Sie dürfen nur Inhalte konvertieren, auf die Sie rechtmäßig zugreifen dürfen und die Sie verarbeiten, vervielfältigen und herunterladen dürfen. Sie tragen die Verantwortung für übermittelte URLs und Tab-Inhalte, gewählte Einstellungen sowie Nutzung und Weitergabe jeder Ausgabe." },
      { heading: "Verbotene Nutzung", body: "Der Dienst darf nicht für rechtswidrige Handlungen, Rechtsverletzungen, Umgehung von Bezahlschranken oder Zugriffskontrollen, Malware, missbräuchliche Inhalte, Prüfung privater Netze, Störung von Sicherheitsmaßnahmen, übermäßige automatisierte Anfragen, Reverse Engineering geschützter Teile oder falsche Darstellung erzeugter Dateien verwendet werden." },
      { heading: "Übermittelte Inhalte und Rechte Dritter", body: "Bestehende Rechte an übermittelten Inhalten bleiben bei Ihnen. Page 2 File gewährt keine Rechte an fremdem Material. Sie sichern zu, dass Verarbeitung und Ausgabe keine Urheber-, Datenschutz-, Vertraulichkeits-, Vertrags- oder sonstigen anwendbaren Rechte verletzen." },
      { heading: "Temporäre Verarbeitung", body: "Der Dienst kann Inhalte, Einstellungen und erzeugte Dateien temporär verarbeiten, um Vorschau und Download bereitzustellen. Ein kontobasierter Verlauf wird nicht angeboten. Einzelheiten stehen in der Datenschutzerklärung." },
      { heading: "Grenzen der Ausgabe und Wiedergabetreue", body: "Webseiten können Skripte, Animationen, Videos, geschützte Medien, eigene Schriften, Canvas-Grafiken, dynamische Daten und komplexe Layouts enthalten, die nicht exakt in einem statischen PDF reproduziert werden. Accurate copy priorisiert die Darstellung; Editable document rekonstruiert unterstützten Text, Bilder und Links. Prüfen Sie Vorschau und Ausgabe vor der Verwendung." },
      { heading: "Dienste und Links Dritter", body: "Der Dienst kann fremde Websites verarbeiten oder verlinken. Page 2 File ist nicht für Verfügbarkeit, Inhalt, Richtigkeit, Rechtmäßigkeit, Sicherheit oder Datenschutz Dritter verantwortlich. Es gelten weiterhin die Bedingungen des jeweiligen Anbieters." },
      { heading: "Datenschutz und Cookies", body: "Die Datenschutzerklärung beschreibt temporäre Verarbeitung, Analytics, Dienstleister und Cookies. Mit der Nutzung erkennen Sie die für die angeforderte Konvertierung notwendige Verarbeitung an." },
      { heading: "Geistiges Eigentum von Page 2 File", body: "Dienst, Software, Gestaltung, Texte, Logos und anderes Material von Page 2 File gehören {{entityName}} oder Lizenzgebern und sind rechtlich geschützt. Eigentumshinweise dürfen nicht entfernt und der Dienst außerhalb gesetzlicher Erlaubnisse nicht kopiert, verkauft, unterlizenziert oder kommerziell verwertet werden." },
      { heading: "Feedback", body: "Für freiwillige Vorschläge oder Rückmeldungen gewähren Sie uns ein weltweites, unbefristetes und unentgeltliches Recht zur Nutzung für Verbesserung oder Entwicklung des Dienstes. Rechte an übermittelten Inhalten werden dadurch nicht übertragen." },
      { heading: "Änderungen, Aktualisierungen und Verfügbarkeit", body: "Wir können den Dienst oder Funktionen aktualisieren, begrenzen, aussetzen oder einstellen und versprechen keine dauerhafte Verfügbarkeit einzelner Funktionen. Technische Grenzen können für Sicherheit, Zuverlässigkeit oder faire Nutzung eingesetzt werden." },
      { heading: "Sperrung und Beendigung", body: "Sie können die Nutzung jederzeit beenden. Wir können Zugriff sperren, wenn ein Verstoß vermutet wird, eine Gefahr für den Dienst oder andere Systeme besteht oder rechtliches Handeln erforderlich ist. Fortgeltende Bestimmungen bleiben wirksam." },
      { heading: "Urheberrechts- und sonstige Beschwerden", body: "Wenn Sie eine Rechtsverletzung vermuten, senden Sie an {{contactEmail}} Angaben zum geschützten Werk, betroffenen Material oder URL, Ihre Kontaktdaten und eine Begründung." },
      { heading: "Keine Gewährleistung", body: "Soweit rechtlich zulässig, werden Dienst und Ausgaben „wie besehen“ und „wie verfügbar“ bereitgestellt. Wir garantieren weder unterbrechungsfreien oder fehlerfreien Betrieb noch vollständige Wiedergabetreue, Verfügbarkeit fremder Seiten, Eignung für einen bestimmten Zweck oder Erfüllung aller Anforderungen." },
      { heading: "Haftungsbeschränkung", body: "Soweit nach anwendbarem Recht zulässig, haftet {{entityName}} nicht für indirekte, beiläufige, besondere, Folge- oder Strafschäden, entgangenen Gewinn, Daten-, Geschäfts- oder Datenschutzverluste oder Kosten aus Nutzung oder Nichtnutzbarkeit. Zwingende Rechte bleiben unberührt." },
      { heading: "Freistellung", body: "Soweit zulässig, stellen Sie {{entityName}} von Ansprüchen Dritter frei, die aus übermittelten Inhalten, Nutzung oder Weitergabe einer Ausgabe, Verstößen gegen diese Bedingungen oder Verletzungen fremder Rechte entstehen." },
      { heading: "Salvatorische Klausel, Verzicht und Gesamtvereinbarung", body: "Ist eine Bestimmung unwirksam oder nicht durchsetzbar, bleiben die übrigen wirksam und die betroffene Bestimmung wird ihrem Zweck möglichst nahe ausgelegt. Nichtdurchsetzung ist kein Verzicht. Diese Bedingungen und die Datenschutzerklärung bilden die Vereinbarung über den Dienst." },
      { heading: "Anwendbares Recht und Streitigkeiten", body: "Diese Bedingungen unterliegen dem Recht von {{jurisdiction}} ohne Kollisionsrecht. Vor einem formellen Verfahren bemühen sich beide Seiten nach schriftlicher Mitteilung um eine einvernehmliche Lösung. Ungelöste Streitigkeiten können den zuständigen Gerichten vorgelegt werden, soweit zwingendes Recht nichts anderes verlangt." },
      { heading: "Änderungen dieser Bedingungen", body: "Die Bedingungen können bei Änderungen des Dienstes, der Anbieter oder rechtlicher Anforderungen überarbeitet werden. Die neue Fassung wird mit Datum veröffentlicht. Wer den Dienst danach weiter nutzt, stimmt der neuen Fassung zu; andernfalls ist die Nutzung zu beenden." },
      { heading: "Kontakt", body: "Fragen oder Mitteilungen können an {{contactEmail}} oder an {{entityName}}, {{address}}, gerichtet werden." },
    ],
    legal: true,
  },
};
