import type { LandingContent, RelatedRoute } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

const gptRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "page2pdf-gpt", label: "Webpage to PDF Converter — Web2File" },
  { route: "web2pdf-gpt", label: "Web 2 PDF" },
  { route: "html2pdf-gpt", label: "HTML 2 PDF" },
  { route: "one-page2powerpoint-gpt", label: "One Page 2 PowerPoint" },
  { route: "web2powerpoint-gpt", label: "Web 2 PowerPoint" },
];
const chatRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "export-ai-chat-to-pdf", label: "Alle eksporter av AI-chatter" },
  { route: "export-chatgpt-to-pdf", label: "ChatGPT til PDF" },
  { route: "export-claude-to-pdf", label: "Claude til PDF" },
  { route: "export-gemini-to-pdf", label: "Gemini til PDF" },
  { route: "export-grok-to-pdf", label: "Grok til PDF" },
];

export const norwegianLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  "page2pdf-gpt": {
    route: "page2pdf-gpt",
    eyebrow: "GPT-app · nøyaktige URL-er, PDF-er eller skjermbilder",
    title: "Webpage to PDF Converter — Web2File",
    displayTitle: "GPT: Webpage 2 PDF",
    description: "Webpage to PDF Converter — Web2File konverterer nøyaktige offentlige nettsideadresser og behandler opplastede nettside-PDF-er eller skjermbilder til separate Visual PDF- eller Interactive PDF-filer.",
    lead: "Oppgi en nøyaktig offentlig URL, en liste med nøyaktige URL-er, en nettside-PDF eller helsides eller sammenhengende skjermbilder. Velg Visual PDF for å lagre nettstedet som skjermbilder eller Interactive PDF for markerbar tekst og klikkbare lenker.",
    sections: [
      { heading: "1. Oppgi én eller flere URL-er", body: "Send en offentlig URL, en liste med nøyaktige offentlige URL-er, en eksisterende nettside-PDF eller helsides eller sammenhengende skjermbilder. Hver nettside forblir en separat PDF." },
      { heading: "2. Velg PDF-type", body: "Velg Visual PDF for et bildebasert resultat som prioriterer sidens utseende, eller Interactive PDF når markerbar tekst og klikkbare lenker er viktigst. Én modus gjelder for hele URL-listen." },
      { heading: "3. Konverter bare oppgitte sider", body: "Appen åpner bare de nøyaktige offentlige URL-ene. Den gjennomsøker ikke domener eller sitemaps, finner ikke sider, følger ikke interne lenker og omgår ikke innlogging, betalingsmurer, CAPTCHA, geografiske eller andre tilgangsbegrensninger. Bruk Web2File: Website 2 PDF for hele nettstedet." },
      { heading: "4. Behandle PDF-er og skjermbilder", body: "Opplastede skjermbilder kan settes sammen ovenfra og ned i en Visual PDF. Nettside-PDF-er behandles uten å dikte opp manglende innhold; Interactive PDF prioriterer eksisterende tekst, oppsett, bilder og verifiserte lenker." },
      { heading: "5. Få tilpasset lagringshjelp og kontroller resultatet", body: "Hvis direkte konvertering er utilgjengelig eller ufullstendig, gir appen trinn for siden, nettleseren eller innebygd eksport. Kontroller manglende eller beskåret innhold, tomme områder, lesbarhet, rekkefølge, oppsett, lenker og samsvar med valgt modus." },
    ],
    externalLinkKey: "page2pdfGpt",
    primaryLabel: "Åpne GPT Webpage 2 PDF",
    articleLinks: [{ slug: "save-webpage-as-pdf", label: "Lagre en nettside som PDF" }, { slug: "long-webpage-page-breaks", label: "Rett sideskift på lange nettsider" }],
    relatedRoutes: gptRoutes,
    workflowOverride: {
      detailsTitle: "Bruksanvisning",
      firstStageDescription: "Gi GPT-appen en fungerende URL.",
      firstStageLabel: "Send URL-er",
    },
  },
  "web2pdf-gpt": {
    route: "web2pdf-gpt",
    eyebrow: "GPT-app · tilgjengelige nettsider",
    title: "Konverter nettstedssider til separate PDF-filer med Web 2 PDF",
    description: "Web 2 PDF finner tilgjengelige sider på et nettsted, konverterer de valgte og returnerer en separat PDF for hver side.",
    lead: "Gi Web 2 PDF en offentlig adresse. Appen kan finne tilgjengelige sider, konvertere valgte URL-er og returnere flere nedlastingslenker, én per side.",
    sections: [
      { heading: "1. Oppgi nettstedet", body: "Send den første offentlige URL-en. Appen finner tilgjengelige sider og viser valgt omfang før konvertering." },
      { heading: "2. Kontroller sidelisten", body: "Bekreft hvilke tilgjengelige sider som tilhører forespørselen. Påloggede sider, blokkerte URL-er og eksterne domener utelates." },
      { heading: "3. Last ned separate PDF-filer", body: "Hver konverterte side leveres som en egen PDF. Web 2 PDF lover ikke et kombinert nettsteddokument eller et datasett for scraping." },
    ],
    externalLinkKey: "web2pdfGpt",
    primaryLabel: "Åpne GPT-appen Web 2 PDF",
    articleLinks: [{ slug: "multi-page-website-to-pdf", label: "Konverter et flersidig nettsted til PDF" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typer nettsteder som kan eksporteres" }],
    relatedRoutes: gptRoutes,
  },
  "html2pdf-gpt": {
    route: "html2pdf-gpt",
    eyebrow: "GPT-app · opplastet HTML-fil",
    title: "HTML to PDF Converter — Web2File",
    displayTitle: "GPT: HTML 2 PDF",
    description: "HTML to PDF Converter — Web2File gjør én opplastet HTML-fil om til en kontrollert PDF og bevarer oppsett, bilder, tekst og lenker.",
    lead: "Last opp nøyaktig én HTML-fil. GPT HTML 2 PDF forhåndsviser utformingen, laster inn tilgjengelige stiler, skrifter og bilder og lager en kontrollert PDF med markerbar tekst og klikkbare lenker der det er mulig.",
    sections: [
      { heading: "1. Last opp nøyaktig én HTML-fil", body: "Legg ved ett HTML-dokument. GPT-appen godtar ikke en URL i stedet, behandler ikke flere HTML-filer, gjennomsøker ikke nettsteder, følger ikke lenker til ekstra sider og slår ikke sammen dokumenter." },
      { heading: "2. Ta med stiler og ressurser", body: "Innebygde stiler brukes automatisk sammen med tilgjengelige eksterne stilark, skrifter og bilder. Hvis HTML-filen viser til en manglende lokal CSS-fil, kan du laste opp den samsvarende filen for et mer nøyaktig resultat eller fortsette uten den." },
      { heading: "3. Forhåndsvis og bevar utformingen", body: "HTML-filen forhåndsvises med en passende skrivebordsbredde før konvertering. PDF-en forsøker å bevare tema, farger, typografi, avstander, kolonner, kort, bilder og innholdsrekkefølge uten å aktivere interaktive kontroller." },
      { heading: "4. Lag én lesbar PDF", body: "GPT-appen lager én PDF med markerbar tekst og fungerende hyperlenker der det er mulig. Brede oppsett kan bruke liggende format eller en passende sidestørrelse, slik at viktige elementer ikke presses sammen, beskjæres eller deles." },
      { heading: "5. Kontroller den ferdige filen", body: "Hver PDF kontrolleres før levering for manglende innhold, beskårne komponenter, uforklarlige tomme områder, lesbarhet, sideskift, bildeplassering og støttede lenker." },
    ],
    externalLinkKey: "html2pdfGpt",
    primaryLabel: "Åpne GPT HTML 2 PDF",
    articleLinks: [{ slug: "html-to-pdf-safely", label: "Konverter HTML sikkert til PDF" }, { slug: "webpage-capture-vs-web-scraping", label: "Sidefangst sammenlignet med web scraping" }],
    relatedRoutes: gptRoutes,
    workflowOverride: {
      detailsTitle: "Fem trinn fra HTML til PDF",
      firstStageDescription: "Gi GPT-appen én HTML-fil.",
      firstStageLabel: "Last opp HTML",
    },
  },
  "one-page2powerpoint-gpt": {
    route: "one-page2powerpoint-gpt",
    eyebrow: "GPT-app · én offentlig URL",
    title: "Konverter en URL til PPTX med One Page 2 PowerPoint",
    description: "One Page 2 PowerPoint er en spesialisert GPT-app som konverterer en offentlig URL og returnerer en PPTX-presentasjon av siden.",
    lead: "Gi appen en offentlig HTTPS-URL. One Page 2 PowerPoint sender siden til konvertering og returnerer en nedlastbar PPTX-presentasjon.",
    sections: [
      { heading: "1. Send en offentlig URL", body: "Lim inn den nøyaktige adressen til siden. Appen behandler én side per forespørsel og utforsker ikke resten av nettstedet." },
      { heading: "2. Motta en PPTX", body: "Siden organiseres i en presentasjon og leveres som en PowerPoint-fil. Kontroller lysbildegrenser og visuelle eller redigerbare erstatninger." },
      { heading: "3. Behold private faner i Chrome", body: "En GPT-app for offentlige URL-er kan ikke bruke nettleserøkten din. Bruk Page 2 File-utvidelsen når kilden er åpen etter pålogging." },
    ],
    externalLinkKey: "onePage2PowerpointGpt",
    primaryLabel: "Åpne One Page 2 PowerPoint",
    articleLinks: [{ slug: "webpage-to-powerpoint", label: "Konverter en nettside til PowerPoint" }, { slug: "sections-to-slides", label: "Konverter sidedeler til lysbilder" }],
    relatedRoutes: gptRoutes,
  },
  "web2powerpoint-gpt": {
    route: "web2powerpoint-gpt",
    eyebrow: "GPT-app · tilgjengelige nettsider",
    title: "Konverter nettstedssider til PPTX med Web 2 PowerPoint",
    description: "Web 2 PowerPoint finner tilgjengelige sider, konverterer de valgte og returnerer en separat PPTX for hver side.",
    lead: "Gi Web 2 PowerPoint en offentlig adresse. Appen finner tilgjengelige sider, konverterer valgte URL-er og returnerer flere lenker til presentasjoner.",
    sections: [
      { heading: "1. Oppgi nettstedet", body: "Send den første offentlige URL-en og definer nettstedets omfang tydelig. Eksterne domener og private sider inkluderes ikke uten varsel." },
      { heading: "2. Bekreft tilgjengelige sider", body: "Kontroller den funne listen før konvertering. Bare valgte og tilgjengelige sider sendes til Page 2 File." },
      { heading: "3. Last ned separate PPTX-filer", body: "Hver konverterte side leveres som en egen presentasjon. Appen lover ikke én kombinert presentasjon av hele nettstedet." },
    ],
    externalLinkKey: "web2powerpointGpt",
    primaryLabel: "Åpne Web 2 PowerPoint",
    articleLinks: [{ slug: "website-to-powerpoint", label: "Konverter et nettsted til PowerPoint" }, { slug: "screenshot-vs-editable-powerpoint", label: "Lysbilder som bilder eller redigerbare" }],
    relatedRoutes: gptRoutes,
  },
  "export-ai-chat-to-pdf": {
    route: "export-ai-chat-to-pdf",
    eyebrow: "Eksport av AI-chatter",
    title: "Eksporter en samtale fra den aktive fanen",
    description: "Eksporter støttede samtaler fra ChatGPT, Claude, Gemini og Grok til PDF med utvidelsen, midlertidig forhåndsvisning og uten historikk.",
    lead: "Velg det opprinnelige utseendet eller et enkelt lesedokument. Utvidelsen eksporterer chatten direkte fra den aktive nettleserfanen.",
    sections: [
      { heading: "Støttede chattegrensesnitt", body: "Page 2 File støtter ChatGPT, Claude, Gemini og Grok samt en forsiktig reserve for andre nettleserchatter.", points: ["ChatGPT", "Claude", "Gemini", "Grok"] },
      { heading: "Opprinnelig utseende", body: "Meldingsgruppering, kodeblokker, tabeller og synlige kildelenker bevares." },
      { heading: "Ryddig dokument", body: "Støttet tekst tilpasses et roligere dokument med bevarte avsendere og lenkemål." },
      { heading: "Uavhengig produkt", body: "Page 2 File er ikke tilknyttet, godkjent eller drevet av noen støttet AI-plattform." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installer utvidelsen",
    articleLinks: [{ slug: "export-ai-chats-privately", label: "Eksporter AI-chatter privat" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typer nettsteder som kan eksporteres" }],
    relatedRoutes: chatRoutes,
  },
  "export-chatgpt-to-pdf": {
    route: "export-chatgpt-to-pdf",
    eyebrow: "Eksport fra ChatGPT",
    title: "Eksporter lange ChatGPT-samtaler til PDF",
    description: "Eksporter synlige ChatGPT-meldinger, kode, tabeller, lenker og lange samtaler fra den aktive fanen til en gjennomgått PDF.",
    lead: "Fang samtalen som vises i den aktive fanen, kontroller sideskift og last ned filen uten en Page 2 File-konto.",
    sections: [
      { heading: "Dette bevares", body: "Meldinger, deltakerrekkefølge, kode, tabeller og synlige lenker vises i forhåndsvisningen." },
      { heading: "To lesestiler", body: "Behold den opprinnelige visuelle rytmen, eller velg et roligere dokument for lesing og utskrift." },
      { heading: "Plattformbegrensninger", body: "Sammenfoldede grener, meldinger som ikke er lastet, og innhold utenfor DOM kan måtte åpnes eller lastes før fangst." },
      { heading: "Ingen offisiell tilknytning", body: "Page 2 File er et uavhengig verktøy og er ikke godkjent eller drevet av OpenAI eller ChatGPT." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installer for ChatGPT",
    articleLinks: [{ slug: "export-chatgpt-conversation-to-pdf", label: "Eksporter en ChatGPT-samtale til PDF" }, { slug: "export-ai-chats-privately", label: "Beskytt data i AI-chatforhåndsvisningen" }],
    relatedRoutes: chatRoutes,
  },
  "export-claude-to-pdf": {
    route: "export-claude-to-pdf",
    eyebrow: "Eksport fra Claude",
    title: "Lagre Claude-samtaler og synlige artefakter",
    description: "Eksporter Claude-samtaler, Markdown, kode, sitater og synlig artefaktkontekst fra den aktive fanen til en gjennomgått PDF.",
    lead: "Etter et tydelig klikk leser utvidelsen den aktive samtalen og oppretter en midlertidig forhåndsvisning for lange svar.",
    sections: [
      { heading: "Lange svar beholder strukturen", body: "Overskrifter, lister, sitater og kode beholder leserekkefølgen." },
      { heading: "Artefaktkontekst", body: "Synlige titler og tilgjengelig artefaktinnhold kan gjengis uten å hevde skjult tilgang." },
      { heading: "Ingen offisiell tilknytning", body: "Page 2 File er et uavhengig verktøy og er ikke godkjent av Anthropic." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installer for Claude",
    articleLinks: [{ slug: "export-claude-chat-to-pdf", label: "Eksporter en Claude-chat til PDF" }, { slug: "export-ai-chats-privately", label: "Beskytt data i AI-chatforhåndsvisningen" }],
    relatedRoutes: chatRoutes,
  },
  "export-gemini-to-pdf": {
    route: "export-gemini-to-pdf",
    eyebrow: "Eksport fra Gemini",
    title: "Gjør en Gemini-samtale om til en lesbar PDF",
    description: "Eksporter synlige Gemini-meldinger, kildekort, kode og sitater fra den aktive fanen til en gjennomgått PDF med midlertidig forhåndsvisning.",
    lead: "Kontroller hvordan kildekort og synlige bilder vises før du oppretter et ryddig eller visuelt troverdig dokument.",
    sections: [
      { heading: "Kildene forblir nyttige", body: "Synlige sitater og lenker forblir klikkbare når målene er sikre." },
      { heading: "Bildene følger DOM", body: "Bare medier som er tilgjengelige for den aktive siden, kan vises i den midlertidige forhåndsvisningen." },
      { heading: "Ingen offisiell tilknytning", body: "Page 2 File er uavhengig og er ikke et produkt fra Google eller Gemini." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installer for Gemini",
    articleLinks: [{ slug: "export-gemini-chat-to-pdf", label: "Eksporter en Gemini-chat til PDF" }, { slug: "export-ai-chats-privately", label: "Beskytt data i AI-chatforhåndsvisningen" }],
    relatedRoutes: chatRoutes,
  },
  "export-grok-to-pdf": {
    route: "export-grok-to-pdf",
    eyebrow: "Eksport fra Grok",
    title: "Eksporter Grok-samtaler med synlige kilder",
    description: "Eksporter synlige Grok-samtaler, X-lenker, siterte innlegg og kilder fra den aktive fanen til en gjennomgått PDF.",
    lead: "Fang den aktive samtalen, bevar synlig kildekontekst og velg en visuell forhåndsvisning eller et ryddig lesedokument.",
    sections: [
      { heading: "Leserekkefølge som følger samtalen", body: "Meldinger og kontekst fra siterte innlegg forblir gruppert i stedet for å bli én umerket tekststrøm." },
      { heading: "Synlige X-lenker", body: "Innleggs-URL-er og kilder forblir klikkbare når de består sikkerhetskontrollen." },
      { heading: "Ingen offisiell tilknytning", body: "Page 2 File er et uavhengig produkt og er ikke godkjent av xAI eller X." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installer for Grok",
    articleLinks: [{ slug: "export-other-ai-chats-to-pdf", label: "Eksporter andre AI-chatter til PDF" }, { slug: "export-ai-chats-privately", label: "Beskytt data i AI-chatforhåndsvisningen" }],
    relatedRoutes: chatRoutes,
  },
};
