import type { LandingContent } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

export const norwegianLegalLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  privacy: {
    route: "privacy",
    eyebrow: "Personvern og databehandling",
    title: "Personvernerklæring",
    description: "Slik behandler Page 2 File nettinnhold, midlertidige filer, informasjonskapsler, analysedata og personvernforespørsler.",
    lead: "Denne erklæringen forklarer hvilke opplysninger Page 2 File behandler når du besøker nettstedet, bruker Chrome-utvidelsen eller konverterer en nettside til PDF.",
    sections: [
      { heading: "Behandlingsansvarlig og omfang", body: "{{entityName}}, med adresse {{address}}, driver Page 2 File og er ansvarlig for behandlingen som beskrives. Erklæringen gjelder nettstedet, utvidelsen og tilknyttede konverteringstjenester." },
      { heading: "Definisjoner", body: "«Tjenesten» betyr Page 2 File og funksjonene. «Konverteringsinnhold» omfatter URL, synlig innhold, valg og opprettet PDF. «Personopplysninger» er opplysninger som identifiserer eller med rimelighet kan knyttes til en person." },
      { heading: "Opplysninger vi behandler", body: "Avhengig av bruken kan vi behandle tekniske forespørselsdata, IP-adresse, nettleser og enhet, besøkte sider, tillatte kampanjeparametere, offentlig URL eller synlig innhold i den aktive fanen, innstillinger, midlertidige identifikatorer og opprettede filer." },
      { heading: "Opplysninger vi ikke ber om", body: "Page 2 File krever ingen konto og ber ikke om betalingskort, fakturaadresser eller passord til kildenettstedet. Utvidelsen bruker siden som allerede er åpen, og mottar ikke passordet du brukte." },
      { heading: "Slik bruker vi opplysninger", body: "Vi behandler opplysninger for å levere forhåndsvisninger og filer, hindre misbruk, diagnostisere feil, opprettholde pålitelighet, forstå samlet bruk, besvare forespørsler og følge loven. Vi selger ikke personopplysninger." },
      { heading: "Konverteringsinnhold og midlertidig behandling", body: "Konvertering av en offentlig URL eller forhåndsvisning fra utvidelsen krever midlertidig behandling av siden og valgene. Vi tilbyr ingen kontobasert historikk. Data og filer er kortvarige og slettes når forhåndsvisningen lukkes eller den tekniske tiden utløper." },
      { heading: "Analyse og attribusjon", body: "Når en gyldig ID er konfigurert, lastes Google Analytics på offentlige sider og kan motta data om side, enhet, nettleser, omtrentlig plassering og kampanje. Tillatte UTM-verdier normaliseres i minnet; Page 2 File lagrer dem ikke i en egen attribusjonskapsel." },
      { heading: "Leverandører og utlevering", body: "Page 2 File bruker {{processors}} til å levere, beskytte og måle Tjenesten. De kan bare behandle tekniske data når det er nødvendig og etter egne regler. Vi kan også utlevere opplysninger når loven krever det, for å beskytte rettigheter eller sikkerhet eller ved en lovlig virksomhetsoverføring." },
      { heading: "Lagring og sletting", body: "Konverteringsinnhold lagres bare under den midlertidige prosessen og ikke som synlig historikk. Sikkerhets-, infrastruktur- og analyselogger samt korrespondanse kan lagres så lenge det med rimelighet er nødvendig for drift, rettslige plikter eller en forespørsel." },
      { heading: "Sikkerhet", body: "Page 2 File bruker same-origin-ruter, anonyme økter, Origin- og CSRF-kontroller, signerte forespørsler, URL-validering, isolert gjengivelse og midlertidige filer. Ingen tiltak garanterer absolutt sikkerhet; ikke konverter materiale du ikke kan dele." },
      { heading: "Internasjonal behandling", body: "Leverandørene våre kan behandle tekniske data eller analysedata utenfor landet ditt. Ved behov bruker vi deres garantier og lovlige overføringsmekanismer. Behandlingsansvarlig er etablert i {{jurisdiction}}." },
      { heading: "Dine rettigheter", body: "Avhengig av gjeldende lov kan du be om innsyn, retting, sletting eller begrensning eller protestere mot bestemt behandling. Fordi det ikke finnes kontoer eller konverteringsarkiv, kan vi trenge opplysninger for å finne en relevant driftsoppføring." },
      { heading: "Tredjepartsnettsteder", body: "Page 2 File kan åpne eller konvertere tredjepartsinnhold og lenke til eksterne tjenester. Deres innhold, sikkerhet og personvern styres av disse partene og deres vilkår." },
      { heading: "Barn", body: "Tjenesten er ikke rettet mot barn under 13 år, og vi samler ikke bevisst inn opplysninger om dem. En forelder eller verge kan kontakte oss for sletting." },
      { id: "cookies", heading: "Informasjonskapsler", body: "Page 2 File bruker de kortvarige informasjonskapslene p2f_session og p2f_csrf til å opprettholde en anonym økt og beskytte forespørsler. De bruker SameSite Strict og utløper etter én time. Google Analytics kan sette analysekapsler. Vi lagrer ikke konverteringsinnhold eller direkte identifiserende profiler i dem." },
      { heading: "Blokkering og sletting av informasjonskapsler", body: "Du kan blokkere eller slette informasjonskapsler i nettleseren. Blokkering av økt- eller CSRF-kapsler kan hindre konvertering. Blokkering av Google Analytics begrenser måling, men ikke lasting av offentlige sider. Bruk nettleserinnstillingene for sletting." },
      { heading: "Endringer i erklæringen", body: "Vi kan oppdatere erklæringen når Tjenesten, leverandører eller loven endres. Den nye versjonen publiseres med en dato; vesentlige endringer gjelder fra angitt dag." },
      { heading: "Kontakt", body: "Send spørsmål og personvernforespørsler til {{contactEmail}}. Ansvarlig er {{entityName}}, {{address}}, etter lovene i {{jurisdiction}}." },
    ],
    legal: true,
  },
  terms: {
    route: "terms",
    eyebrow: "Tjenesteavtale",
    title: "Vilkår for bruk av Page 2 File",
    description: "Vilkår for bruk av Page 2 File, inkludert tillatte kilder, begrensninger, ansvar og tilgjengelighet.",
    lead: "Disse Vilkårene regulerer bruken av Page 2 File-nettstedet, Chrome-utvidelsen og tjenestene for konvertering til PDF.",
    sections: [
      { heading: "Godkjenning og operatør", body: "Ved å åpne eller bruke Page 2 File godtar du Vilkårene. Tjenesten drives av {{entityName}}, med adresse {{address}}. Hvis du handler for en organisasjon, bekrefter du at du kan godta Vilkårene på dens vegne." },
      { heading: "Definisjoner", body: "«Tjenesten» omfatter nettstedet, utvidelsen og konverteringsfunksjonene. «Kildeinnhold» er en side, innhold i aktiv fane eller annet sendt materiale. «Resultat» er en PDF, forhåndsvisning eller annen opprettet fil." },
      { heading: "Begrenset lisens", body: "Vi gir deg en tilbakekallbar, ikke-eksklusiv, ikke-overførbar og begrenset rett til å bruke Tjenesten etter Vilkårene. Eierskap til programvare, merkevare eller beskyttet materiale overføres ikke." },
      { heading: "Tillatte kilder og ditt ansvar", body: "Du kan bare konvertere innhold du lovlig kan åpne, behandle, gjengi og laste ned. Du er ansvarlig for URL-er, innhold, innstillinger og bruk eller distribusjon av hvert Resultat." },
      { heading: "Forbudt bruk", body: "Ikke bruk Tjenesten til å bryte lov eller rettigheter, omgå betaling eller kontroller, spre skadevare, sende ulovlig innhold, undersøke private nettverk, forstyrre sikkerhet, overbelaste systemer, automatisere overdrevne forespørsler, tilbakekonstruere beskyttede deler eller fremstille filer feil." },
      { heading: "Kildeinnhold og tredjepartsrettigheter", body: "Du beholder rettighetene til innholdet. Page 2 File gir ingen rettigheter til andres materiale. Du erklærer at behandlingen og Resultatet ikke krenker opphavsrett, personvern, konfidensialitet, avtaler eller andre rettigheter." },
      { heading: "Midlertidig behandling", body: "Tjenesten kan midlertidig behandle innhold, innstillinger og filer for forhåndsvisning og nedlasting. Ingen historikk er knyttet til en konto. Personvernerklæringen beskriver data, informasjonskapsler og leverandører." },
      { heading: "Begrensninger i resultat og trohet", body: "Skript, animasjoner, video, beskyttede medier, skrifter, canvas, dynamiske data og kompleks layout kan ikke alltid gjengis nøyaktig. Accurate copy prioriterer utseendet; Editable document bygger opp støttet tekst, bilder og lenker. Kontroller forhåndsvisningen og Resultatet." },
      { heading: "Tredjepartstjenester og lenker", body: "Tjenesten kan konvertere eller lenke til tredjepartsnettsteder. Page 2 File er ikke ansvarlig for tilgjengelighet, innhold, nøyaktighet, lovlighet, sikkerhet eller personvern. Leverandørens vilkår gjelder." },
      { heading: "Personvern og informasjonskapsler", body: "Personvernerklæringen beskriver midlertidig behandling, analyse, leverandører og informasjonskapsler. Ved å bruke Tjenesten erkjenner du behandlingen som kreves for konverteringen." },
      { heading: "Page 2 Files immaterielle rettigheter", body: "Tjenesten, programvaren, designet, teksten, logoene og annet materiale eies av eller lisensieres til {{entityName}} og er beskyttet. Du kan ikke fjerne merking eller kopiere, selge, underlisensiere eller utnytte Tjenesten kommersielt uten uttrykkelig lovhjemmel." },
      { heading: "Tilbakemeldinger", body: "Hvis du frivillig gir forslag, gir du oss en global, evigvarende og royaltyfri rett til å bruke dem til forbedring eller utvikling uten plikt til betaling. Kildeinnholdet ditt overføres ikke." },
      { heading: "Endringer, oppdateringer og tilgjengelighet", body: "Vi kan oppdatere, begrense, stanse eller avslutte Tjenesten eller funksjoner og innføre grenser for sikkerhet, pålitelighet eller rimelig bruk. Når det er mulig, viser vi vesentlige endringer på nettstedet." },
      { heading: "Suspensjon og opphør", body: "Du kan slutte å bruke Tjenesten når som helst. Vi kan blokkere tilgang ved rimelig mistanke om brudd på Vilkårene, trussel mot systemer eller lovpålagt handling. Bestemmelser som skal fortsette, forblir i kraft." },
      { heading: "Klager om rettigheter", body: "Hvis du mener at materiale via Page 2 File krenker rettighetene dine, kontakt {{contactEmail}} og oppgi verket, materialet eller URL-en, kontaktopplysningene dine og grunnlaget for klagen." },
      { heading: "Ingen garantier", body: "I den grad loven tillater det, leveres Tjenesten og hvert Resultat «som det er» og «etter tilgjengelighet». Vi garanterer ikke uavbrutt drift, feilfri konvertering, full trohet, tredjepartstilgjengelighet, egnethet eller at Resultatet oppfyller alle behov." },
      { heading: "Ansvarsbegrensning", body: "I den grad loven tillater det, er {{entityName}} ikke ansvarlig for indirekte, tilfeldige, særlige, etterfølgende eller straffende tap eller tap av fortjeneste, data, virksomhet, personvern eller kostnader ved bruk eller manglende mulighet til bruk. Rettigheter som ikke kan fravikes, påvirkes ikke." },
      { heading: "Skadesløsholdelse", body: "I den grad loven tillater det, godtar du å forsvare og holde {{entityName}} skadesløs mot tredjepartskrav fra innsendt innhold, bruk eller distribusjon av Resultatet, brudd på Vilkårene eller andres rettigheter." },
      { heading: "Utskillelse, avkall og fullstendig avtale", body: "Hvis en bestemmelse er ugyldig, fortsetter de øvrige å gjelde, og den berørte tolkes så nær formålet som mulig. Manglende håndheving er ikke avkall. Vilkårene og Personvernerklæringen utgjør avtalen." },
      { heading: "Gjeldende lov og tvister", body: "Vilkårene reguleres av lovene i {{jurisdiction}}. Før en prosess forsøker du og {{entityName}} å løse tvisten i god tro gjennom skriftlig varsel. Uløste tvister kan behandles av kompetente domstoler i {{jurisdiction}}, med mindre ufravikelig lov krever noe annet." },
      { heading: "Endringer i vilkårene", body: "Vi kan endre Vilkårene når Tjenesten, leverandører eller loven endres. En ny versjon publiseres med dato. Fortsatt bruk etter ikrafttredelsen betyr godkjenning; ellers må du slutte å bruke Tjenesten." },
      { heading: "Kontakt", body: "Send spørsmål eller varsler til {{contactEmail}} eller {{entityName}}, {{address}}." },
    ],
    legal: true,
  },
};
