import type { LandingContent } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

export const polishLegalLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  privacy: {
    route: "privacy",
    eyebrow: "Prywatność i przetwarzanie danych",
    title: "Polityka prywatności",
    description: "Jak Page 2 File przetwarza treść stron, pliki tymczasowe, cookies, dane analityczne i żądania dotyczące prywatności.",
    lead: "Niniejsza Polityka wyjaśnia, jakie dane Page 2 File przetwarza podczas wizyty w witrynie, używania rozszerzenia Chrome lub konwertowania strony do PDF albo PowerPoint.",
    sections: [
      { heading: "Operator i zakres", body: "{{entityName}}, z siedzibą pod adresem {{address}}, prowadzi Page 2 File i odpowiada za opisane przetwarzanie. Polityka dotyczy witryny, rozszerzenia i powiązanych usług konwersji." },
      { heading: "Definicje", body: "„Usługa” oznacza Page 2 File i jego funkcje. „Treść konwersji” obejmuje URL, widoczną treść, opcje i utworzony PDF lub PowerPoint. „Dane osobowe” to informacje identyfikujące osobę lub możliwe do rozsądnego powiązania z nią." },
      { heading: "Przetwarzane informacje", body: "Zależnie od sposobu użycia możemy przetwarzać dane techniczne żądania, adres IP, przeglądarkę i urządzenie, odwiedzone strony, dozwolone parametry kampanii, publiczny URL lub treść aktywnej karty, ustawienia, identyfikatory tymczasowe i wygenerowane pliki." },
      { heading: "Informacje, których nie żądamy", body: "Page 2 File nie wymaga konta ani nie prosi o karty płatnicze, adresy rozliczeniowe czy hasła do witryny źródłowej. Rozszerzenie używa już otwartej strony i nie otrzymuje hasła użytego do dostępu." },
      { heading: "Jak używamy informacji", body: "Przetwarzamy informacje, aby dostarczać podglądy i pliki, zapobiegać nadużyciom, diagnozować błędy, utrzymywać niezawodność, rozumieć zagregowane użycie, odpowiadać na żądania i przestrzegać prawa. Nie sprzedajemy danych osobowych." },
      { heading: "Treść konwersji i przetwarzanie tymczasowe", body: "Konwersja publicznego URL lub podgląd rozszerzenia wymaga tymczasowego przetwarzania strony i opcji. Nie oferujemy historii powiązanej z kontem. Dane i pliki są krótkotrwałe i usuwane po zamknięciu podglądu lub upływie terminu technicznego." },
      { heading: "Analityka i atrybucja", body: "Gdy skonfigurowano prawidłowy identyfikator, Google Analytics ładuje się na stronach publicznych i może otrzymywać dane o stronie, urządzeniu, przeglądarce, przybliżonej lokalizacji i kampanii. Dozwolone wartości UTM są normalizowane w pamięci; Page 2 File nie zapisuje ich we własnym cookie atrybucji." },
      { heading: "Dostawcy i ujawnianie", body: "Page 2 File korzysta z {{processors}} do świadczenia, ochrony i pomiaru Usługi. Mogą przetwarzać dane techniczne tylko w niezbędnym zakresie i zgodnie ze swoimi politykami. Możemy też ujawnić informacje, gdy wymaga tego prawo, ochrona praw lub bezpieczeństwa albo legalne przejęcie firmy." },
      { heading: "Przechowywanie i usuwanie", body: "Treść konwersji jest przechowywana tylko na czas procesu tymczasowego, a nie jako widoczna historia. Dzienniki bezpieczeństwa, infrastruktury, analityki i korespondencja mogą być przechowywane przez okres rozsądnie potrzebny do działania, obowiązków prawnych lub obsługi żądania." },
      { heading: "Bezpieczeństwo", body: "Page 2 File używa tras tego samego pochodzenia, anonimowych sesji, kontroli Origin i CSRF, podpisanych żądań, walidacji URL, izolowanego renderowania i plików tymczasowych. Żaden środek nie gwarantuje pełnego bezpieczeństwa; nie konwertuj materiału, którego nie wolno ujawnić." },
      { heading: "Przetwarzanie międzynarodowe", body: "Nasi dostawcy mogą przetwarzać dane techniczne lub analityczne poza Twoim krajem. W odpowiednich przypadkach korzystamy z ich zabezpieczeń i legalnych mechanizmów transferu. Operator ma siedzibę w {{jurisdiction}}." },
      { heading: "Twoje prawa", body: "Zależnie od prawa możesz żądać dostępu, sprostowania, usunięcia lub ograniczenia albo sprzeciwić się określonemu przetwarzaniu. Ponieważ nie ma kont ani archiwum konwersji, możemy potrzebować informacji do znalezienia właściwego rekordu operacyjnego." },
      { heading: "Witryny zewnętrzne", body: "Page 2 File może otwierać lub konwertować treści podmiotów trzecich i prowadzić do usług zewnętrznych. Ich treść, bezpieczeństwo i prywatność zależą od tych podmiotów oraz ich warunków." },
      { heading: "Dzieci", body: "Usługa nie jest skierowana do dzieci poniżej 13 lat i nie zbieramy świadomie ich danych. Rodzic lub opiekun może skontaktować się w sprawie usunięcia." },
      { id: "cookies", heading: "Pliki cookie", body: "Page 2 File używa krótkotrwałych cookies p2f_session i p2f_csrf do utrzymania anonimowej sesji i ochrony żądań. Używają SameSite Strict i wygasają po godzinie. Google Analytics może ustawiać cookies analityczne. Nie zapisujemy w nich treści konwersji ani bezpośrednio identyfikujących profili." },
      { heading: "Blokowanie i usuwanie cookies", body: "Możesz blokować lub usuwać cookies w przeglądarce. Zablokowanie cookies sesji lub CSRF może uniemożliwić konwersję. Zablokowanie Google Analytics ogranicza pomiar, ale nie ładowanie stron publicznych. Do usuwania użyj ustawień przeglądarki." },
      { heading: "Zmiany polityki", body: "Możemy aktualizować politykę, gdy zmienia się Usługa, dostawcy lub prawo. Opublikujemy nową wersję z datą; istotne zmiany obowiązują od wskazanego dnia." },
      { heading: "Kontakt", body: "Pytania i żądania dotyczące prywatności wysyłaj na {{contactEmail}}. Operatorem jest {{entityName}}, {{address}}, podlegający prawu {{jurisdiction}}." },
    ],
    legal: true,
  },
  terms: {
    route: "terms",
    eyebrow: "Umowa dotycząca usługi",
    title: "Warunki użytkowania",
    description: "Warunki korzystania z Page 2 File, w tym dozwolone źródła, ograniczenia, odpowiedzialność i dostępność.",
    lead: "Niniejsze Warunki regulują korzystanie z witryny Page 2 File, rozszerzenia Chrome i usług konwersji do PDF lub PowerPoint.",
    sections: [
      { heading: "Akceptacja i operator", body: "Uzyskując dostęp lub korzystając z Page 2 File, akceptujesz te Warunki. Usługę prowadzi {{entityName}}, z siedzibą pod adresem {{address}}. Działając za organizację, potwierdzasz uprawnienie do akceptacji w jej imieniu." },
      { heading: "Definicje", body: "„Usługa” obejmuje witrynę, rozszerzenie i funkcje konwersji. „Treść źródłowa” to strona, treść aktywnej karty lub inny przesłany materiał. „Wynik” to PDF, PowerPoint, podgląd lub inny wygenerowany plik." },
      { heading: "Ograniczona licencja", body: "Udzielamy odwołalnego, niewyłącznego, nieprzenoszalnego i ograniczonego prawa do używania Usługi zgodnie z Warunkami. Nie przenosimy własności oprogramowania, marki ani chronionych materiałów." },
      { heading: "Dozwolone źródła i odpowiedzialność", body: "Możesz konwertować tylko treści, do których masz prawo dostępu, przetwarzania, reprodukcji i pobierania. Odpowiadasz za adresy URL, treść, ustawienia oraz użycie i dystrybucję każdego Wyniku." },
      { heading: "Zakazane użycie", body: "Nie używaj Usługi do naruszania prawa lub praw innych, omijania płatności lub kontroli, rozpowszechniania malware, przesyłania bezprawnych treści, sondowania sieci prywatnych, zakłócania bezpieczeństwa, przeciążania systemów, nadmiernej automatyzacji, inżynierii wstecznej chronionych części ani fałszowania plików." },
      { heading: "Treść źródłowa i prawa osób trzecich", body: "Zachowujesz swoje prawa do treści. Page 2 File nie nadaje praw do materiałów innych osób. Oświadczasz, że przetwarzanie i Wynik nie naruszają praw autorskich, prywatności, poufności, umów ani innych praw." },
      { heading: "Przetwarzanie tymczasowe", body: "Usługa może tymczasowo przetwarzać treść, ustawienia i pliki, aby zapewnić podgląd i pobranie. Nie ma historii powiązanej z kontem. Polityka prywatności opisuje dane, cookies i dostawców." },
      { heading: "Ograniczenia wyniku i wierności", body: "Skrypty, animacje, wideo, chronione media, czcionki, canvas, dane dynamiczne i złożone układy mogą nie zostać odtworzone dokładnie. Accurate copy stawia na wygląd; Editable document odbudowuje obsługiwany tekst, obrazy i łącza. Sprawdź podgląd i Wynik." },
      { heading: "Usługi i łącza zewnętrzne", body: "Usługa może konwertować witryny osób trzecich lub do nich prowadzić. Page 2 File nie odpowiada za ich dostępność, treść, dokładność, legalność, bezpieczeństwo ani prywatność. Obowiązują warunki dostawcy." },
      { heading: "Prywatność i cookies", body: "Polityka prywatności opisuje tymczasowe przetwarzanie, analitykę, dostawców i cookies. Korzystając z Usługi, uznajesz przetwarzanie potrzebne do żądanej konwersji." },
      { heading: "Własność intelektualna Page 2 File", body: "Usługa, oprogramowanie, projekt, tekst, logotypy i inne materiały należą lub są licencjonowane na rzecz {{entityName}} i podlegają ochronie. Nie wolno usuwać oznaczeń ani kopiować, sprzedawać, sublicencjonować lub komercyjnie wykorzystywać Usługi bez wyraźnej zgody prawa." },
      { heading: "Opinie", body: "Dobrowolnie przekazując sugestie, udzielasz nam ogólnoświatowego, wieczystego i bezpłatnego prawa do ich użycia przy rozwoju Usługi, bez obowiązku wynagrodzenia. Nie przenosi to treści źródłowej." },
      { heading: "Zmiany, aktualizacje i dostępność", body: "Możemy aktualizować, ograniczać, zawieszać lub kończyć Usługę albo funkcje oraz nakładać limity bezpieczeństwa, niezawodności lub uczciwego użycia. W miarę możliwości istotne zmiany pokażemy w witrynie." },
      { heading: "Zawieszenie i zakończenie", body: "Możesz przestać używać Usługi w każdej chwili. Możemy zablokować dostęp przy uzasadnionym podejrzeniu naruszenia Warunków, zagrożenia systemów lub wymogu prawnego. Postanowienia przeznaczone do dalszego obowiązywania pozostają w mocy." },
      { heading: "Roszczenia dotyczące praw", body: "Jeśli uważasz, że materiał dostępny przez Page 2 File narusza Twoje prawa, skontaktuj się przez {{contactEmail}} i wskaż utwór, materiał lub URL, swoje dane oraz podstawę roszczenia." },
      { heading: "Brak gwarancji", body: "W zakresie dozwolonym prawem Usługa i każdy Wynik są dostarczane „tak jak są” i „w miarę dostępności”. Nie gwarantujemy ciągłego działania, konwersji bez błędów, pełnej wierności, dostępności stron trzecich, przydatności ani spełnienia wszystkich wymagań." },
      { heading: "Ograniczenie odpowiedzialności", body: "W zakresie dozwolonym prawem {{entityName}} nie odpowiada za szkody pośrednie, przypadkowe, szczególne, następcze lub karne ani utratę zysków, danych, działalności, prywatności czy koszty użycia lub niemożności użycia. Prawa niewyłączalne pozostają nienaruszone." },
      { heading: "Zwolnienie z odpowiedzialności", body: "W zakresie dozwolonym prawem zgadzasz się bronić i zabezpieczać {{entityName}} przed roszczeniami osób trzecich wynikającymi z przesłanej treści, użycia lub dystrybucji Wyniku, naruszenia Warunków albo praw innych." },
      { heading: "Rozdzielność, zrzeczenie i pełna umowa", body: "Jeśli postanowienie jest nieważne, pozostałe obowiązują, a dotknięte będzie interpretowane możliwie blisko celu. Brak egzekwowania nie jest zrzeczeniem. Warunki i Polityka prywatności tworzą umowę." },
      { heading: "Prawo właściwe i spory", body: "Warunki podlegają prawu {{jurisdiction}}. Przed postępowaniem Ty i {{entityName}} spróbujecie rozwiązać spór w dobrej wierze pisemnym zawiadomieniem. Nierozwiązane spory mogą trafić do właściwych sądów {{jurisdiction}}, chyba że prawo bezwzględnie wymaga inaczej." },
      { heading: "Zmiany warunków", body: "Możemy zmieniać Warunki wraz ze zmianami Usługi, dostawców lub prawa. Opublikujemy nową wersję z datą. Dalsze używanie po wejściu w życie oznacza akceptację; w przeciwnym razie należy przestać korzystać." },
      { heading: "Kontakt", body: "Pytania lub zawiadomienia wysyłaj na {{contactEmail}} albo do {{entityName}}, {{address}}." },
    ],
    legal: true,
  },
};
