import type { LandingContent, RelatedRoute } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

const gptRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "page2pdf-gpt", label: "Webpage to PDF Converter — Web2File" },
  { route: "web2pdf-gpt", label: "Web 2 PDF" },
  { route: "html2pdf-gpt", label: "HTML 2 PDF" },
  { route: "one-page2powerpoint-gpt", label: "One Page 2 PowerPoint" },
  { route: "web2powerpoint-gpt", label: "Web 2 PowerPoint" },
];
const chatRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "export-ai-chat-to-pdf", label: "Wszystkie eksporty czatów AI" },
  { route: "export-chatgpt-to-pdf", label: "ChatGPT do PDF" },
  { route: "export-claude-to-pdf", label: "Claude do PDF" },
  { route: "export-gemini-to-pdf", label: "Gemini do PDF" },
  { route: "export-grok-to-pdf", label: "Grok do PDF" },
];

export const polishLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  "page2pdf-gpt": {
    route: "page2pdf-gpt",
    eyebrow: "Aplikacja GPT · dokładne URL-e, PDF-y lub zrzuty ekranu",
    title: "Webpage to PDF Converter — Web2File",
    description: "Webpage to PDF Converter — Web2File konwertuje dokładne publiczne adresy stron i przetwarza przesłane PDF-y stron lub zrzuty ekranu do osobnych plików Visual PDF albo Interactive PDF.",
    lead: "Podaj dokładny publiczny URL, listę dokładnych URL-i, PDF strony internetowej albo pełne lub kolejne zrzuty ekranu. Wybierz Visual PDF, aby zapisać witrynę jako zrzuty, lub Interactive PDF dla zaznaczanego tekstu i aktywnych łączy.",
    sections: [
      { heading: "1. Podaj jeden lub więcej adresów URL", body: "Wyślij publiczny URL, listę dokładnych publicznych URL-i, istniejący PDF strony albo pełne lub kolejne zrzuty ekranu. Każda strona pozostaje osobnym plikiem PDF." },
      { heading: "2. Wybierz typ PDF", body: "Wybierz Visual PDF dla wyniku opartego na obrazach, który stawia wygląd strony na pierwszym miejscu, albo Interactive PDF, gdy ważniejsze są zaznaczany tekst i aktywne łącza. Jeden tryb obowiązuje dla całej listy URL-i." },
      { heading: "3. Konwertuj tylko podane strony", body: "Aplikacja otwiera wyłącznie dokładne publiczne URL-e. Nie przeszukuje domen ani sitemap, nie odkrywa stron, nie podąża za linkami wewnętrznymi i nie omija logowania, paywalli, CAPTCHA, ograniczeń geograficznych ani innych zabezpieczeń. Do odkrywania całej witryny użyj Web2File: Website 2 PDF." },
      { heading: "4. Przetwarzaj PDF-y i zrzuty ekranu", body: "Przesłane zrzuty można połączyć od góry do dołu w Visual PDF. PDF-y stron są przetwarzane bez wymyślania brakującej treści; Interactive PDF zachowuje przede wszystkim istniejący tekst, układ, obrazy i zweryfikowane łącza." },
      { heading: "5. Uzyskaj dopasowane instrukcje i sprawdź wynik", body: "Jeśli bezpośrednia konwersja jest niedostępna lub niepełna, aplikacja podaje instrukcje właściwe dla strony, przeglądarki lub natywnego eksportu. Sprawdź brakującą lub uciętą treść, puste obszary, czytelność, kolejność, układ, łącza i zgodność z trybem." },
    ],
    externalLinkKey: "page2pdfGpt",
    primaryLabel: "Otwórz GPT Webpage 2 PDF",
    articleLinks: [{ slug: "save-webpage-as-pdf", label: "Zapisz stronę internetową jako PDF" }, { slug: "long-webpage-page-breaks", label: "Napraw podziały długich stron" }],
    relatedRoutes: gptRoutes,
    workflowOverride: {
      detailsTitle: "Instrukcja użytkowania",
      firstStageDescription: "Przekaż aplikacji GPT działający adres URL.",
      firstStageLabel: "Wyślij adresy URL",
    },
  },
  "web2pdf-gpt": {
    route: "web2pdf-gpt",
    eyebrow: "Aplikacja GPT · dostępne strony witryny",
    title: "Konwertuj strony witryny do osobnych PDF z Web 2 PDF",
    description: "Web 2 PDF znajduje dostępne strony witryny, konwertuje wybrane i zwraca oddzielny PDF dla każdej strony.",
    lead: "Przekaż Web 2 PDF publiczny adres. Aplikacja może znaleźć dostępne strony, przekonwertować wybrane adresy URL i zwrócić wiele łączy do pobrania — po jednym na stronę.",
    sections: [
      { heading: "1. Podaj witrynę", body: "Wyślij początkowy publiczny URL. Aplikacja znajduje dostępne strony i pokazuje wybrany zakres przed konwersją." },
      { heading: "2. Sprawdź listę stron", body: "Potwierdź, które dostępne strony należą do żądania. Strony wymagające logowania, zablokowane adresy i domeny zewnętrzne są wykluczone." },
      { heading: "3. Pobierz osobne pliki PDF", body: "Każda przekonwertowana strona jest dostarczana jako oddzielny PDF. Web 2 PDF nie obiecuje połączonego dokumentu witryny ani zbioru danych scrapingowych." },
    ],
    externalLinkKey: "web2pdfGpt",
    primaryLabel: "Otwórz aplikację GPT Web 2 PDF",
    articleLinks: [{ slug: "multi-page-website-to-pdf", label: "Konwertuj wielostronicową witrynę do PDF" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typy witryn możliwe do eksportu" }],
    relatedRoutes: gptRoutes,
  },
  "html2pdf-gpt": {
    route: "html2pdf-gpt",
    eyebrow: "Aplikacja GPT · przesłany plik HTML",
    title: "Konwertuj przesłany plik HTML z HTML 2 PDF",
    description: "HTML 2 PDF przyjmuje przesłany plik HTML i zwraca przejrzysty PDF w widocznych granicach renderowania.",
    lead: "Prześlij plik HTML do aplikacji GPT. HTML 2 PDF renderuje go w izolacji i zwraca PDF; ten proces dla surowego pliku jest dostępny tylko w tej aplikacji.",
    sections: [
      { heading: "1. Prześlij plik HTML", body: "Dodaj dokument HTML, który masz prawo przetwarzać. Ten proces zaczyna się od pliku, a nie od publicznego URL strony." },
      { heading: "2. Konwertuj do PDF", body: "Aplikacja zwraca PDF przesłanego dokumentu. Zewnętrzne zasoby, skrypty, niestandardowe czcionki i funkcje przeglądarki mogą się różnić." },
      { heading: "3. Traktuj HTML jako niezaufane dane", body: "Bezpieczne renderowanie wymaga izolacji sieci prywatnych, plików lokalnych i niekontrolowanych skryptów. Wynik jest konwersją dokumentu, nie hostowanym wykonaniem strony." },
    ],
    externalLinkKey: "html2pdfGpt",
    primaryLabel: "Otwórz aplikację GPT HTML 2 PDF",
    articleLinks: [{ slug: "html-to-pdf-safely", label: "Bezpiecznie konwertuj HTML do PDF" }, { slug: "webpage-capture-vs-web-scraping", label: "Przechwytywanie strony a web scraping" }],
    relatedRoutes: gptRoutes,
  },
  "one-page2powerpoint-gpt": {
    route: "one-page2powerpoint-gpt",
    eyebrow: "Aplikacja GPT · jeden publiczny URL",
    title: "Konwertuj URL do PPTX z One Page 2 PowerPoint",
    description: "One Page 2 PowerPoint to wyspecjalizowana aplikacja GPT, która konwertuje publiczny URL i zwraca prezentację PPTX tej strony.",
    lead: "Przekaż aplikacji publiczny URL HTTPS. One Page 2 PowerPoint wysyła stronę do konwersji i zwraca prezentację PPTX gotową do pobrania.",
    sections: [
      { heading: "1. Wyślij publiczny URL", body: "Wklej dokładny adres strony. Aplikacja przetwarza jedną stronę na żądanie i nie przeszukuje reszty witryny." },
      { heading: "2. Odbierz PPTX", body: "Strona zostaje ułożona w prezentację i dostarczona jako plik PowerPoint. Sprawdź granice slajdów oraz wizualne lub edytowalne zastąpienia." },
      { heading: "3. Prywatne karty zachowaj w Chrome", body: "Aplikacja GPT dla publicznych adresów URL nie może przejąć sesji przeglądarki. Gdy źródło jest otwarte po zalogowaniu, użyj rozszerzenia Page 2 File." },
    ],
    externalLinkKey: "onePage2PowerpointGpt",
    primaryLabel: "Otwórz One Page 2 PowerPoint",
    articleLinks: [{ slug: "webpage-to-powerpoint", label: "Konwertuj stronę do PowerPoint" }, { slug: "sections-to-slides", label: "Zamień sekcje strony w slajdy" }],
    relatedRoutes: gptRoutes,
  },
  "web2powerpoint-gpt": {
    route: "web2powerpoint-gpt",
    eyebrow: "Aplikacja GPT · dostępne strony witryny",
    title: "Konwertuj strony witryny do PPTX z Web 2 PowerPoint",
    description: "Web 2 PowerPoint znajduje dostępne strony, konwertuje wybrane i zwraca osobny PPTX dla każdej strony.",
    lead: "Przekaż Web 2 PowerPoint publiczny adres. Aplikacja znajduje dostępne strony, konwertuje wybrane adresy URL i zwraca wiele łączy do prezentacji.",
    sections: [
      { heading: "1. Podaj witrynę", body: "Wyślij początkowy publiczny URL i jasno określ zakres witryny. Domeny zewnętrzne i strony prywatne nie są dodawane bez informacji." },
      { heading: "2. Potwierdź dostępne strony", body: "Sprawdź znalezioną listę przed konwersją. Do Page 2 File trafiają tylko wybrane i dostępne strony." },
      { heading: "3. Pobierz osobne pliki PPTX", body: "Każda przekonwertowana strona jest dostarczana jako niezależna prezentacja. Aplikacja nie obiecuje jednej połączonej prezentacji całej witryny." },
    ],
    externalLinkKey: "web2powerpointGpt",
    primaryLabel: "Otwórz Web 2 PowerPoint",
    articleLinks: [{ slug: "website-to-powerpoint", label: "Konwertuj witrynę do PowerPoint" }, { slug: "screenshot-vs-editable-powerpoint", label: "Slajdy jako zrzuty lub edytowalne" }],
    relatedRoutes: gptRoutes,
  },
  "export-ai-chat-to-pdf": {
    route: "export-ai-chat-to-pdf",
    eyebrow: "Eksport czatów AI",
    title: "Eksportuj rozmowę z aktywnej karty",
    description: "Eksportuj obsługiwane rozmowy ChatGPT, Claude, Gemini i Grok do PDF za pomocą rozszerzenia, tymczasowego podglądu i bez historii.",
    lead: "Wybierz oryginalny wygląd lub prosty dokument do czytania. Rozszerzenie eksportuje rozmowę bezpośrednio z aktywnej karty przeglądarki.",
    sections: [
      { heading: "Obsługiwane interfejsy czatu", body: "Page 2 File obsługuje ChatGPT, Claude, Gemini i Grok oraz ostrożny tryb awaryjny dla innych czatów w przeglądarce.", points: ["ChatGPT", "Claude", "Gemini", "Grok"] },
      { heading: "Oryginalny wygląd", body: "Zachowywane są grupowanie wiadomości, bloki kodu, tabele i widoczne łącza do źródeł." },
      { heading: "Przejrzysty dokument", body: "Obsługiwany tekst zostaje ułożony w spokojniejszy dokument z zachowaniem autorstwa i celów łączy." },
      { heading: "Niezależny produkt", body: "Page 2 File nie jest powiązany, wspierany ani obsługiwany przez żadną z obsługiwanych platform AI." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Zainstaluj rozszerzenie",
    articleLinks: [{ slug: "export-ai-chats-privately", label: "Eksportuj czaty AI prywatnie" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typy witryn możliwe do eksportu" }],
    relatedRoutes: chatRoutes,
  },
  "export-chatgpt-to-pdf": {
    route: "export-chatgpt-to-pdf",
    eyebrow: "Eksport ChatGPT",
    title: "Eksportuj długie rozmowy ChatGPT do PDF",
    description: "Eksportuj widoczne wiadomości ChatGPT, kod, tabele, łącza i długie rozmowy z aktywnej karty do sprawdzonego PDF.",
    lead: "Przechwyć rozmowę widoczną w aktywnej karcie, sprawdź podziały stron i pobierz plik bez zakładania konta Page 2 File.",
    sections: [
      { heading: "Co zostaje zachowane", body: "Wiadomości, kolejność uczestników, kod, tabele i widoczne łącza są odwzorowane w podglądzie." },
      { heading: "Dwa style czytania", body: "Zachowaj oryginalny rytm wizualny lub wybierz spokojniejszy dokument do czytania i druku." },
      { heading: "Ograniczenia platformy", body: "Zwinięte gałęzie, niewczytane wiadomości i treści poza DOM mogą wymagać otwarcia lub wczytania przed przechwyceniem." },
      { heading: "Brak oficjalnego związku", body: "Page 2 File jest niezależnym narzędziem i nie jest wspierany ani obsługiwany przez OpenAI lub ChatGPT." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Zainstaluj dla ChatGPT",
    articleLinks: [{ slug: "export-chatgpt-conversation-to-pdf", label: "Eksportuj rozmowę ChatGPT do PDF" }, { slug: "export-ai-chats-privately", label: "Chroń dane podglądu czatów AI" }],
    relatedRoutes: chatRoutes,
  },
  "export-claude-to-pdf": {
    route: "export-claude-to-pdf",
    eyebrow: "Eksport Claude",
    title: "Zapisuj rozmowy Claude i widoczne artefakty",
    description: "Eksportuj rozmowy Claude, Markdown, kod, cytowania i widoczny kontekst artefaktów z aktywnej karty do sprawdzonego PDF.",
    lead: "Po wyraźnym kliknięciu rozszerzenie odczytuje aktywną rozmowę i tworzy tymczasowy podgląd do sprawdzenia długich odpowiedzi.",
    sections: [
      { heading: "Długie odpowiedzi zachowują strukturę", body: "Nagłówki, listy, cytowania i kod pozostają we właściwej kolejności czytania." },
      { heading: "Kontekst artefaktów", body: "Widoczne tytuły i dostępna treść artefaktów mogą zostać odwzorowane bez sugerowania ukrytego dostępu." },
      { heading: "Brak oficjalnego związku", body: "Page 2 File jest niezależnym narzędziem i nie jest wspierany przez Anthropic." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Zainstaluj dla Claude",
    articleLinks: [{ slug: "export-claude-chat-to-pdf", label: "Eksportuj czat Claude do PDF" }, { slug: "export-ai-chats-privately", label: "Chroń dane podglądu czatów AI" }],
    relatedRoutes: chatRoutes,
  },
  "export-gemini-to-pdf": {
    route: "export-gemini-to-pdf",
    eyebrow: "Eksport Gemini",
    title: "Zamień rozmowę Gemini w czytelny PDF",
    description: "Eksportuj widoczne wiadomości Gemini, karty źródeł, kod i cytowania z aktywnej karty do sprawdzonego PDF z tymczasowym podglądem.",
    lead: "Sprawdź, jak wyglądają karty źródeł i widoczne obrazy, zanim utworzysz przejrzysty lub wizualnie wierny dokument.",
    sections: [
      { heading: "Źródła pozostają użyteczne", body: "Widoczne cytowania i łącza pozostają klikalne, gdy ich cele są bezpieczne." },
      { heading: "Obrazy podążają za DOM", body: "W tymczasowym podglądzie mogą pojawić się tylko multimedia dostępne dla aktywnej strony." },
      { heading: "Brak oficjalnego związku", body: "Page 2 File jest niezależny i nie jest produktem Google ani Gemini." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Zainstaluj dla Gemini",
    articleLinks: [{ slug: "export-gemini-chat-to-pdf", label: "Eksportuj czat Gemini do PDF" }, { slug: "export-ai-chats-privately", label: "Chroń dane podglądu czatów AI" }],
    relatedRoutes: chatRoutes,
  },
  "export-grok-to-pdf": {
    route: "export-grok-to-pdf",
    eyebrow: "Eksport Grok",
    title: "Eksportuj rozmowy Grok z widocznymi źródłami",
    description: "Eksportuj widoczne rozmowy Grok, łącza X, cytowane posty i źródła z aktywnej karty do sprawdzonego PDF.",
    lead: "Przechwyć aktywną rozmowę, zachowaj widoczny kontekst źródeł i wybierz wizualny podgląd lub przejrzysty dokument do czytania.",
    sections: [
      { heading: "Kolejność zgodna z rozmową", body: "Wiadomości i kontekst cytowanych postów pozostają zgrupowane, zamiast tworzyć nieopisany strumień tekstu." },
      { heading: "Widoczne łącza X", body: "Adresy postów i źródła pozostają klikalne, jeśli przejdą kontrolę bezpieczeństwa." },
      { heading: "Brak oficjalnego związku", body: "Page 2 File jest niezależnym produktem i nie jest wspierany przez xAI ani X." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Zainstaluj dla Grok",
    articleLinks: [{ slug: "export-other-ai-chats-to-pdf", label: "Eksportuj inne czaty AI do PDF" }, { slug: "export-ai-chats-privately", label: "Chroń dane podglądu czatów AI" }],
    relatedRoutes: chatRoutes,
  },
};
