import type { LandingContent } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

export const swedishLegalLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  privacy: {
    route: "privacy",
    eyebrow: "Integritet och databehandling",
    title: "Integritetspolicy",
    description: "Så behandlar Page 2 File webbinnehåll, tillfälliga filer, cookies, analysdata och integritetsförfrågningar.",
    lead: "Denna policy förklarar vilka uppgifter Page 2 File behandlar när du besöker webbplatsen, använder Chrome-tillägget eller konverterar en webbsida till PDF eller PowerPoint.",
    sections: [
      { heading: "Personuppgiftsansvarig och omfattning", body: "{{entityName}}, med adress {{address}}, driver Page 2 File och ansvarar för behandlingen som beskrivs. Policyn gäller webbplatsen, tillägget och tillhörande konverteringstjänster." },
      { heading: "Definitioner", body: "”Tjänsten” betyder Page 2 File och dess funktioner. ”Konverteringsinnehåll” omfattar URL, synligt innehåll, val och skapad PDF eller PowerPoint. ”Personuppgifter” är uppgifter som identifierar eller rimligen kan kopplas till en person." },
      { heading: "Uppgifter vi behandlar", body: "Beroende på användning kan vi behandla tekniska begärandedata, IP-adress, webbläsare och enhet, besökta sidor, tillåtna kampanjparametrar, offentlig URL eller synligt innehåll i den aktiva fliken, inställningar, tillfälliga identifierare och skapade filer." },
      { heading: "Uppgifter vi inte begär", body: "Page 2 File kräver inget konto och begär inte betalkortsuppgifter, faktureringsadresser eller lösenord till källwebbplatsen. Tillägget använder den redan öppna sidan och får inte lösenordet du använde." },
      { heading: "Hur vi använder uppgifter", body: "Vi behandlar uppgifter för att leverera förhandsgranskningar och filer, förhindra missbruk, diagnostisera fel, upprätthålla tillförlitlighet, förstå aggregerad användning, besvara förfrågningar och följa lag. Vi säljer inte personuppgifter." },
      { heading: "Konverteringsinnehåll och tillfällig behandling", body: "Konvertering av en offentlig URL eller tilläggets förhandsgranskning kräver tillfällig behandling av sidan och valen. Vi erbjuder ingen kontobaserad historik. Data och filer är kortlivade och raderas när förhandsgranskningen stängs eller den tekniska tiden löper ut." },
      { heading: "Analys och attribuering", body: "När ett giltigt ID har konfigurerats laddas Google Analytics på offentliga sidor och kan ta emot data om sida, enhet, webbläsare, ungefärlig plats och kampanj. Tillåtna UTM-värden normaliseras i minnet; Page 2 File sparar dem inte i en egen attribueringscookie." },
      { heading: "Leverantörer och utlämnande", body: "Page 2 File använder {{processors}} för att leverera, skydda och mäta Tjänsten. De får endast behandla tekniska data när det behövs och enligt sina policyer. Vi kan också lämna ut uppgifter när lagen kräver det, för att skydda rättigheter eller säkerhet eller vid en laglig verksamhetsöverlåtelse." },
      { heading: "Lagring och radering", body: "Konverteringsinnehåll sparas endast under det tillfälliga flödet och inte som synlig historik. Säkerhets-, infrastruktur- och analysloggar samt korrespondens kan sparas så länge det rimligen behövs för drift, rättsliga skyldigheter eller en förfrågan." },
      { heading: "Säkerhet", body: "Page 2 File använder same-origin-rutter, anonyma sessioner, Origin- och CSRF-kontroller, signerade begäranden, URL-validering, isolerad rendering och tillfälliga filer. Ingen åtgärd garanterar full säkerhet; konvertera inte material som du inte får lämna ut." },
      { heading: "Internationell behandling", body: "Våra leverantörer kan behandla tekniska data eller analysdata utanför ditt land. När det krävs använder vi deras skyddsåtgärder och lagliga överföringsmekanismer. Den personuppgiftsansvarige är etablerad i {{jurisdiction}}." },
      { heading: "Dina rättigheter", body: "Beroende på tillämplig lag kan du begära tillgång, rättelse, radering eller begränsning eller invända mot viss behandling. Eftersom det inte finns konton eller konverteringsarkiv kan vi behöva uppgifter för att hitta en relevant driftpost." },
      { heading: "Tredjepartswebbplatser", body: "Page 2 File kan öppna eller konvertera tredjepartsinnehåll och länka till externa tjänster. Deras innehåll, säkerhet och integritet styrs av dessa parter och deras egna villkor." },
      { heading: "Barn", body: "Tjänsten riktar sig inte till barn under 13 år och vi samlar inte medvetet in deras uppgifter. En förälder eller vårdnadshavare kan kontakta oss för radering." },
      { id: "cookies", heading: "Cookies", body: "Page 2 File använder de kortlivade cookies p2f_session och p2f_csrf för att upprätthålla en anonym session och skydda begäranden. De använder SameSite Strict och upphör efter en timme. Google Analytics kan sätta analyscookies. Vi sparar inte konverteringsinnehåll eller direkt identifierande profiler i dem." },
      { heading: "Blockera och radera cookies", body: "Du kan blockera eller radera cookies i webbläsaren. Om sessions- eller CSRF-cookies blockeras kan konvertering sluta fungera. Blockering av Google Analytics begränsar mätning men inte laddning av offentliga sidor. Använd webbläsarens inställningar för radering." },
      { heading: "Ändringar i policyn", body: "Vi kan uppdatera policyn när Tjänsten, leverantörer eller lag ändras. Den nya versionen publiceras med ett datum; väsentliga ändringar gäller från angiven dag." },
      { heading: "Kontakt", body: "Skicka frågor och integritetsförfrågningar till {{contactEmail}}. Ansvarig är {{entityName}}, {{address}}, enligt lagarna i {{jurisdiction}}." },
    ],
    legal: true,
  },
  terms: {
    route: "terms",
    eyebrow: "Tjänsteavtal",
    title: "Villkor för Page 2 File",
    description: "Villkor för användning av Page 2 File, inklusive tillåtna källor, begränsningar, ansvar och tillgänglighet.",
    lead: "Dessa Villkor styr användningen av Page 2 File-webbplatsen, Chrome-tillägget och tjänsterna för konvertering till PDF eller PowerPoint.",
    sections: [
      { heading: "Godkännande och operatör", body: "Genom att öppna eller använda Page 2 File godkänner du Villkoren. Tjänsten drivs av {{entityName}}, med adress {{address}}. Om du agerar för en organisation bekräftar du att du får godkänna Villkoren för den." },
      { heading: "Definitioner", body: "”Tjänsten” omfattar webbplatsen, tillägget och konverteringsfunktionerna. ”Källinnehåll” är en sida, innehåll i aktiv flik eller annat skickat material. ”Resultat” är en PDF, PowerPoint, förhandsgranskning eller annan skapad fil." },
      { heading: "Begränsad licens", body: "Vi ger dig en återkallelig, icke-exklusiv, icke-överlåtbar och begränsad rätt att använda Tjänsten enligt Villkoren. Äganderätt till programvara, varumärke eller skyddat material överförs inte." },
      { heading: "Tillåtna källor och ditt ansvar", body: "Du får endast konvertera innehåll som du lagligen får öppna, behandla, reproducera och hämta. Du ansvarar för URL:er, innehåll, inställningar samt användning och distribution av varje Resultat." },
      { heading: "Förbjuden användning", body: "Använd inte Tjänsten för att bryta mot lag eller rättigheter, kringgå betalningar eller kontroller, sprida skadlig kod, skicka olagligt innehåll, undersöka privata nätverk, störa säkerhet, överbelasta system, automatisera överdrivna begäranden, bakåtkompilera skyddade delar eller vilseleda om filer." },
      { heading: "Källinnehåll och tredje parts rättigheter", body: "Du behåller dina rättigheter till innehållet. Page 2 File ger inga rättigheter till andras material. Du intygar att behandlingen och Resultatet inte bryter mot upphovsrätt, integritet, sekretess, avtal eller andra rättigheter." },
      { heading: "Tillfällig behandling", body: "Tjänsten kan tillfälligt behandla innehåll, inställningar och filer för förhandsgranskning och hämtning. Ingen historik är kopplad till ett konto. Integritetspolicyn beskriver data, cookies och leverantörer." },
      { heading: "Begränsningar i resultat och trohet", body: "Skript, animationer, video, skyddade medier, typsnitt, canvas, dynamiska data och komplex layout kanske inte återges exakt. Accurate copy prioriterar utseendet; Editable document bygger upp text, bilder och länkar som stöds. Granska förhandsgranskningen och Resultatet." },
      { heading: "Tredjepartstjänster och länkar", body: "Tjänsten kan konvertera eller länka till tredje parts webbplatser. Page 2 File ansvarar inte för deras tillgänglighet, innehåll, korrekthet, laglighet, säkerhet eller integritet. Leverantörens villkor gäller." },
      { heading: "Integritet och cookies", body: "Integritetspolicyn beskriver tillfällig behandling, analys, leverantörer och cookies. Genom att använda Tjänsten bekräftar du den behandling som krävs för konverteringen." },
      { heading: "Page 2 Files immateriella rättigheter", body: "Tjänsten, programvaran, designen, texten, logotyperna och annat material ägs eller licensieras av {{entityName}} och skyddas. Du får inte ta bort märkningar eller kopiera, sälja, underlicensiera eller kommersiellt utnyttja Tjänsten utan uttryckligt lagstöd." },
      { heading: "Återkoppling", body: "Om du frivilligt lämnar förslag ger du oss en global, evig och royaltyfri rätt att använda dem för förbättring eller utveckling utan ersättningsskyldighet. Ditt källinnehåll överförs inte." },
      { heading: "Ändringar, uppdateringar och tillgänglighet", body: "Vi kan uppdatera, begränsa, pausa eller avsluta Tjänsten eller funktioner och införa gränser för säkerhet, tillförlitlighet eller skälig användning. När det är möjligt visar vi väsentliga ändringar på webbplatsen." },
      { heading: "Avstängning och upphörande", body: "Du kan sluta använda Tjänsten när som helst. Vi kan blockera åtkomst vid rimlig misstanke om brott mot Villkoren, hot mot system eller lagkrav. Bestämmelser som ska fortsätta gälla förblir i kraft." },
      { heading: "Klagomål om rättigheter", body: "Om du anser att material via Page 2 File kränker dina rättigheter, kontakta {{contactEmail}} och ange verket, materialet eller URL:en, dina uppgifter och grunden för klagomålet." },
      { heading: "Inga garantier", body: "I den utsträckning lagen tillåter tillhandahålls Tjänsten och varje Resultat ”i befintligt skick” och ”i mån av tillgång”. Vi garanterar inte oavbruten drift, felfri konvertering, full trohet, tillgänglighet från tredje part, lämplighet eller att Resultatet uppfyller alla behov." },
      { heading: "Ansvarsbegränsning", body: "I den utsträckning lagen tillåter ansvarar {{entityName}} inte för indirekta, tillfälliga, särskilda, följd- eller straffskador eller förlust av vinst, data, verksamhet, integritet eller kostnader vid användning eller oförmåga att använda. Rättigheter som inte kan avtalas bort påverkas inte." },
      { heading: "Skadeslöshet", body: "I den utsträckning lagen tillåter samtycker du till att försvara och hålla {{entityName}} skadeslös från tredjepartskrav som följer av inskickat innehåll, användning eller distribution av Resultatet, brott mot Villkoren eller andras rättigheter." },
      { heading: "Avskiljbarhet, avstående och fullständigt avtal", body: "Om en bestämmelse är ogiltig fortsätter övriga att gälla och den berörda tolkas så nära syftet som möjligt. Underlåtenhet att verkställa är inte ett avstående. Villkoren och Integritetspolicyn utgör avtalet." },
      { heading: "Tillämplig lag och tvister", body: "Villkoren styrs av lagarna i {{jurisdiction}}. Före en process försöker du och {{entityName}} lösa tvisten i god tro genom skriftligt meddelande. Olösta tvister kan prövas av behörig domstol i {{jurisdiction}}, om inte tvingande lag kräver annat." },
      { heading: "Ändringar i villkoren", body: "Vi kan ändra Villkoren när Tjänsten, leverantörer eller lag ändras. En ny version publiceras med datum. Fortsatt användning efter ikraftträdandet innebär godkännande; annars måste du sluta använda Tjänsten." },
      { heading: "Kontakt", body: "Skicka frågor eller meddelanden till {{contactEmail}} eller {{entityName}}, {{address}}." },
    ],
    legal: true,
  },
};
