import type { LandingContent, RelatedRoute } from "./landings";
import type { StaticRoute } from "@/shared/routes/routes";

const gptRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "page2pdf-gpt", label: "One Page 2 PDF" },
  { route: "web2pdf-gpt", label: "Web 2 PDF" },
  { route: "html2pdf-gpt", label: "HTML 2 PDF" },
  { route: "one-page2powerpoint-gpt", label: "One Page 2 PowerPoint" },
  { route: "web2powerpoint-gpt", label: "Web 2 PowerPoint" },
];
const chatRoutes: ReadonlyArray<RelatedRoute> = [
  { route: "export-ai-chat-to-pdf", label: "Alla exporter av AI-chattar" },
  { route: "export-chatgpt-to-pdf", label: "ChatGPT till PDF" },
  { route: "export-claude-to-pdf", label: "Claude till PDF" },
  { route: "export-gemini-to-pdf", label: "Gemini till PDF" },
  { route: "export-grok-to-pdf", label: "Grok till PDF" },
];

export const swedishLandingContent: Partial<Record<StaticRoute, LandingContent>> = {
  "page2pdf-gpt": {
    route: "page2pdf-gpt",
    eyebrow: "GPT-app · en offentlig URL",
    title: "Konvertera en offentlig URL till PDF med One Page 2 PDF",
    description: "One Page 2 PDF är en specialiserad GPT-app som skickar en offentlig URL för konvertering och returnerar en PDF av den enskilda sidan.",
    lead: "Ge GPT-appen en offentlig HTTPS-URL. One Page 2 PDF skickar adressen till tjänsten Page 2 File och returnerar en nedladdningsbar PDF av den begärda sidan.",
    sections: [
      { heading: "1. Skicka en offentlig URL", body: "Klistra in den exakta HTTPS-adressen till sidan som ska konverteras. Begäran omfattar en sida och startar inte en genomsökning av hela webbplatsen." },
      { heading: "2. Ta emot en PDF", body: "GPT-appen returnerar en länk till en PDF av sidan. Granska text, länkar, bilder och sidbrytningar innan filen används." },
      { heading: "3. Använd rätt omfattning", body: "One Page 2 PDF öppnar inte inloggade flikar och kringgår inte åtkomstkontroller. Använd Page 2 File-tillägget för en sida som redan är öppen efter inloggning." },
    ],
    externalLinkKey: "page2pdfGpt",
    primaryLabel: "Öppna GPT-appen One Page 2 PDF",
    articleLinks: [{ slug: "save-webpage-as-pdf", label: "Spara en webbsida som PDF" }, { slug: "long-webpage-page-breaks", label: "Åtgärda sidbrytningar på långa webbsidor" }],
    relatedRoutes: gptRoutes,
  },
  "web2pdf-gpt": {
    route: "web2pdf-gpt",
    eyebrow: "GPT-app · tillgängliga webbsidor",
    title: "Konvertera webbplatsens sidor till separata PDF-filer med Web 2 PDF",
    description: "Web 2 PDF hittar tillgängliga sidor på en webbplats, konverterar de valda och returnerar en separat PDF för varje sida.",
    lead: "Ge Web 2 PDF en offentlig adress. Appen kan hitta tillgängliga sidor, konvertera valda URL:er och returnera flera hämtningslänkar, en per sida.",
    sections: [
      { heading: "1. Ange webbplatsen", body: "Skicka den första offentliga URL:en. Appen hittar tillgängliga sidor och visar den valda omfattningen före konvertering." },
      { heading: "2. Granska sidlistan", body: "Bekräfta vilka tillgängliga sidor som ingår. Inloggade sidor, blockerade URL:er och externa domäner utesluts." },
      { heading: "3. Hämta separata PDF-filer", body: "Varje konverterad sida levereras som en fristående PDF. Web 2 PDF lovar inte ett sammanslaget webbplatsdokument eller en dataset för scraping." },
    ],
    externalLinkKey: "web2pdfGpt",
    primaryLabel: "Öppna GPT-appen Web 2 PDF",
    articleLinks: [{ slug: "multi-page-website-to-pdf", label: "Konvertera en flersidig webbplats till PDF" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typer av webbplatser som kan exporteras" }],
    relatedRoutes: gptRoutes,
  },
  "html2pdf-gpt": {
    route: "html2pdf-gpt",
    eyebrow: "GPT-app · uppladdad HTML-fil",
    title: "Konvertera en uppladdad HTML-fil med HTML 2 PDF",
    description: "HTML 2 PDF tar emot en uppladdad HTML-fil och returnerar en tydlig PDF inom synliga renderingsgränser.",
    lead: "Ladda upp en HTML-fil i GPT-appen. HTML 2 PDF renderar den isolerat och returnerar en PDF; arbetsflödet för en rå fil finns endast i denna app.",
    sections: [
      { heading: "1. Ladda upp HTML-filen", body: "Lägg till HTML-dokumentet som du har rätt att bearbeta. Arbetsflödet börjar med en fil, inte en offentlig URL till en webbsida." },
      { heading: "2. Konvertera till PDF", body: "Appen returnerar en PDF av det uppladdade dokumentet. Externa resurser, skript, egna typsnitt och webbläsarfunktioner kan variera." },
      { heading: "3. Behandla HTML som osäker indata", body: "Säker rendering kräver isolering av privata nätverk, lokala filer och okontrollerade skript. Resultatet är dokumentkonvertering, inte värdbaserad webbkörning." },
    ],
    externalLinkKey: "html2pdfGpt",
    primaryLabel: "Öppna GPT-appen HTML 2 PDF",
    articleLinks: [{ slug: "html-to-pdf-safely", label: "Konvertera HTML säkert till PDF" }, { slug: "webpage-capture-vs-web-scraping", label: "Sidfångst jämfört med web scraping" }],
    relatedRoutes: gptRoutes,
  },
  "one-page2powerpoint-gpt": {
    route: "one-page2powerpoint-gpt",
    eyebrow: "GPT-app · en offentlig URL",
    title: "Konvertera en URL till PPTX med One Page 2 PowerPoint",
    description: "One Page 2 PowerPoint är en specialiserad GPT-app som konverterar en offentlig URL och returnerar en PPTX-presentation av sidan.",
    lead: "Ge appen en offentlig HTTPS-URL. One Page 2 PowerPoint skickar sidan för konvertering och returnerar en nedladdningsbar PPTX-presentation.",
    sections: [
      { heading: "1. Skicka en offentlig URL", body: "Klistra in sidans exakta adress. Appen bearbetar en sida per begäran och genomsöker inte resten av webbplatsen." },
      { heading: "2. Ta emot en PPTX", body: "Sidan ordnas i en presentation och levereras som en PowerPoint-fil. Granska bildgränser och visuella eller redigerbara ersättningar." },
      { heading: "3. Behåll privata flikar i Chrome", body: "En GPT-app för offentliga URL:er kan inte använda din webbläsarsession. Använd Page 2 File-tillägget när källan är öppen efter inloggning." },
    ],
    externalLinkKey: "onePage2PowerpointGpt",
    primaryLabel: "Öppna One Page 2 PowerPoint",
    articleLinks: [{ slug: "webpage-to-powerpoint", label: "Konvertera en webbsida till PowerPoint" }, { slug: "sections-to-slides", label: "Konvertera sidavsnitt till bilder" }],
    relatedRoutes: gptRoutes,
  },
  "web2powerpoint-gpt": {
    route: "web2powerpoint-gpt",
    eyebrow: "GPT-app · tillgängliga webbsidor",
    title: "Konvertera webbplatsens sidor till PPTX med Web 2 PowerPoint",
    description: "Web 2 PowerPoint hittar tillgängliga sidor, konverterar de valda och returnerar en separat PPTX för varje sida.",
    lead: "Ge Web 2 PowerPoint en offentlig adress. Appen hittar tillgängliga sidor, konverterar valda URL:er och returnerar flera länkar till presentationer.",
    sections: [
      { heading: "1. Ange webbplatsen", body: "Skicka den första offentliga URL:en och definiera webbplatsens omfattning tydligt. Externa domäner och privata sidor läggs inte till i tysthet." },
      { heading: "2. Bekräfta tillgängliga sidor", body: "Granska den hittade listan före konvertering. Endast valda och tillgängliga sidor skickas till Page 2 File." },
      { heading: "3. Hämta separata PPTX-filer", body: "Varje konverterad sida levereras som en fristående presentation. Appen lovar inte en sammanslagen presentation av hela webbplatsen." },
    ],
    externalLinkKey: "web2powerpointGpt",
    primaryLabel: "Öppna Web 2 PowerPoint",
    articleLinks: [{ slug: "website-to-powerpoint", label: "Konvertera en webbplats till PowerPoint" }, { slug: "screenshot-vs-editable-powerpoint", label: "Bilder som sidfångst eller redigerbara" }],
    relatedRoutes: gptRoutes,
  },
  "export-ai-chat-to-pdf": {
    route: "export-ai-chat-to-pdf",
    eyebrow: "Export av AI-chattar",
    title: "Exportera en konversation från den aktiva fliken",
    description: "Exportera konversationer från ChatGPT, Claude, Gemini och Grok till PDF med tillägget, en tillfällig förhandsgranskning och utan historik.",
    lead: "Välj det ursprungliga utseendet eller ett enkelt läsdokument. Tillägget exporterar chatten direkt från den aktiva webbläsarfliken.",
    sections: [
      { heading: "Chattgränssnitt som stöds", body: "Page 2 File stöder ChatGPT, Claude, Gemini och Grok samt ett försiktigt reservläge för andra webbläsarchattar.", points: ["ChatGPT", "Claude", "Gemini", "Grok"] },
      { heading: "Ursprungligt utseende", body: "Meddelandegruppering, kodblock, tabeller och synliga källänkar bevaras." },
      { heading: "Tydligt dokument", body: "Text som stöds anpassas till ett lugnare dokument med bevarade avsändare och länkmål." },
      { heading: "Oberoende produkt", body: "Page 2 File är inte anslutet till, godkänt eller drivet av någon AI-plattform som stöds." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installera tillägget",
    articleLinks: [{ slug: "export-ai-chats-privately", label: "Exportera AI-chattar privat" }, { slug: "website-types-to-pdf-or-powerpoint", label: "Typer av webbplatser som kan exporteras" }],
    relatedRoutes: chatRoutes,
  },
  "export-chatgpt-to-pdf": {
    route: "export-chatgpt-to-pdf",
    eyebrow: "Export från ChatGPT",
    title: "Exportera långa ChatGPT-konversationer till PDF",
    description: "Exportera synliga ChatGPT-meddelanden, kod, tabeller, länkar och långa konversationer från den aktiva fliken till en granskad PDF.",
    lead: "Fånga konversationen som syns i den aktiva fliken, granska sidbrytningar och hämta filen utan ett Page 2 File-konto.",
    sections: [
      { heading: "Det här bevaras", body: "Meddelanden, deltagarordning, kod, tabeller och synliga länkar visas i förhandsgranskningen." },
      { heading: "Två lässtilar", body: "Behåll den ursprungliga visuella rytmen eller välj ett lugnare dokument för läsning och utskrift." },
      { heading: "Plattformens begränsningar", body: "Infällda grenar, ej inlästa meddelanden och innehåll utanför DOM kan behöva öppnas eller läsas in före fångst." },
      { heading: "Ingen officiell koppling", body: "Page 2 File är ett oberoende verktyg och stöds eller drivs inte av OpenAI eller ChatGPT." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installera för ChatGPT",
    articleLinks: [{ slug: "export-chatgpt-conversation-to-pdf", label: "Exportera en ChatGPT-konversation till PDF" }, { slug: "export-ai-chats-privately", label: "Skydda data i AI-chattens förhandsgranskning" }],
    relatedRoutes: chatRoutes,
  },
  "export-claude-to-pdf": {
    route: "export-claude-to-pdf",
    eyebrow: "Export från Claude",
    title: "Spara Claude-konversationer och synliga artefakter",
    description: "Exportera Claude-konversationer, Markdown, kod, citat och synlig artefaktkontext från den aktiva fliken till en granskad PDF.",
    lead: "Efter ett uttryckligt klick läser tillägget den aktiva konversationen och skapar en tillfällig förhandsgranskning för långa svar.",
    sections: [
      { heading: "Långa svar behåller strukturen", body: "Rubriker, listor, citat och kod behåller sin läsordning." },
      { heading: "Artefaktkontext", body: "Synliga rubriker och tillgängligt artefaktinnehåll kan återges utan påståenden om dold åtkomst." },
      { heading: "Ingen officiell koppling", body: "Page 2 File är ett oberoende verktyg och stöds inte av Anthropic." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installera för Claude",
    articleLinks: [{ slug: "export-claude-chat-to-pdf", label: "Exportera en Claude-chatt till PDF" }, { slug: "export-ai-chats-privately", label: "Skydda data i AI-chattens förhandsgranskning" }],
    relatedRoutes: chatRoutes,
  },
  "export-gemini-to-pdf": {
    route: "export-gemini-to-pdf",
    eyebrow: "Export från Gemini",
    title: "Omvandla en Gemini-konversation till en läsbar PDF",
    description: "Exportera synliga Gemini-meddelanden, källkort, kod och citat från den aktiva fliken till en granskad PDF med tillfällig förhandsgranskning.",
    lead: "Granska hur källkort och synliga bilder visas innan du skapar ett tydligt eller visuellt troget dokument.",
    sections: [
      { heading: "Källorna förblir användbara", body: "Synliga citat och länkar förblir klickbara när deras mål är säkra." },
      { heading: "Bilderna följer DOM", body: "Endast medier som är tillgängliga för den aktiva sidan kan visas i den tillfälliga förhandsgranskningen." },
      { heading: "Ingen officiell koppling", body: "Page 2 File är oberoende och är inte en produkt från Google eller Gemini." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installera för Gemini",
    articleLinks: [{ slug: "export-gemini-chat-to-pdf", label: "Exportera en Gemini-chatt till PDF" }, { slug: "export-ai-chats-privately", label: "Skydda data i AI-chattens förhandsgranskning" }],
    relatedRoutes: chatRoutes,
  },
  "export-grok-to-pdf": {
    route: "export-grok-to-pdf",
    eyebrow: "Export från Grok",
    title: "Exportera Grok-konversationer med synliga källor",
    description: "Exportera synliga Grok-konversationer, X-länkar, citerade inlägg och källor från den aktiva fliken till en granskad PDF.",
    lead: "Fånga den aktiva konversationen, bevara synlig källkontext och välj en visuell förhandsgranskning eller ett tydligt läsdokument.",
    sections: [
      { heading: "Läsordning som följer konversationen", body: "Meddelanden och kontext från citerade inlägg förblir grupperade i stället för att bli en omärkt textström." },
      { heading: "Synliga X-länkar", body: "Inläggens URL:er och källor förblir klickbara när de klarar säkerhetskontrollen." },
      { heading: "Ingen officiell koppling", body: "Page 2 File är en oberoende produkt och stöds inte av xAI eller X." },
    ],
    externalLinkKey: "chromeExtension",
    primaryLabel: "Installera för Grok",
    articleLinks: [{ slug: "export-other-ai-chats-to-pdf", label: "Exportera andra AI-chattar till PDF" }, { slug: "export-ai-chats-privately", label: "Skydda data i AI-chattens förhandsgranskning" }],
    relatedRoutes: chatRoutes,
  },
};
